### ISSUE TITLE
Command line version doesn't load singletons

### ISSUE THREAD

**Issue by caryoscelus** [bitwes/Gut#10]
So the same test may pass when called from scene and fail to run (it just shows the testing window and keeps counting time, without reporting failure or quitting) when called from command line script.

**Comment by bitwes** [comment]
I have it loading at least one.  Are you using more than one?

**Comment by bitwes** [comment]
I just double checked the code and it should load all singletons in the config file.  Can provide a sample that doesn't work?

**Comment by caryoscelus** [comment]
Sure. Will upload one after inspecting stuff myself. I looked into logs more carefully now and the relevant lines seems to be these:
```
SCRIPT ERROR: load_auto_load_scripts: Invalid call. Nonexistent function 'new' in base 'PackedScene'.
   At: res://test/gut/gut_cmdln.gd:319
```

**Comment by caryoscelus** [comment]
At some point i got this:

```
ERROR: load: Failed loading resource: *res://external/logger/logger.gd
```

So i guesses the problem was in that `*` and removed it in loading code. Now with that loading kinda works, except that they are not put into globals and thus script using them still fail.

**Comment by caryoscelus** [comment]
Anyway, i think that autoload should just reuse Godot code, so i'll look into that.

**Comment by caryoscelus** [comment]
Filled upstream issue https://github.com/godotengine/godot/issues/6360
If it's going to be fixed, we can close this. Otherwise, it might be a good idea to call scene from command line instead (and add option parsing there).

**Comment by bitwes** [comment]
I read the upstream issue and it jogged my memory.  One workaround would be to create your own test class that inherits from the Gut test class.  You could load up whatever you needed and then use that class as the base for all your tests.  It should just work though.  The code in the command line tool loads up all scripts listed, so I'm not sure what is going wrong.  A sample will help.  Maybe it's an ordering issue.  I could be loading them in a different order than the engine does.

**Comment by caryoscelus** [comment]
http://my-files.ru/Save/srwxs5/atest.zip

But it's just a simplest regular project. Maybe you were trying with old project format? Cause i see no way that code would work with current format, when singletons are denoted with * in path.

Anyhow, i'd rather see it implemented in the engine rather than load manually. Especially since it's literally couple lines of code there. Though i guess it can take time with nobody caring about that issue.

**Comment by bitwes** [comment]
Ahhh, I hadn't realized the format changed.  Must have missed that earlier.  I think all my projects that use Gut have been around since 1.0.  I'll take a look this weekend.  Should be able to work around it.

**Comment by bitwes** [comment]
Can you autoload scenes as well?  I didn't know you could do that.  That would be another bug if you could.

**Comment by caryoscelus** [comment]
Yes, you can. I don't think it makes sense to remake all the work made in the engine, though.

**Comment by caryoscelus** [comment]
Well, Godot devs accepted the patch (https://github.com/godotengine/godot/pull/6413), so it should work fine in master.

**Comment by ericdsw** [comment]
Hey @caryoscelus, sorry to add to this issue so late but, How does this work in the latest master branch? I already compiled the latest 2.1 version (2.1.5-beta) from source and I'm trying to use the generated executable to run the command line version, but the same error occurs. Is there a parameter that I have to add to the command? I'm using the example defined in the **alias** section:

```
godot -d -s addons/gut/gut_cmdln.gd -gdir=res://test/unit,res://test/integration -gexit -gignore_pause
```

**Comment by caryoscelus** [comment]
@ericdsw i'm no longer using Godot, so i can't help you here. But you should probably specify the error you're getting in more details because in this thread i describe few different ones.

**Comment by ericdsw** [comment]
@caryoscelus Sure, running my tests directly from the test scene works, but when I try to run them from the `gut_cmdln.gd` script, they fail as soon as one script tries to access a global reference with the error `Parse Error: Identifier not found: AutoloadName` (I'm referencing my autoloads directly via their name instead of using `get_node("/root/AutoloadName")`).

I already made a workaround that removes the issue with the `*` character, and both scenes and scripts instance correctly and are added to the tree. My problem boils down to not being able to use my autoloads via their name, as using get_node() with their full path works fine.

**Comment by bitwes** [comment]
@ericdsw Can you make an issue on the gut repo?  I'll try to address it, if nothing else I'll document your workaround.

https://github.com/bitwes/Gut/issues
