### ISSUE TITLE
Include subdirectories option ignored when running from command line using gutconfig.json

### ISSUE THREAD

**Issue by Xrayez** [bitwes/Gut#104]
Tested in GUT 6.6.2, Godot 3.1 beta, godot_3_1 branch

The fix is:
```gdscript
into.include_subdirs = get_value(results.result, 'include_subdirs', false)
```
To be added here:
https://github.com/bitwes/Gut/blob/3f4d31e6b75d6ecb4fed3bfd8dacd9f6f8f154c6/addons/gut/gut_cmdln.gd#L410-L411

Seems to be missing in all versions so giving this up to you! :P

My `.gutconfig.json`:
```json
{
    "include_subdirs":true,
    "dirs":[
        "res://tests/"
    ],
    "should_exit":false,
    "ignore_pause":true,
    "log": 1,
    "should_maximize":true
}
```

**Comment by bitwes** [comment]
Good catch.  I noticed this the other day when making a tutorial for setting up the command line.  I quickly removed it from the wiki and plan to add it back in.  Might take this opportunity to get all the options in there.  I think I can do it more dynamically than I currently am.

**Comment by bitwes** [comment]
This will be fixed in the next release.  Some names may change to be more consistent between the config file and the command line options.  They will be listed in the change nots.
