### ISSUE TITLE
Add should exit option on success and/or failure as command line option

### ISSUE THREAD

**Issue by Xrayez** [bitwes/Gut#105]
Not sure if it's possible already, but this would enhance GUT:
```json
{
  "should_exit_on_success":true,
  "should_exit_on_failure":false
}
```
`should_exit` can be kept for compatibility.

**Comment by bitwes** [comment]
I originally added the should_exit for the command line, bit I can see this being useful when running the scene.  These could be added to the scene options.  I don't see a need for them at the command line.

**Comment by Xrayez** [comment]
Notice I'm proposing this feature as command line option.

The reason why it's useful from command line is for CI-like behavior. In fact I don't run GUT from command line directly, it's mostly executed via git pre-commit hook relying on `gutconfig.json` at the same time. 

So in this case I'd like GUT to close the window and commit changes on success *automatically*, but I'd also like to prevent GUT exiting in case any test fail before I close the window *manually* to inspect it further. But `should_exit` option does it in any case which is inconvenient.

For example I have these Travis CI email notifications setup similarly in one of my repos:
```yaml
notifications:
  email:
    on_success: never
    on_failure: always
```

**Comment by bitwes** [comment]
Ok.  You make a decent enough case.  I think this might just be the addition of `should_exit_on_success`.  I think between `should_exit` and `should_exist_on_success` we can cover all the bases.  I can't think of a case where you would want to exit on failure but not on success.  So with those two options you can never exit, exit when everything passes, or always exit.  These should be added to both the command line and the scene options.

Do you have a way to differentiate between an exit and it quitting b/c of a runtime error?

As a workaround, Gut has a `get_fail_count` method you could use to check yourself.  You could make your own runnable scene that had a Gut in it.  You could configure the instance through code or the editor and then add code to the `_init` method that would check for any failing tests with `get_fail_count` and then `quit()` based on the results.  This might give you some extra control over how Gut runs in your CI environment which could be helpful down the road and you wouldn't have to wait for this to be implemented.  I think it's a decent enough option to add, but I don't know when it will make it in.  Probably soon, it won't take much and I'm in the middle of another release.

**Comment by Xrayez** [comment]
> So with those two options you can never exit.

Yes seems like a good compromise.

> Do you have a way to differentiate between an exit and it quitting b/c of a runtime error?

I guess the `OS.exit_code` should contain an error code other than `1` (indicating failing tests), if that's what you mean. Other than that the changes are committed when git hook receives `0` error code on exit, so it's not an issue.

As a bonus here's a piece of code to indicate manual quit in either case that might be of use for someone (I've changed existing error codes for this to make more sense):
```gdscript
extends SceneTree

enum TestExitCode {
    FAIL = -1
    FAIL_MANUAL_QUIT = -2
    SUCCESS = 0,
    SUCCESS_MANUAL_QUIT = 1
}

func _notification(what):
    match what:
        NOTIFICATION_WM_QUIT_REQUEST:
            match OS.exit_code:
                FAIL:
                    # Indicate manual quit on fail
                    OS.exit_code = FAIL_MANUAL_QUIT
                SUCCESS:
                    # Indicate manual quit on success
                    OS.exit_code = SUCCESS_MANUAL_QUIT		
```
The git hook could interpret these exit codes whatever it likes. That's too big to ask for though and might add more complexity.

No worries, I can always patch GUT to suit my needs at the moment, especially usability feature like this, just giving some ideas.

**Comment by bitwes** [comment]
Threw it in there for ya in 6.8.0.

**Comment by Xrayez** [comment]
Thanks, I tested this while it was just added, works alright for me so far, certainly speeds up my dev/pre-test/commit workflow, updated to 6.8.0 now.
