### ISSUE TITLE
Connection based asserts

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#113]
Add asserts that verify an object is connected to a signal on another object.  It should be able to verify that an object is connected to another object without having to know the method that it uses for the connection.  The methods used for connections are usually private and it is helpful to verify that an object is "just" connected, and not the details of the connection.

This ordering of parameters is backwards from how `connect` is used but it makes more sense to me grammatically.  The naming and ordering of parameters is up for discussion.
```
assert_connected(obj_that_connects, obj_connected_to, signal_name, (optional)method_name)
```
Example
```
button.connect('pressed', self, '_on_button_pressed')
assert_connected(self, button, 'pressed')
assert_connected(self, button, 'pressed', '_on_button_pressed')
```
If the test fails it should list any connections between the objects to aid in debugging.  In the example above it would list connections between `self` and `button` and vice versa.  It may also be a good idea to list all connections that `self` has if that is possible.

There should be an `assert_not_connected` as well.

**Comment by ssd71** [comment]
I would like to work on this

**Comment by bitwes** [comment]
Great!  If you need any more details not covered in the description post here.  Also, if you would like any feedback, just let me know or open up a Pull Request.
