### ISSUE TITLE
I cant get more than 6-9fps on android phone(not x86 emulator) after adding a directional light in GODOT ENGINE

### ISSUE THREAD

**Issue by ozzr** [bitwes/Gut#116]
I am trying to create simple 3d game for android using godot but when i add a single directional light to the scene on export i cant get more than a few unplayable fps on my phone, i only have put a single low poli character, dont have anything else in the scene, i have tryed changing the preferences but nothing changes so i ended up taking away the lights and using unshaded materials but it is not what i would like to use.
DOES ANYONE KNOW HOW TO SOLVE THIS?

**Comment by bitwes** [comment]
I believe you have opened this issue on the wrong repo.

**Comment by schweigert** [comment]
Hi @ozzr . This repository is used to keep the Gut plugin code. This is not Godot Engine's official repo. You can report this issue in the official repository (https://github.com/godotengine/godot).

You can mention me (@schweigert) in the new issue to help you (and do not pollute this repository).
