### ISSUE TITLE
Stray Nodes exist after use.

### ISSUE THREAD

**Issue by CodeDarigan** [bitwes/Gut#122]
3.1

Installed GUT via AssetLib. Implemented the test script in the Wikia. Used print stray nodes to get this:

![image](https://user-images.githubusercontent.com/47497501/58877104-d9ab3200-86c7-11e9-910d-5ce63baeeabd.png)

If the GUT Scene wasn't a tool, this covers everything:

```
func _notification(what):
	if what == NOTIFICATION_EXIT_TREE:
		queue_free()
```

But being a tool causes more issues.

**Comment by bitwes** [comment]
Neat!  I didn't know about print stray nodes.  This might help me clean
things up at the end.  Was this after a run or during a test?

**Comment by CodeDarigan** [comment]
It was after the first run of tests.

**Comment by bitwes** [comment]
I've tried numerous approaches to free up these nodes when running from the command line.  I've not had any luck.  I've tried using a timer to put some time between releasing the GUT object (`_tester`) and the `quit` but that didn't change anything.

Any suggestions are welcomed.  Although it is ugly to have the errors at the end, they don't affect anything.  Each object is in use right up to the point of quitting.  It's slightly more important now that the VSCode extension exists and it causes you to have to scroll more in the terminal to see the results.

**Comment by CodeDarigan** [comment]
I don't know to be honest. I will say though that stray nodes themselves don't actually really matter (unless you are leaking) because sometimes they are only temporaily stray.

**Comment by bitwes** [comment]
@hilfazer opened a PR that got rid of most of the leaks.  I've been able to take that code and add a little more and should be able to get the orphans down to zero.  These changes will be in the 7.0.0 release.

**Comment by bitwes** [comment]
No more leaks by GUT in 7.0.0!  See Memory Management wiki page for info on tools and options.

**Comment by drwhut** [comment]
I've started using Gut 7.4.1 in my project, and I've noticed that it has a lot of memory leaks when exiting Godot.

For context, I've downloaded the add-on via the in-engine AssetLib on the official 3.5.2 build (`Godot_v3.5.2-stable_x11.64`) to a newly created project with no tests or configuration files made, and this is the output when running the engine with `--verbose`:

[gut.log](https://github.com/bitwes/Gut/files/11121772/gut.log)

**Comment by drwhut** [comment]
Are there any plans to fix this at all?

**Comment by bitwes** [comment]
Please create a new issue for this.  I can only reproduce what you've posted when I quit Godot.  GUT doesn't orphan any nodes when running tests via the command line, or running tests in the editor (which is what this issue is concerned about).  Maybe I'm not freeing up the panel the way I should.  Creating orphans during a run is annoying, but I'm not sure how concerned I am about leaks when exiting the editor.
