### ISSUE TITLE
Add "only" and "skip" support

### ISSUE THREAD

**Issue by levilindsey** [bitwes/Gut#123]
I've sometimes seen other test libraries call such functions "iit"/"xit" or "it.only"/"it.skip".

When debugging failing tests, it is super useful to be able to temporarily prevent all other tests from running except for the one test you're debugging.

Similarly, it can helpful to skip a problematic test that you want to deal with later and running it in the meantime would just generate noise.

**Comment by bitwes** [comment]
Got ya covered, it's already in there.  You can specify a script to run (by
name, not path so it's pretty friendly), any test containing a string in
the name, and an inner class.  You can combine these to get pretty granular
with what is run.  These settings are covered in the wiki and the command
line tutorial on the tutorial wiki page covers using them there.

**Comment by bitwes** [comment]
For skipping, you can use "pending" and return after.  Pending takes an optional description.  All pending tests are listed at the end with any failures if there are any.

**Comment by levilindsey** [comment]
Ah, right, that makes sense. I hadn't read that far through the docs yet, I guess. Thanks!
