### ISSUE TITLE
Add posible to test native C++ scripts with gtest(Google testing framework)

### ISSUE THREAD

**Issue by Jesus05** [bitwes/Gut#132]

**Comment by bitwes** [comment]
Can you elaborate on this?  From the title it sounds like this would be an engine thing and not a GUT thing.

**Comment by schweigert** [comment]
You can test native code with gut. Just add nodes with these scripts to a scene and test the behavior. Tests should test behavior, not small snippets of your code.

However, gtest is a C testing tool. You can write tests, but you can only test part that has no graphics engine dependency (Or mock this dependency).

This sounds like a tricky thing to do, but in web development the concept of clean architecture was created to decouple infrastructure from the business rule (your script). Using similar logic, you can decouple and test native code in C / C ++.

But only by explanation do we realize that this is a very complex thing to keep. Unless it's very important for business rule, you might also consider not creating unit tests for native code, just for the scene-based behavior you created in the editor.
