### ISSUE TITLE
Option to disable Debug Console

### ISSUE THREAD

**Issue by FeralBytes** [bitwes/Gut#134]
The debug console is a handy feature when I am using GUT from my computer. But when I have GUT being run as part of CI, it hangs the runner. I would like to have an option to have the debugger just exit with an error and print the line of the error and reason.

**Comment by bitwes** [comment]
Are you talking about when you run from the command line?  Is this when an error occurs or when the tests finish?

**Comment by FeralBytes** [comment]
Yes, when run from the command line. If there is an error in the code, it will jump to the debug console. That is a good feature, but I would like the option to disable this behavior for CI. This is definitely an edge case so no rush. The reason it is an edge case, is at my work I can not use personal computers nor can I use Godot. But what I do, is I will edit the code via gitlab's Web IDE, which is why I sometimes cause an error or a typo; which in turn triggers the debug mode.
Thank you for your time.

**Comment by bitwes** [comment]
Does it do this when you don't give the `-d` flag?  If so, I don't think there is anything I can do from the GUT side.  It's all engine behavior.

**Comment by FeralBytes** [comment]
@bitwes sorry for taking so long to test this. I removed the ```-d``` flag but it caused an unexpected result, with an error built into the code, faulty code. GUT succeeded even though no asserts were run from the tests. See the output below and let me know what other details you need.

```shell
71 $ $DOCKER_HOME/godot_editor/Godot_v3.2-beta2_linux_headless.64 -s --path $DOCKER_HOME/godot/ $DOCKER_HOME/godot/addons/gut/gut_cmdln.gd
72 Godot Engine v3.2.beta2.official - https://godotengine.org
73  
74 ERROR: register_scene_types: Error loading custom font 'res://assets/fonts/BlackOpsOne-Regular.ttf'
75    At: scene/register_scene_types.cpp:754.
76  ---  Gut  ---
77 Godot version:  3.2.0
78 GUT version:  6.8.0
79 [ERROR]  The path [res://tests/integration/] does not exist.
80 /-----------------------------------------
81 Running Script res://tests/unit/test_TileMap.gd
82 -----------------------------------------/
83 SCRIPT ERROR: GDScript::reload: Parse Error: Expected indented block after "for".
84    At: built-in:258.
85 ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
86    At: modules/gdscript/gdscript.cpp:576.
87 SCRIPT ERROR: before_all: Invalid set index 'g_width' (on base: 'Node2D') with value of type 'int'.
88    At: res://tests/unit/test_TileMap.gd:10.
89 * test_grid_generates_flat_id_array
90 SCRIPT ERROR: test_grid_generates_flat_id_array: Invalid get index 'grid_id_array_built' (on base: 'Node2D').
91    At: res://tests/unit/test_TileMap.gd:26.
92 * test_grid_flat_array_id_equals_offset_x_y_by_width
93 SCRIPT ERROR: test_grid_flat_array_id_equals_offset_x_y_by_width: Invalid get index 'grid_id_array_built' (on base: 'Node2D').
94    At: res://tests/unit/test_TileMap.gd:31.
95 * test_grid_flat_id_array_no_duplicates
96 SCRIPT ERROR: test_grid_flat_id_array_no_duplicates: Invalid get index 'grid_id_array' (on base: 'Node2D').
97    At: res://tests/unit/test_TileMap.gd:39.
98 * test_grid_flat_to_offset
99 SCRIPT ERROR: test_grid_flat_to_offset: Invalid get index 'grid_id_array' (on base: 'Node2D').
100    At: res://tests/unit/test_TileMap.gd:45.
101 * test_grid_calc_flat_to_offset
102 SCRIPT ERROR: test_grid_calc_flat_to_offset: Invalid get index 'grid_id_array' (on base: 'Node2D').
103    At: res://tests/unit/test_TileMap.gd:49.
104 * test_offset_to_flat
105 SCRIPT ERROR: test_offset_to_flat: Invalid get index 'grid_id_array' (on base: 'Node2D').
106    At: res://tests/unit/test_TileMap.gd:54.
107 * test_offset_to_flat_limit
108     Pending
109 * test_grid_offset_to_cube
110 SCRIPT ERROR: test_grid_offset_to_cube: Invalid get index 'grid_id_array' (on base: 'Node2D').
111    At: res://tests/unit/test_TileMap.gd:85.
112 * test_grid_flat_to_cube
113 SCRIPT ERROR: test_grid_flat_to_cube: Invalid get index 'grid_id_array' (on base: 'Node2D').
114    At: res://tests/unit/test_TileMap.gd:108.
115 * test_cube_neighbor_and_cube_add
116 SCRIPT ERROR: test_cube_neighbor_and_cube_add: Invalid call. Nonexistent function 'cube_neighbor' in base 'Node2D'.
117    At: res://tests/unit/test_TileMap.gd:125.
118 * test_cube_distance
119 SCRIPT ERROR: test_cube_distance: Invalid call. Nonexistent function 'cube_distance' in base 'Node2D'.
120    At: res://tests/unit/test_TileMap.gd:138.
121 * test_cube_round
122 SCRIPT ERROR: test_cube_round: Invalid call. Nonexistent function 'cube_round' in base 'Node2D'.
123    At: res://tests/unit/test_TileMap.gd:143.
124 * test_lerp
125     Pending
126 * test_cube_lerp
127     Pending
128 * test_cube_linedraw
129 SCRIPT ERROR: test_cube_linedraw: Invalid call. Nonexistent function 'cube_linedraw' in base 'Node2D'.
130    At: res://tests/unit/test_TileMap.gd:152.
131 * test_cube_in_range
132     Pending
133 * test_cube_to_offset
134 SCRIPT ERROR: test_cube_to_offset: Invalid call. Nonexistent function 'cube_to_offset' in base 'Node2D'.
135    At: res://tests/unit/test_TileMap.gd:171.
136 * test_cube_to_flat
137 SCRIPT ERROR: test_cube_to_flat: Invalid call. Nonexistent function 'cube_to_flat' in base 'Node2D'.
138    At: res://tests/unit/test_TileMap.gd:176.
139 ERROR: remove_child: Cannot remove child node HexTileMap as it is not a child of this node.
140    At: scene/main/node.cpp:1256.
141 *****************
142 Run Summary
143 *****************
144 res://tests/unit/test_TileMap.gd
145   - test_offset_to_flat_limit
146      Pending:  
147   - test_lerp
148      Pending:  
149   - test_cube_lerp
150      Pending:  
151   - test_cube_in_range
152      Pending:  
153 ***  Totals  ***
154   scripts:          1
155   tests:            18
156   passing asserts:  0
157   failing asserts:  0
158   pending:          4
159 Warnings/Errors:
160   * 1 Errors.
161 +++ 0 passed 0 failed.  Tests finished in:  1 +++
162 ERROR: ~List: Condition ' _first != __null ' is true.
163    At: ./core/self_list.h:112.
164 ERROR: ~List: Condition ' _first != __null ' is true.
165    At: ./core/self_list.h:112.
166 WARNING: cleanup: ObjectDB Instances still exist!
167    At: core/object.cpp:2069.
168 ERROR: clear: Resources Still in use at Exit!
169    At: core/resource.cpp:473.
170 Job succeeded
```
Is there a way I can tell GUT to fail if an error was detected? Because it does detect the error.

**Comment by bitwes** [comment]
I did some looking around and I don't see any way to get a list of errors that have occurred in the engine.  I see that GDScript has a way to `push_error` but there aren't any `get` methods listed.  I'll continue to keep an eye out but I don't think there is a way to do this now.

Just a note, GUT is listing that it saw `* 1 Errors` but that is a GUT error from line 79.  It doesn't know about the other script errors.

**Comment by FeralBytes** [comment]
Ah, IC the error is due to git not keeping the directory around, I need not make a .gitignore file. Thanks for pointing that out. Can you think of a clever way to fail if the test simply does not get run as in the above case? The main reason I really want this is so that when I work with others, if they change a file and break a scene that it could be detected by GUT.

**Comment by bitwes** [comment]
If I'm reading the output you provided right, then all the tests ran but each blew up because of some runtime error.  That resulted in 0 asserts being run.  In this case that is an error,  but in general I don't know what I could do to GUT to detect this and force a bad exit code.  It is not inherently an error. 

The only thing that I can think of is to make your own script to run GUT instead of using `gut_cmdln`.   You could then inspect the results and fail accordingly.

I threw this together real quick,  I didn't test it but it should be enough to get you started.  For as complicated and long as `gut_cmdln.gd` is, this is really all it ends up doing.
``` python
extends SceneTree

var Gut = load('res://addons/gut/gut.gd')
var _tester = Gut.new()

func _init():
    get_root().add_child(_tester)

    _tester.set_yield_between_tests(true)
    _tester.set_include_subdirectories(true)
    _tester.add_directory('res://test', 'test_', '.gd')
    _tester.connect('tests_finished', self, '_on_tests_finished')
    _tester.show()
    # apply any other options you want to the tester.  Check
    # func apply_options(opts): in gut_cmdln for examples

    _tester.test_scripts()

    
func _on_tests_finished():
    var totals = _tester.get_summary().get_totals()
    # verify some summary data.  summary has:
    #   passing = 0,
    #   pending = 0,
    #   failing = 0,
    #   tests = 0,
    #   scripts = 0
    if(summary.passing + summary.failing == 0 or summary.scripts ==  0):
        OS.exit_code = 1

    if(_tester.get_fail_count() > 0):
		OS.exit_code = 1

    quit()
```

The totals does not have the "assert count" which would be very helpful in this case.  Since this run only had one script you can get enough info by seeing that there were 0 passing and 0 failing.  But if a run runs more scripts you won't be able to tell that way (assuming the others have asserts that run).  Adding the assert count to the summary would allow you to verify that `failing + passing == total`.  I'm going to add that in, but in the meantime if you change `get_totals()` in `res://addons/gut/summary.gd` to the following code, it should get you access to the total number of asserts via `get_totals`.

``` python
    func get_totals():
    	var totals = {
    		passing = 0,
    		pending = 0,
    		failing = 0,
    		tests = 0,
    		scripts = 0,
    		asserts = 0
    	}

    	for s in range(_scripts.size()):
    		totals.passing += _scripts[s].get_pass_count()
    		totals.pending += _scripts[s].get_pending_count()
    		totals.failing += _scripts[s].get_fail_count()
    		totals.tests += _scripts[s]._test_order.size()
    		totals.asserts += _scripts[s].get_assert_count()

    	totals.scripts = get_non_inner_class_script_count()

    	return totals
```

Hope that helps.  It's a bit of a manual process.  This might be a sign that `gut_cmdln` is getting too big and should be broken up a bit so that others can create their own runner script but still be able to get to the functionality in gut_cmdln, like loading options.

**Comment by FeralBytes** [comment]
The new get_totals() in summary.gd fails with 
```shell
Invalid call. Nonexistent function 'get_assert_count' in base 'Reference()'. Even though the test scripts do inherit gut/test.gd and I can find the method get_assert_count() in that file.
I am investigating further because that seems weird. Commenting out the last line in the for does result in a working summary script.
```gd
#			totals.asserts += _scripts[s].get_assert_count()
```

**Comment by FeralBytes** [comment]
And with that change it now catches when a scene has an error or if asserts simply fail to be run that are not pending.

**Comment by bitwes** [comment]
These changes were rolled into 6.8.1
