### ISSUE TITLE
Testing tool scripts?

### ISSUE THREAD

**Issue by tchernia** [bitwes/Gut#135]
Hello everybody!

First of all, I would like to say thank you for this great framework that should have needed a lot of endeavor.
I am trying to create a plugin myself to improve the use of TileMaps, and I am running into an issue. Maybe there is already something that allows to do that?

To run tests with gut, we need to play the scene, which by essence makes Engine.is_editor_hint() being false.
Because of that, it is impossible to test functionality that runs only in the editor and not in game, such as level design functions.
It would be great to be able tu use gut when making plugins too!

Thanks and have a nice week end.

**Comment by bitwes** [comment]
This is an interesting problem.  I don't have any ideas off the top of my for GUT but there might be something that can be done.

In the meantime, I'm guessing you are conditionally running or not running code based on the `is_editor_hint`.  You might be able to make a function in a `global` script that would check the hint and another "testing" flag.  That way you don't have to litter your code with complicated `if`s everywhere.  You could set the "testing" flag in the `before_all` in your test scripts.

You may also want to look into modularizing the code in a way that you can get access to the functions without the check being in them.  I haven't made any editor plugins so I'm not sure if that is even possible.

If you could supply some simple examples of how the hint is getting in your way we'll have a better time coming up with a fix or a recommended workaround that could be added to the documentation.

Thanks for using GUT!

**Comment by tchernia** [comment]
This is exactly as you guessed: I am coding a functionality to align tilemap childs to the grid automatically during level design: when the transform is changed (notify(NOTIFICATION_TRANSFORM_CHANGED)) it makes sure the node ends up on a point of the grid (map_to_world(world_to_map(position)). But I only want this to happen in editor and not in my game of course. So I am using Engine.is_editor_hint().

Actually I have found an easy (but not elegant) workaround to use gut for tool scripts:

- I set run on load export variable, which allows to run tests automatically when loading the scene, when we are in editor (though I have to open the scene each time I want to make a new test, which is a bit tedious).
- However this does not detect any test. I had to look in gut.gd script and what allowed it to work was removing all the "if !Engine.is_editor_hint()" conditions I could find. I did not find any side effects but I didn't look very far.
- In my tests, I use "if !Engine.is_editor_hint()" and "if Engine.is_editor_hint()" conditions so that some asserts are tested only in editor and some other only in game. Thus I can check if my code behaves as expected in both contexts. Then I have to both run my tests in editor (by the workaround I explained before) and in game (by playing the scene the normal way) to fully test my plugin :)

The idea of replacing the direct condition by a global variable is interesting too, thanks anyway! I will keep that in mind if I run into that kind of problem again and I don't find a satisfying workaround.

**Comment by bitwes** [comment]
It looks like you can set the flag yourself.  This could get ugly to manage, but with careful use `before_all` and of `after_all` you should be able to manage it.  Using [Inner test classes](https://github.com/bitwes/Gut/wiki/Inner-Test-Classes) might also be helpful in organizing your editor and non-editor tests (if not separate files).

I ran this simple script
```python
extends SceneTree

func _init():
	print(Engine.is_editor_hint())
	Engine.set_editor_hint(true)
	print(Engine.is_editor_hint())
	quit()
```
and it printed
```
false
true
```

I'm thinking something along these lines:
```python
extends 'res://addons/gut/test.gd'

class TestInEditor:
  extends 'res://addons/gut/test.gd'

  func before_all():
    # Set the flag before any of the tests in this class run.
    Engine.set_editor_hint(true)

  func after_all():
    # Unset the flag after all tests in this class run.
    Engine.set_editor_hint(false)

  func test_foo():
    pending('make test')

  func test_bar():
    pending('make test')

class TestNotInEditor:
  extends 'res://addons/gut/test.gd'

  # No need to set/unset for this class

  func test_foo():
    pending('make test')

  func test_bar():
    pending('make test')
  ```

**Comment by tchernia** [comment]
Indeed I did not know we could set the parameters ourselves. This solves everything in quite an elegant way, thank you!!
