### ISSUE TITLE
Add pre and post script hooks.

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#139]
It would be useful to add pre-run and possibly post-run script hooks.  GUT would run the pre-run script before any tests are run and the post-run script after all tests were run.

This can be done pretty easily without the hooks if the command line tool is not used.  You can alter your test scene to do these things.  You could then run the scene from the command line but you don't have access to all the command line options.

The scenario that spawned this idea was that I have a Stats class that has numerous places where saves occur so that stats are saved as soon as is reasonable.  So that I don't have to worry about stubbing the Stats class global in all the places that might cause a save to occur, I could stub it before any tests run.

### Use Cases for pre-run
* Stubbing or setting globals before running any tests so that they don't have to stubbed everywhere.  
* Could be useful in CICD pipelines to cleanup any save files from previous run (see post-run)

### Use Cases for post-run
the post-run script could be useful for CICD pipelines to write results to a file or create output that the pipeline could then use to verify the results of the run.

### Implementation
* Settings:
  * pre-run path setting for editor
  * pre-run path option for command line and .gutconfig.json
  * post-run path setting for editor
  * post-run path option for command line and .gutconfig.json
* Scripts will be required to have a `run()` method that takes no parameters.  I thought about just allowing everything to be in the `init()` method but with the optional `extends` feature it would get too complicated and this is just easier.
  * If the script does not have a `run` method then GUT will error.  If that script is the pre-run script then no tests will be run.
* Scripts can, but aren't required, inherit from a script that will provide access to the GUT instance via a script variable called `gut`.  Additional helper methods to be added as needed.  Both the pre and post scripts will inherit from the same script, maybe `res://addons/gut/gut_hooks.gd`
  * The default implementation of `gut_hooks.gd`'s will print out an error message and possibly stop the run if the script is the pre-run script.
  * Optional addition of `global_double` and `global_stub` methods for globals.  Stubs are cleared between tests so something will have to be done so that globals can retain their stubs.
* GUT will retain the pre-run script instance so that it is available to the post-run script to cut down on some duplicate code.
  * A method called `get_pre_run_script_instance` must be added to GUT.

**Comment by Xrayez** [comment]
Yeah I think this should be mostly useful for command line stuff alone.

Apart from #128, I could do the following with this:

1. Read `.git` commit message to find anything containing `[ci skip]` via GDScript.
2. Interpret that directly and just quit the GUT with zero exit status.

This would be mainly useful for local experimental branches development where you don't really have to run tests for the new functionality. Of course I could do this via git hooks specifically, running tests only for the `master` branch, but a combination of git+GUT hooks would make it really flexible.

**Comment by bitwes** [comment]
Implemented in 6.8.1
