### ISSUE TITLE
Can't activate gut when treating warnings as errors

### ISSUE THREAD

**Issue by ChrisPWill** [bitwes/Gut#143]
Due to some warnings in the code, gut cannot be activated in the Plugins list if `warnings/treat_warnings_as_errors` is set to `true`. I suspect this could mostly be fixed by providing some type annotations, and will be happy to have a go at this once I have a little more free time.

I know it sounds a little pedantic to enable this setting, but as I'm working on a project with non-coders contributing code I'd rather enforce stricter standards to prevent a whole bunch of dead code and other more nasty things sneaking into the code-base.

**Comment by bitwes** [comment]
Take a look at #129.  I think there is a way to disable the warnings for plugins now in 3.2.  I haven't tested this or documented it yet, so let me know how it goes and I'll update the wiki.

**Comment by ChrisPWill** [comment]
Can confirm that 3.2 fixed the issue. Quite funny timing on my part to be filing the issue! :)
