### ISSUE TITLE
My very little problem

### ISSUE THREAD

**Issue by an7i8** [bitwes/Gut#144]
Hello. Thanks for your utility. I am new at game developing and testing too. Now I have a little problem with my test. I want to write test which will check movement of the object.
```
func test_move_forward_moves_by_speed_times_delta():
	var spaceship = Spaceship.new()
	spaceship.set_translation(Vector3(1, 0, 0))
	var orig_pos = spaceship.get_translation()
	spaceship.main_eng(20)
	spaceship.move_forward(.5)
	assert_eq(spaceship.get_translation().x, orig_pos.x + 10, 'move forward')
```
Realization, like this i saw in TDD and PONG video. And when i write the movement function like this:
```
func main_eng(main_eng):
	_main_eng = main_eng

func move_forward(delta):
	set_translation(get_translation() + Vector3 (delta * _main_eng, 0, 0))
```

Everything work fine. But i want to make realization of the movement, like here:
```
func main_eng(main_eng):
	_main_eng = main_eng

func move_forward(delta):
	add_central_force(transform.basis.x * _main_eng * delta)

```
In this case my test doesn't work. I think this is my mistake, but i don't know where and how i can fix it. Can you help me?

**Comment by Ajver** [comment]
Hi!

I think the problem isn't in the test or the code, but Godot's behavior. `add_central_force` function doesn't move the body but sets force, that will move the body in the physics frame.

So to pass the test, you have to "wait" a frame, to allow Godot to move the body. You can probably use `simulate` to do so: https://github.com/bitwes/Gut/wiki/Simulate.

Also, I am not sure if using `add_central_force` with `delta` is a good idea, as the velocity is calculated by Godot itself, based on the force(s) AND delta. But I may be wrong, didn't test your code...

**Comment by bitwes** [comment]
I'm not sure if `simulate` will work, it's worth a try.  If not then you'll have to `yield` in your test to give the engine a few cycles to move the body.  There's a wiki page that covers yiedling.

Since this is part of the engine, it might not really need to be tested.   If you can get information from your object about what forces have been applied then that might be a better test.  That way you can confirm you are applying the force you expected but not that things actually move (since we don't want to "test the framework" as they say).

**Comment by an7i8** [comment]
Thanks Ajver for knowledge about delta. But simulate didn't help.
bitwes, big thanks. Yielding help me to make a test. I dont quite understand. How  can I get information from my object about what forces have been applied.

**Comment by bitwes** [comment]
Im not sure.  I was thinking something in the engine would give u that info.
