### ISSUE TITLE
3.2 gui doesnt appear out of the box problem

### ISSUE THREAD

**Issue by astrale-sharp** [bitwes/Gut#145]
Hey there,

the problem is this: on Godot3.2, you cant add a gut object to a scene because it does not appear in  the "Create New Node" list
if you try to make a Control Node inherits the gut.gd script, you end up with lots of gui problem (it doesnt fit the screen, even inside a container

to reproduce the bug, add the gut.gd script to a control node and launch the scene

**Comment by bitwes** [comment]
To add GUT to a scene you should see it in the list of available nodes like below.  If you do not see this then GUT might not be enabled.

![image](https://user-images.githubusercontent.com/1156520/74593206-d9a15700-4ff6-11ea-826c-28fec7fe41ae.png)

![image](https://user-images.githubusercontent.com/1156520/74593224-035a7e00-4ff7-11ea-9cf2-634804fd4508.png)

If you have it enabled then there might be something weird going on.  I created these two screenshots by starting a new project, installing GUT from the Asset Library and enabling it.  If enabling it does not fix the problem then please provide some more details about your setup.

**Comment by bitwes** [comment]
Reopen this if this didn't fix the issue for you.
