### ISSUE TITLE
Errors when running gut from the command line

### ISSUE THREAD

**Issue by Philbywhizz** [bitwes/Gut#150]
I'm following along the TDDPong video to learn how to do TDD with gut and I am using the command line instead of creating a test scene with a gut node.

When I run _godot --debug-collisions --path $PWD -d -s addons/gut/gut_cmdln.gd_ I get the following when Godot shutdown.

```
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2071.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:476.
```

I have a feeling that they are Godot errors rather than GUT as I don't see these errors on the output when I create a test scene with gut node as per the video.

I have tried against 6.8.1 (master) as well as your current 6_8_2 branch and I have the same result.

**Comment by bitwes** [comment]
These can be ignored.  Issue #122 covers some of these.  Some are artifacts of GUT not/not-able-to free up objects before the program quits which isn't really a problem since most are in use right up to the point it quits.  Some are vague and I haven't tracked down what is causing them, but they've been there since day one and have not caused any issues.  They are really ugly though, and I hate them.

**Comment by Philbywhizz** [comment]
Thanks for the explanation. I'll just have to put up with the ugliness for now. Yes I don't believe it causes any issues as they occur after the gut windows shutdown (after all the tests have run). I might have a poke through the GUT code and see if I can spot anything.

**Comment by olivierdalang** [comment]
I'm also getting this.

Could we reopen the issue until it's fixed (even if no fix is planned short-term) ? This would make it easier to find the issue and allow us to subscribe to it so we can know when this is fixed.

Thanks for Gut which seems really nice otherwise !!
