### ISSUE TITLE
Bad Download Hash

### ISSUE THREAD

**Issue by bbstilson** [bitwes/Gut#153]
I receive the following error when trying to download Gut from the AssetLib.

I'm on Godot 3.2.1 on Mac OS Catalina.

![image](https://user-images.githubusercontent.com/7949037/79076338-385d1700-7cae-11ea-8a73-450121e3f321.png)

**Comment by bbstilson** [comment]
Found the instructions to download from github.

**Comment by bitwes** [comment]
I just got the same thing.  I don't. know what is causing this.  All the settings look fine in the Asset Library.

**Comment by CodeDarigan** [comment]
I think there was an issue with godot a while ago that screwed all assets up but maybe you somehow amended a release that was already in the lib?

**Comment by bitwes** [comment]
Was able to install it without error.  I guess they fixed it.
