### ISSUE TITLE
/Methods wiki subpage is inaccessible

### ISSUE THREAD

**Issue by dydokamil** [bitwes/Gut#154]
https://github.com/bitwes/Gut/wiki/Methods cannot be accessed

I am redirected to the main wiki page

should the link be changed to /Asserts-and-Methods?

**Comment by bitwes** [comment]
Shoot.  I renamed it to asserts and methods.  Forgot to update links.  I'll
fix that today.

**Comment by bitwes** [comment]
Links fixed.  The new page is https://github.com/bitwes/Gut/wiki/Asserts-and-Methods
