### ISSUE TITLE
upgrade usability of gut.p()

### ISSUE THREAD

**Issue by astrale-sharp** [bitwes/Gut#156]
I'd like to make gut.p() fake variadic (take up to ten args)
so as to be able to use it like print(1,2,3,...)

so, leave it to me, I'll implement it! ;)

**Comment by astrale-sharp** [comment]
okay i have a problem :
the problem being, gut.p currently prints null statements correctly
my implementation breaks that if an user calls

gut.p(1,2,null,3,null)
you can know there is a null statement between 2 and 3 and print it correctly
but you cant know if the last null is the defaut value of your function or provided by the user

If you cant help on this, lets abort, users can alway pass array even though its ugly ;) (plus array are displayed nicely now ;) )

my code so far :
```
func p(text0 = null, text1 = null, text2 = null, text3 = null, text4 = null, text5 = null, text6 = null, text7 = null, text8 = null, text9 = null, \
		 level=0, indent=0):

	var texts = [text0, text1, text2, text3, text4, text5, text6, text7, text8, text9,level,indent ]
	var total_size = texts.size()
	while texts.has(null):
		texts.erase(null)
	
	#two last texts interpreted as level, indent
	if not texts.size() == total_size:
		indent = texts.pop_back()
		level = texts.pop_back()
	
	var str_text = ""
	
	for text in texts:
		var each_str_text = var2str(text) if typeof(text) in \
		[
				TYPE_ARRAY,
				TYPE_DICTIONARY,
				TYPE_COLOR_ARRAY,
				TYPE_INT_ARRAY,
				TYPE_VECTOR2_ARRAY,
				TYPE_VECTOR3_ARRAY,
				TYPE_RAW_ARRAY,
				TYPE_REAL_ARRAY,
		] \
			else str(text)
		str_text += each_str_text
		str_text += "\n"


```

**Comment by bitwes** [comment]
Closing this based on other discussions in a PR that has been closed and your last comment.  I think `gut.p` could be improved though.  In most cases the user would never need the indent level.  This is used internally and the method was just exposed "as is".  There might be something else that could be done.

The easiest workaround for this would be to just pass an array of things to print as the first parameter.
