### ISSUE TITLE
Godot tries to parse template file, causing get_token_identifier error

### ISSUE THREAD

**Issue by hsandt** [bitwes/Gut#157]
When running Godot in the console only (it's apparently automatic when clicking on Desktop icon on Windows), you are able to see script parsing errors.

If gut is installed, you will see:

> $ ERROR: get_token_identifier: Condition "tk_rb[ofs].type != TK_IDENTIFIER" is true. Returned: StringName()
   At: modules/gdscript/gdscript_tokenizer.cpp:1129.
ERROR: get_token_identifier: Condition "tk_rb[ofs].type != TK_IDENTIFIER" is true. Returned: StringName()
   At: modules/gdscript/gdscript_tokenizer.cpp:1129.
ERROR: get_token_identifier: Condition "tk_rb[ofs].type != TK_IDENTIFIER" is true. Returned: StringName()
   At: modules/gdscript/gdscript_tokenizer.cpp:1129.
ERROR: get_token_identifier: Condition "tk_rb[ofs].type != TK_IDENTIFIER" is true. Returned: StringName()
   At: modules/gdscript/gdscript_tokenizer.cpp:1129.

And for some reason, on Windows only I get a few extra lines of information like:

> SCRIPT ERROR: GDScript::reload: Parse Error: Unexpected token: '{':                                                               At: res://addons/gut/double_templates/function_template.gd:1

The last one allowed to find the cause, double_templates/function_template.gd being parsed. But it's just a template that contains `{variable}`, not a valid script.

I have yet to find a fix, but maybe changing the extension of templates to .txt would prevent script parsing.

**Comment by hsandt** [comment]
Renaming templates to .txt (and updating the paths in script that are used to load the templates) seems to fix the issue.

The files will disappear from Godot FileSystem view though, so you'll need to edit them with a external code editor.

**Comment by bitwes** [comment]
I remember all this now.  I left them as `.gd` files because I get nice syntax highlighting when editing them and also b/c of exporting and running tests on a device...which I think is now broken b/c of this.  I'll try to find a more elegant solution in the next release.

**Comment by bitwes** [comment]
Neat!  The current fix works ok and I don't see having to edit the templates much in the future.  If it gets annoying then I'll try the `.gdignore` and test the exporting.  Great to know about the `.gdignore`.

**Comment by bitwes** [comment]
Fixed in 6.8.3
