### ISSUE TITLE
Differences in compared arrays or dictionaries can be difficult to spot

### ISSUE THREAD

**Issue by hilfazer** [bitwes/Gut#176]
![gut_failed_array_dict_comparison](https://user-images.githubusercontent.com/29497869/83948808-45b2ff80-a820-11ea-81e8-57f410851e0f.png)

Elements that differ could use different colour.

I used assert_eq.

**Comment by bitwes** [comment]
The upcoming version 7.0.0 introduces some logging changes that would make this possible.  Changing the compare to loop through the elements would also help with #152.  This becomes a really gross problem with more complicated data structures though.  It is feasible, for sure, but could be gross.  Maybe a shallow implementation would be acceptable as a first pass at this.

**Comment by bitwes** [comment]
This should be addressed now in 7.1.0.  The differences are now called out specifically for arrays.  Dictionaries have to use the `assert_eq_deep` or `assert_eq_shallow`.  See https://github.com/bitwes/Gut/wiki/Comparing-Things.
