### ISSUE TITLE
Discussion:  Strategy for automatically freeing objects?

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#178]
I've been working on some changes for tracking down leaks.  In doing so I've discovered that the tests I've made for my own game have been creating a lot of leaks.  This doesn't _really_ matter since they are just tests but with the new changes you can't tell if the test is leaking and/or the game is leaking until they are addressed.

The next release already has some minor breaking changes, so I'm ok with breaking things if it will be better in the long run.  Here are some implementations I've been experimenting with.

# The Stuff That Is Working
## Orphan counts
In the upcoming version 7.0.0 GUT prints out the number of orphans each test/script/run generates.  It keeps track of the number of orphans and prints out the difference after each test and script and a total at the end.  This feature is working great, but after enabling it I realized my tests were making a lot of orphans.  The next problem to solve is the best way to allow users to free up their objects so that actual memory leaks are easier to track down.

## `autofree`
The `autofree(thing)` method marks whatever is passed to be freed at the end of the test.  It also returns whatever you pass it so you can cut down on lines of code.  You can pass it whatever and it will free it at the end of the test if it can.  It is designed so that using it incorrectly won't cause any issues.
```
var foo = autofree(load('res://foo.gd').new())
var bar = autofree(Bar.new())
```
I've tried this out in my tests and it works great.  I've also added `autoqfree` which calls `queue_free` on the object though I haven't found a need for it yet.

# The Stuff That Needs Work
## Doubles and Partial Doubles (this still needs some thought)
I've added code to Doubles and Partial Doubles that will automatically free them when the test ends.  This cleaned up a lot of my orphans in my game's tests with no changes to the code.  I'm not sure if this could cause an issue.  I don't think you should be making doubles in `before_all` since all stubs and spies are cleared between tests.  But you can.  I'm also not sure if this is too much "magic".  

## Children
Right now, if you call `add_child` in a test then the child is added to the test itself.  The tests are not freed until the end of the run.  If the test code doesn't free these objects then they can suck up memory.  Also, when they are freed at the end, any orphans they create lose the context of where they were created.

#### Solution 1:  Alter `add_child` (decided this isn't ideal)
I was able to overload `add_child` so that it calls `autofree` on anything passed to it.  This frees up the nodes at the end.  This could cause a problem though if a child is added in `before_all`.  It seems like this should be allowed, so a method like `add_persistent_child` could be added that would not `autofree` the child.  Another idea is that GUT could probably detect the context of the call to `add_child` and not `autofree` if not in a test.

The BIG benefit of this approach is that you get all the cleanup with no changes to tests.  

The down side is working the `before_all` problem and that `add_child` now works different in tests than it does anywhere else in your code (though you may have assumed this is how it worked anyway).  It could be another case of too much "magic".

#### Solution 2:  Warn and Add Helpers (going forward this way)
When a test or script finishes GUT could print out a warning if there are any children that still exist on the test object.  This would also give brief instructions on how to address the issue.  I think the warning would come at the end of the script to cut down on log pollution.

A method for adding children and also freeing them would be added.  Let's call it `add_child_autofree`.  This would add the child, mark the object to be freed, and return whatever was passed in so that you can cut down on lines of code.
```
var foo = add_child_autofree(Foo.new())
```

This implementation works fine, but does require changes to tests to free the objects.

# Feedback
Please post any ideas you have in regards to implementation, names, approaches, concerns or anything else.

Thanks

**Comment by hilfazer** [comment]
> I was able to overload add_child so that it calls autofree on anything passed to it. This frees up the nodes at the end. This could cause a problem though if a child is added in before_all.

I don't think those nodes are a problem by themselves. If i add children to my test before any tests are run i want to have them for all tests. But nodes added as children of those nodes in a `test_` function won't be freed either:

```
func test_stuff():
	childAddedBeforeAll.add_child( Node.new() )
```

Another approach is to traverse test's children recursively and register them before any tests are run. Then after each test current children would be compared to that list and nodes that aren't on it would be deleted.
This approach avoid aforementioned problem.

Yet another option is to leave the business of freeing children to users (: 
We could do that by overloading `before_*` and `after_*` as we already do. The code for this can be written once and used in all tests so it's not too big of a deal.

**Comment by bitwes** [comment]
Going forward with Solution 2 for the children.

If anyone has any thoughts on the Doubles and Partial Doubles issue I'd like to hear them.  It's been implemented but I'm not sure if I should take it out.

**Comment by bitwes** [comment]
`autofree`, `autoqfree`, `add_child_autofree`, and `add_child_autoqfree` were added in 7.0.0 to address this.
