### ISSUE TITLE
[WIKI] Add minor doc improvements to Creating-Tests.md

### ISSUE THREAD

**Issue by justin-calleja** [bitwes/Gut#179]
Sorry, no idea how to make a PR for your wiki. Here's a link to the commit with the suggested changes:

https://github.com/justin-calleja/Gut-wiki/commit/7a377d306080787f0c404079cf023f370d1959c0

Thanks - nice project!

**Comment by bitwes** [comment]
It doesn't look like there is a way to make wiki PRs.  This is probably the easiest way to do it.  I'll copy over your changes and close this issue once pushed up.  Thanks for the changes.

**Comment by bitwes** [comment]
Changes pushed up.  Thanks again.

**Comment by justin-calleja** [comment]
@bitwes thanks!
