### ISSUE TITLE
How can I inject a child into a Script before it hits _ready():

### ISSUE THREAD

**Issue by smksnutmeg** [bitwes/Gut#180]
```
func before_each():
	obj = Obj.new()
	var child_node = State.new()
	obj.add_child(child_node)
	obj.current_state = child_node
```

Want to inject the child before it calls _ready - this is because ready injects the child into a dictionary.

```
func _ready():
	var first_child = get_child(0)
	states_stack.push_front(first_child)
	current_state = first_child
	if active:
		start()
```

**Comment by bitwes** [comment]
From the code it is hard to tell if `obj` has other children already.  If it does and you want to replace the child at index 0 then this method might help.  https://github.com/bitwes/Gut/wiki/Asserts-and-Methods#replace_node

This will replace a given node in an object based off name.  You would have to know the name of child 0 for this to be useful.

If `obj` doesn't have any other children already then it looks like your code would work as it is.  Though I don't see you calling `add_child` on `obj` which would cause `_ready` to be called.  I'm assuming the `_ready` is for `obj` and not `State`.

I also think there is a way to reorder children or insert a child at a specific index though I don't remember ever doing that before.  It has to be possible though.

**Comment by bitwes** [comment]
I'm closing this out since it's gone stale.  If that didn't answer the question or you have more questions just reopen the bug and post them here.
