### ISSUE TITLE
assert_no_new_orphans() crashes if no test were run before

### ISSUE THREAD

**Issue by hilfazer** [bitwes/Gut#185]
```
extends "res://addons/gut/test.gd"

func before_all():
	assert_no_new_orphans()

func test_1():
	pass


func after_all():
	assert_no_new_orphans()

```

There will be a crash in 'before_all()'. The crash would also be in 'after_all()' if 'test_1()' didn't exist. I tried some other assertions and the didn't have that problem.

![GutAssertNoNewOrphanCrash](https://user-images.githubusercontent.com/29497869/85198674-d4c51a80-b2ea-11ea-9389-08f5f648ee75.png)

**Comment by bitwes** [comment]
Merge fixed this.  Additionally I added a test and changed `get_counter` to return -1 instead of 0 so that it will be more obvious if the `orphan_counter.gd` is misused.
