### ISSUE TITLE
get_instance() fails when running from editor (3.2.2, 3.2.1)

### ISSUE THREAD

**Issue by jamie-pate** [bitwes/Gut#194]
I'm unable to run my test scene from the editor, because during `_init()` in `addons/gut/gut.gd` the root node doesn't exist, and it causes `Nonexistent function 'has_node' in base Nil` during `if(the_root.has_node(INSTANCE_NAME())):`

running dc10b00eaafff0ad6e7f2aa7d5fd4dd9ba194531 7.0.0-1 (works in 6.7.0)

also fails with
https://github.com/bitwes/GutTutorials/tree/master/TddAndPong/Episode4 
by following the method used in the video

```
Open test/Tests.tscn
click 'Play Scene' button
```

**Comment by bitwes** [comment]
When you updated to 7.0.0 did you delete the Gut node from the scene and
re-add it?

**Comment by jamie-pate** [comment]
No, I did not, will try that next week...

**Comment by bitwes** [comment]
Are you still having issues with this?  If not please close it out.
