### ISSUE TITLE
Parameterized tests generate deprecated calls

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#195]
It looks like I missed a call to `gut.p` that uses 3 parameters.  I noticed this with a parameterized test so I think it's in there somewhere.

**Comment by short-story-long** [comment]
Hi,
also ran into this one. in script test.gd, use_parameters function has a call of gut.p() method with three arguments. I'm not exactly sure what the correct call is supposed to be though, sorry.

test.gd, line 1182: `gut.p(output, 0, 0)`

**Comment by bitwes** [comment]
implemented in master, will be  in next release
