### ISSUE TITLE
Detect when an instance is passed to double and partial_double

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#199]
I _think_ it is possible to detect when an instance of something is passed to `double` or `partial_double`.  If so, then it should add a GUT error and return `null`.  The current error that happens is hard to decipher.

**Comment by short-story-long** [comment]
You can experiment with the `get_class` / `is_class(string)` functions. You then can check if the given instance is a `Resource`. Or you can force the input parameter of `double` / `partial_double` to be a `Resource` by using typed gdscript. In that case the input parameter will be `null` if the developer throws in an instance of the class under test instead the class itself. (This is what I will be doing for #70)
