### ISSUE TITLE
Disable strict typing with int and float?

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#2]
My heart was in the right place, but the more I use the strict typing with integers and floats the more I'm annoyed.  The engine supports comparing them.  I thought it would be useful to make sure that datatypes are what they are supposed to be but I'm not sure at all now.  Seems like it just gets in the way.

I think the others should stay since they can cause runtime errors.  I think it's better to fail than to blow chow.

Would like to hear opinions.

**Comment by caryoscelus** [comment]
The only situation (that i can think of) where int/float difference matter is division. GDScript uses py2-like behaviour, which might lead to mistakes if not careful and strict type checking can help here.

However, i haven't been using Gut enough to tell which behaviour has more advantages. Maybe make it optional?

**Comment by bitwes** [comment]
After much use...I say yes...remove it.  Could make it a warning, but it should not fail.

**Comment by bitwes** [comment]
Fixed in 3_1 branch.
