### ISSUE TITLE
Add pass/fail/is_passing/has_failed methods

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#201]
Add the following methods for tests:
* pass_test(msg='').  Marks test as passing.  Does not overwrite anything that has already marked the test as failing.  Name could change but must be called something other than "pass" since that is already a reserved word.  
* fail_test(msg='').  Marks test as failing.  Follow whatever naming convention used for "pass_test" if that changes.
* is_passing():  Returns true if the test is passing as of the time of the check, false if not.
* did_fail():  Returns true if the test is failing as of the time of the check, false if not.

**Comment by Xrayez** [comment]
> * fail_test(msg='').  Marks test as failing.  Follow whatever naming convention used for "pass_test" if that changes.

Yes, I've been using the internal `_fail()` in some cases for that matter.

**Comment by bitwes** [comment]
Question:  Should it a warning or error be generated if a test does not make any assertions and isn't pending?

In implementing this I have decided to add a warning if a test does not make  any assertions (which includes calls to `pass_test` and  `fail_test`).  Honestly thought it was already there, but it appears there  is only a message if no tests were run.

This came as a side effect of not  wanting `is_passing` to return `true` if no assertions had been made yet.  With the addition  of `pass_test` and `fail_test` it seems like a good idea to at least warn, but should it be an error?  

Having a warning (or probably an error) could also help with #210 as long as you are careful to only assert at the end (prior to anything that could cause a Script Error).  In `after_all` you could check for any "no assert"  warnings/errors.

**Comment by Xrayez** [comment]
One use case I see is that, someone setups a GUT framework in their projects without tests, commits it, and then other people write tests after that. If we issue an error with no tests, then it would fail CI results as failing too. So I guess a warning should be enough.
