### ISSUE TITLE
freeing test object after all tests run 

### ISSUE THREAD

**Issue by short-story-long** [bitwes/Gut#204]
after all tests of a given test script were run the test object itself is not freed leaving behind an orphan node. 

my workaround for this is to implement the after_all() method in each test script and send the test object to free itself. but maybe this (or something similar) can be integrated into the test.gd script?

i think, this would help keeping track of any orphans that are actually created by the code under test.

**Comment by bitwes** [comment]
If you are talking about the instance of `test.gd`, it has to stick around until the end.  The test suite for GUT itself requires they aren't freed until the end of the run.  They are all freed at the end of the run (in 7.0.0) and do not interfere with the orphan nodes being reported by GUT.  They do show up in the count from `Performance.get_monitor(Performance.OBJECT_ORPHAN_NODE_COUNT)`, and muddy the waters a bit if you are using `print_orphaned_nodes`.

https://github.com/bitwes/Gut/pull/175#issuecomment-638423732

**Comment by short-story-long** [comment]
Ok, cool. Good to know. In that case, I should change my strategy on that one.

Another question: can the test instances be added to the scene tree then? In that case they should not be listed in the performance monitor or `via print_orphan_nodes`, right? Maybe we can make a container node for each test run and the tests can add themselves as children. Then the developers could look into the test instances as well if they need to.

**Comment by bitwes** [comment]
A temp node might work.  One of the main reasons for removing them from the tree was to make sure that no children left behind by the tests were still visible.  When adding to the temp node, it should set the visibility of the script.  That should hide all of its children.  Maybe putting that temp node way offscreen would be a good idea.  I'm not sure.

**Comment by short-story-long** [comment]
I see. Thanks again for taking time to answer my questions. I'll probably experiment a little bit on that one and if I come up with something I'll get back to you.

As you mentioned previously, my initial request to free the test instances itself is not an option. Therefore I'll close this issue. Hope that's fine with you.
