### ISSUE TITLE
How to use Gut to test standalone addon?

### ISSUE THREAD

**Issue by karthanistyr** [bitwes/Gut#209]
How would you propose to use Gut to test a standalone addon, one that would potentially be published on the AssetLib? I'm trying to build something in the spirit of https://github.com/heroiclabs/nakama-godot/, but with Gut as the test engine instead of a home cooked one.

Here's my repository layout:
```
karthanis@karth-dev-book ~/Documents/godot/my_addon (git)-[master] % tree
.
├── addons
│   └── my_addon
│       └── addon.gd
├── project.godot
└── test
    ├── integration
    ├── run_tests.sh
    └── unit
        └── test_example.gd

5 directories, 4 files
```
Note that Gut is currently *absent* from the `addons` directory, but would need to be there at the time I run my tests.

Currently I see some options, but none very good:
* I statically copy Gut in the `addons` directory; not ideal as it'd mean I am redistributing Gut alongside my own addon, it works but I think it violates the AssetLib's guidelines.
* I add Gut as a submodule; not good as I'd be pulling Gut's own tests and it'd conflict with my own directory layout (and my own tests)
* I create a script that fetches a Gut release and unpacks it where it is needed when I run the tests; this is the only really working solution but a bit cumbersome.

Do you have any other suggestions?

**Comment by bitwes** [comment]
For my own games I add `addons` to my `.gitignore` and. install plugins whenever I check everything out (which doesn't happen often on a team of one).  It seems like bad practice to checkin code from other repositories.  I don't think Godot has any dependency management yet, so the last option would probably work best if you want something easily reproducible.

If you really really want to have a version of GUT in your repository then `.gitattributes` would be the way.

**Comment by karthanistyr** [comment]
>  install plugins whenever I check everything out

My concerns with this approach is that it requires a number of manual steps, and relies on the continuous availability of the correct versions of the dependencies over a long period of time.

> It seems like bad practice to checkin code from other repositories.

I agree, I wouldn't do this at first if I could address the concerns expressed above in a clean, "dependency management"-like way. But I have come to think this isn't *so* bad after all. Having Gut in the repo as a kind of *vendored library* satisfies both the "no manual steps" and the future-proofing of the setup, and any AssetLib publication of my addon should be fine if Gut and all other satellite files are properly excluded from archives with `.gitattributes` as you suggest.

>  I don't think Godot has any dependency management yet, so the last option would probably work best if you want something easily reproducible.

I think I agree, and I'm considering backing up the targeted Gut release on a personal artifact repository to that effect. A considerable drawback though is that I would have to support multiple platforms (and provide multiple scripts) for this crude inhouse dependency management, but that can be addressed at a later time... :thinking: 

In any case, thank you for your input and for Gut. :100:

**Comment by bitwes** [comment]
FYI, GUT only has to be enabled as a plugin in Godot to add it to a scene.  If you have your scene already or just use the command line then that is one less step to worry about in automating the install.  The command line tutorial video I made never bothers enabling and it runs just fine.

https://www.youtube.com/watch?v=DZ7NVJOpemg
