### ISSUE TITLE
Run all tests from GUI

### ISSUE THREAD

**Issue by TeddyDD** [bitwes/Gut#21]
I updated GUT from 3 to 4 in one of my projects. I see there is no option in gui to run all tests from given directory. This would be quite useful.

**Comment by bitwes** [comment]
I guess I could add another setting that allowed you to run one of the 6 directories you have configured.  As a workaround you could remove the other directories you have configured but that would get annoying over time.  You can also use code to setup your directories and comment them out, which is also annoying.  This would be a nice enhancement.

**Comment by TeddyDD** [comment]
The thing is I configured only one directory and I have to run tests one by one (or I am doing something wrong)

**Comment by bitwes** [comment]
Are you using the "run" button or the "<-- run" button?  There are two now.  One that runs the currently selected test and one that runs the currently selected one and all tests after it.

**Comment by TeddyDD** [comment]
Damn, you are right. I'v been using <-- run. Thanks.
