### ISSUE TITLE
Script error in strutils.gd: Error calling built-in function 'inst2dict': Not a script with an instance

### ISSUE THREAD

**Issue by founderio** [bitwes/Gut#211]
When running a test like this:
```
func test_focus_entered_emits_signal():
	var component_template = load("res://inventory/text_item.tscn")
	var cut = component_template.instance()

	add_child_autofree(cut)

	watch_signals(cut)

	cut.onFocusEntered()

	assert_signal_emitted_with_parameters(cut, "selected", [0, 0])
```

I receive this script error:
```
SCRIPT ERROR: _get_obj_filename: Error calling built-in function 'inst2dict': Not a script with an instance
   At: res://addons/gut/strutils.gd:76.
```

The error seems to be related to signal processing, other asserts work fine.

Stack trace (sorry, no idea how to copy that stack trace in text form... Can't seem to find it anywhere):
![image](https://user-images.githubusercontent.com/6136865/91665010-08929c80-eaf3-11ea-9862-cbf68b50be5f.png)

The issue may be closely related to the fact that `cut` has a GDNative script, so str2dict may not work correctly.  
I was able to silence the error by applying this hack to `strutils.gd`, I am not sure if this behaves correctly though. This hack is highly specific to my use cases, I have not checked whether it works with GDScripts (Our project does not use GDScripts except for integration tests which require a running engine).

```diff
--- a/addons/gut/strutils.gd
+++ b/addons/gut/strutils.gd
@@ -73,10 +73,13 @@ func _get_obj_filename(thing):
 			# we do nothing.  This just read better.
 			pass
 	elif(!_utils.is_native_class(thing)):
-		var dict = inst2dict(thing)
-		filename = _get_filename(dict['@path'])
-		if(dict['@subpath'] != ''):
-			filename += str('/', dict['@subpath'])
+		# FIXME: This is a temporary hack to allow this to work with GDNative scripts
+		# inst2dict fails with "Not a script with an instance"
+		filename = thing.get_script().resource_path
+		# var dict = inst2dict(thing)
+		# filename = _get_filename(dict['@path'])
+		# if(dict['@subpath'] != ''):
+		# 	filename += str('/', dict['@subpath'])
 
 	return filename
 
-- 
```

With the hack applied, failed assertions show the path of the `.gdns` which is as close as godot can get to display the source path of a GDNative script I think. Example:
```
[...]

res://test/integration/inventory/test_text_item.gd
Loading resource: res://test/integration/inventory/test_text_item.gd
* test_mouse_click_emits_signal
    [DEPRECATED]:  gut.p no longer supports the optional 3rd parameter for indent_level parameter.
    (call #1) with paramters:  True
    [DEPRECATED]:  gut.p no longer supports the optional 3rd parameter for indent_level parameter.
    (call #2) with paramters:  False
* test_set_text_updates_label
* test_input_event_emits_signal
* test_focus_entered_emits_signal
    [Failed]:  Expected object [PanelContainer:2138](res://bin/text_item.gdns) to emit signal [selected] with parameters [1, 0], got [0, 0]
      at line -1
4/5 passed.


*** Run Summary ***
res://test/integration/inventory/test_text_item.gd
- test_focus_entered_emits_signal
    [Failed]:  Expected object [PanelContainer:2138](res://bin/text_item.gdns) to emit signal [selected] with parameters [1, 0], got [0, 0]
          at line -1

[...]
```

**Comment by bitwes** [comment]
Can you check to see if adding a `is GDNative` somewhere in there would help?  I haven't done any GDNative programming.  I  tried out the quick tutorial  I found at https://godotengine.org/article/dlscript-here but I don't have `scons` installed and ran out of willpower.

**Comment by founderio** [comment]
Your idea was in the right direction.
All GDNative scripts are an instance of `NativeScript`.

I've created a pull request with the updated, proper fix.

Relevant documentation: https://docs.godotengine.org/en/3.2/classes/class_script.html#class-script

This documentation made me think: Is the inst2dict required for anything or could we make use of the same resource_path property also exposed by GDScripts? Not sure.

Another point: C# scripts may have a similar issue. @MJacred I know you have a C# project somewhere, would be good if you could test this with a C# object. We might have to implement a similar edgecase for `is CSharpScript`.

**Comment by bitwes** [comment]
"Is the inst2dict required for anything...", yes, it also gets the sub-path which is the inner class name if it is an inner class.  `resource_path` appears to come from the base `Resource` class.  I don't see anything in there that has the inner class name.

**Comment by founderio** [comment]
> it also gets the sub-path which is the inner class name if it is an inner class

got it, thanks for clarifying :)
