### ISSUE TITLE
Wiki snippet for Partial Doubles using 'double' and not 'partial_double'

### ISSUE THREAD

**Issue by nilold** [bitwes/Gut#212]
Hello!
The [Wiki snippet](https://github.com/bitwes/Gut/wiki/Quick-Start#partial-doubles) for Partial Doubles is using 'double' and not 'partial_double'.

I would PR it but I don't know how to make it with wiki pages and its also a very small change.

I know its a small issue, but newbies like me could spend some minutes before figuring it out =);

**Comment by bitwes** [comment]
Last I checked you couldn't make wiki PRs.  Fixed the snippet added some comments and fixed the "more information" link for Partial-Dobules.  Thanks, good find.
