### ISSUE TITLE
Use class_name for test.gd

### ISSUE THREAD

**Issue by Shatur** [bitwes/Gut#215]
I suggest to add [class_name](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#classes) to the plugin's `test.gd`.
This will allow to write `extends Test` instead of `extends "res://addons/gut/test.gd"` in user-defined tests.

**Comment by bitwes** [comment]
I've thought about adding this.  I think the name would have to be less generic, like `GutTest`.  I'm not sure if this should wait for a major release in case the name clashes with a user's class.

**Comment by Shatur95** [comment]
Yes, `GutTest` is better name. In [WAT](https://github.com/CodeDarigan/WAT) it called `WAT.Test`.

**Comment by Shatur95** [comment]
>  I'm not sure if this should wait for a major release in case the name clashes with a user's class.

I guess `GutTest` shouldn't cause name clashes.

**Comment by hilfazer** [comment]
It can be worked around by inheriting all your tests from a class that inherits "res://addons/gut/test.gd" and has a class_name.

That class can also be doing things you want to have in each of your tests. If someone is interested, there's mine:
https://github.com/hilfazer/Projects/blob/master/Godot/GUT_structure/tests/GutTestBase.gd
Keep in mind i'm a beginner at GUT so some of those things may be unnecessary :)

**Comment by bitwes** [comment]
`GutTest` can now be used instead of `'res://addons/gut/test.g'` in master.  This will be in release 3.0.

**Comment by bitwes** [comment]
Released in v7.3.0.
