### ISSUE TITLE
Typed/Numbered GUT Errors and Warnings

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#224]
Introduce some way of identifying errors and warnings by something other than their text.

Inspired by #201 and #210.  It would be nice to be able to uniquely identify a specific error/warning  "type"  in `after_all` or a post-run hook script and take specific actions.  In this case it would be to check for the warning introduced in #201 (test did not assert) to infer that some tests did not finish due to a Godot Script Error.  You can do this now but you can only look for specific text which is error prone over time.

I'm favoring numbered/named instead of typed to keep things simple.  Approach should be added here before starting.

**Comment by astrale-sharp** [comment]
something like this looks good : 
```gdscript
extends 'res://addons/gut/test.gd'
func test_warn_me():
        if some_logic:
                warning("This warning")
```
which would add to the summary this string :
```
WARN from tests/unit/my_test.gd : test_warn_me
This warning
```

**Comment by bitwes** [comment]
I thought about it.  I don't want to do this.  It might be a good idea, but just seems like a layer of tedium that only helps in some edge cases.  This also seems like the kind of idea that I would change my mind on numerous times.  Closing this until it's re-opened or created again.
