### ISSUE TITLE
Add support for yielding in custom functions

### ISSUE THREAD

**Issue by db0** [bitwes/Gut#247]
I am using git 7.1.0 as I saw #187 was resolved there. I would like to use the yield capability in custom functions as well, as some of my integration tests are using a repeated series of tasks which requires a few yields in between.

 I would like to put the repeated block in a function and just call that for readability, but it looks like gut yielding in a functon is ignored

**Comment by bitwes** [comment]
That might not be possible due to how `yield` works.  Something like this might work but I'm not sure how GUT will handle it.
```gdscript
var value = 1
func with_yield():
  yield(yield_for(1), YIELD)
  value = 2

func test_call_with_yield():
  var func_result = with_yield()
  yield(func_result, 'completed')
  assert_eq(value, 2)
```

**Comment by CodeDarigan** [comment]
A quick fix on the user end is to emit an additional signal at the end of the loop and yield on that.

```gdscript
func with_yield():
    for i in 10:
        yield(get_tree(), "idle_frame")
    emit_signal("custom_signal")

func test_call_with_yield():
    yield(with_yield, "custom_signal")
    // testing
```

(or at least I think so).

**Comment by bitwes** [comment]
You don't need to emit a custom signal, when you `yield` in a function that method will return a `FuncRef` instance.  This has a `completed` signal that will be emitted when the function completes.  This signal is not emitted until the entire method completes, regardless of the number of times yield happens.  I tried out the following in a GUT test and it only waits .5 seconds 3 times:

```gdscript
func subroutine_yield():
	yield(yield_to(get_tree().create_timer(.5), "timeout", 10), YIELD)
	gut.p('one')
	yield(yield_to(get_tree().create_timer(.5), "timeout", 10), YIELD)
	gut.p('two')
	yield(yield_to(get_tree().create_timer(.5), "timeout", 10), YIELD)
	gut.p('three')


func test_yielding_to_sub_routines_with_yield_to():
	gut.p('start')
	yield(subroutine_yield(), 'completed')
	gut.p('after subroutine')
	pass_test('we got here')
```

```
* test_yielding_to_sub_routines_with_yield_to
    start
    -- Yielding to signal "timeout" or for 10 seconds -- 
    one
    -- Yielding to signal "timeout" or for 10 seconds -- 
    two
    -- Yielding to signal "timeout" or for 10 seconds -- 
    three
    after subroutine
    [Passed]:  we got here
```

**Comment by bitwes** [comment]
I think the example I provided shows GUT handles this scenario ok so I'm closing this one out.

**Comment by db0** [comment]
OK so basically the solution is to always yield() to the called function, instead of just calling it, ye?

**Comment by bitwes** [comment]
Correct.  There's no way for GUT to do this for you.  When a function yields, only the caller can tell if it yielded by checking the return value to see if it is a `FuncRef`.  When you yield in a test GUT can detect this since GUT is the caller for the test.  When a method called by a test yields, there is no way for GUT to know.

**Comment by bitwes** [comment]
Sorry,  not `FuncRef`, `GDScriptFunctionState`.  `gut.gd` is littered with checks on `if(script_result is GDScriptFunctionState)` for this reason.
