### ISSUE TITLE
Question of external function proper usage

### ISSUE THREAD

**Issue by db0** [bitwes/Gut#249]
I have a fairly complex function that I want to be able to easily reuse from my integration tests. This function includes a number of gut yields and is called via the yield itself. At the moment, I'm just manually copying it in all my test_*.gd files, but obviously this is not optimal. 

I tried creating an "library" .gd file with some common options (it also extends `"res://addons/gut/test.gd"`, but whenever I call the function, godot stops in the `yield_for()` function with this error

```
Invalid call. Nonexistent function 'set_yield_time' in base 'Nil'.
```

If I copy my function in the main tests script and call it from there, it works fine.

For reference, here's how my function looks like

```
# Takes care of simple drag&drop requests
func drag_drop(card: Card, target_position: Vector2, interpolation_speed := "fast") -> void:
	var mouse_yield_wait: float
	var mouse_speed: int
	if interpolation_speed == "fast":
		mouse_yield_wait = 0.3
		mouse_speed = 10
	else:
		mouse_yield_wait = 0.6
		mouse_speed = 3
	card._on_Card_mouse_entered()
	click_card(card)
	yield(yield_for(0.3), YIELD) # Wait to allow dragging to start
	board._UT_interpolate_mouse_move(target_position,card.position,mouse_speed)
	yield(yield_for(mouse_yield_wait), YIELD)
	drop_card(card,board._UT_mouse_position)
	card._on_Card_mouse_exited()
	yield(yield_to(card.get_node('Tween'), "tween_all_completed", 1), YIELD)
```

And here's a sample of the main test_file

```
extends "res://addons/gut/test.gd"

var board
var hand
var cards := []
var common


func before_each():
	common = autoqfree(UTCommon.new())
	board = autoqfree(TestVars.new().boardScene.instance())
	get_tree().get_root().add_child(board)
	common.setup_board(board)
	cards = common.draw_test_cards(5)
	hand = cfc.NMAP.hand
	yield(yield_for(1), YIELD)

func test_manipulation_buttons_not_messing_hand_focus():
	var card 
	card = cards[0]
	yield(common.drag_drop(card, Vector2(600,200)), 'completed')
```

**Comment by bitwes** [comment]
I think the problem you are having is that, although you are extending `test.gd`, that script does not exist in the same context that tests do.  GUT doesn't know anything about that script, so anything that it needs to use the common GUT instance for will fail.

If your test scripts extended THAT script then everything should work as expected.  So create:  __`res://test/db0_test.gd`__
```gdscript
extends 'res://addons/gut/test.gd'

func drag_drop(card: Card, target_position: Vector2, interpolation_speed := "fast") -> void:
	var mouse_yield_wait: float
	var mouse_speed: int
	...

func foo():
	...

func bar():
	...
```
Then each script that needs these methods should extend `res://test/db0_test.gd` instead of GUT's `test.gd`.
__`res://test/integration/test_something.gd`__
```gdscript
extends 'res://test/db0_test.gd'

func test_something():
	var f = foo()
	pass_test('Called foo in db0_test.gd')
```

**Comment by db0** [comment]
Oh right, why didn't I think of that 👍  :D
