### ISSUE TITLE
Error: assert_eq_deep and compare_deep isn't declare in the current class

### ISSUE THREAD

**Issue by bulfonjf** [bitwes/Gut#253]
I have a godot project using your tool. I can run my tests but not use some functions like asser_eq_deep or compare_deep.
I'm missing something?
![image](https://user-images.githubusercontent.com/28897384/102644908-6568a000-4140-11eb-8b57-b28f4453f0f4.png)

**Comment by bitwes** [comment]
Those methods just came out.  Probably need to update.

**Comment by bulfonjf** [comment]
Thank you very match! Now is working.
