### ISSUE TITLE
New version message

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#254]
Should be able to get the latest version from github and compare against currently running version and print out a message at the end of the run if a new version exists.

**Comment by bitwes** [comment]
latest version number is somewhere in here:
`curl https://api.github.com/repos/bitwes/Gut/releases/latest`

**Comment by astrale-sharp** [comment]
I'd like to do it! :)

It is the last part of the path contained with the key "html_url".
A code like this prints the version number : 
```gdscript
func _ready():
	# Create an HTTP request node and connect its completion signal.
	var http_request = HTTPRequest.new()
	add_child(http_request)
	http_request.connect("request_completed", self, "_http_request_completed")

	# Perform a GET request. The URL below returns JSON as of writing.
	var error = http_request.request("https://api.github.com/repos/bitwes/Gut/releases/latest")
	if error != OK:
		push_error("An error occurred in the HTTP request.")


func _http_request_completed(result, response_code, headers, body):
	var response = parse_json(body.get_string_from_utf8())

	# Will print the user agent string used by the HTTPRequest node (as recognized by httpbin.org).
	var path : String = response.html_url
	var arr = Array(path.split("/"))
	print(arr.pop_back())
```
im working on it, PR should come soon

**Comment by bitwes** [comment]
Ok.  The message should appear at the end of the run.  Any errors should be ignored.

**Comment by astrale-sharp** [comment]
this should be closed now ;)
