### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by bulfonjf** [bitwes/Gut#261]
Sorry I open an issue to ask help, if this is not the way let me know (is there a discord for this project?)

First of all, this is a great and awesome project.

The problem is that my double isn't being called and that fails the assertion.

I'm using stubs to return an array of two doubles and then singleton.gd is using the items in that array to call the do_some_work function.

I created a repo for my code if you want to see: https://github.com/bulfonjf/poc_godot_crear_escena
I speak spanish :)

This is similar to my code (in English):

---------------------------
singleton.gd
func my_func(first_param) -> void:
  var items = self.get_items()
  for item in items:
    if item.do_some_work(first_param):
      break
    
func get_items():
  return null # I put null here to be sure the test is using the double instead of singleton.gd

---------------------------
  item.gd
  
  func do_some_work(first_param) -> bool:
    return false # I have another code here, but is the same, this function will return true or false
    
    
 I wrote some test and I can make doubles of my item.gd and my singleton.gd, also I can stub the get_items func in singleton.gd with success.
 The problem appears when I want to test that my_func in singleton.gd breaks the loop on the first item that returns true.
 So I created a test, a double for the singleton, two doubles for item.gd, also I'm using stubs to force get_items to return an array of two doubles of item.gd, and using stubs to return true in the do_some_work function of those doubles.
My failing assertion is:
assert_call_count(double_item_a, "do_some_work", 1)

**Comment by bitwes** [comment]
Hola bulfonjf,

Preguntas are welcome here.  There is no discord, but that's a good idea. 

Primero, you can format code using three backticks (\`\`\`) or wrap `some words` using one.  You can even tell  it to do syntax highlighting by telling it the language (\`\`\` gdscript)
https://guides.github.com/features/mastering-markdown/

```gdscript
# ---------------------------
# singleton.gd
func my_func(first_param) -> void:
  var items = self.get_items()
  for item in items:
    if item.do_some_work(first_param):
      break
    
func get_items():
  return null # I put null here to be sure the test is using the double instead of singleton.gd

# ---------------------------
# item.gd  
  
  func do_some_work(first_param) -> bool:
    return false # I have another code here, but is the same, this function will return true or false
```

I tried to look at your repo, but couldn't quickly find the file you are having issue with.  If you can provide me the following I'll try to help:
* link to the failing test.  You can copy permalinks in github to a line like [this one](https://github.com/bulfonjf/poc_godot_crear_escena/blob/c3614e4194c7f2b42ef9ea2b581cac1201a77d04/test/unit/componentes/test_componentes.gd#L17)
* The failure.  It's not clear if you are getting too many or not enough calls to the method.
* Links to any of the related files being tested.

I really wish I could remember more Spanish.  Pero that's how things go.

**Comment by bulfonjf** [comment]
Thank you very much!


- Link to the failing test. You can copy permalinks in github to a line like this one
  -  [failing test](https://github.com/bulfonjf/poc_godot_crear_escena/blob/c3614e4194c7f2b42ef9ea2b581cac1201a77d04/test/unit/contextos/test_comandos.gd#L25).  
  - You will see this:
  ` gdscript pass_test("no podemos verificar que corte con el primer procesador que de true")`
  because I'm ignoring the test for now, but the code of the test is commented.
- The failure. It's not clear if you are getting too many or not enough calls to the method.
  -  this is the failing assertion    `assert_call_count(procesador_a, "procesar", 1, [path_de_acciones_valido])`.
  -  _procesador_a_ should be called once
  -  and _procesador_b_ should not be called
- Links to any of the related files being tested
  - [method I want to test](https://github.com/bulfonjf/poc_godot_crear_escena/blob/c3614e4194c7f2b42ef9ea2b581cac1201a77d04/contextos/comandos.gd#L33)
  - I'm using stubs for:
    - [obtener_procesadores](https://github.com/bulfonjf/poc_godot_crear_escena/blob/c3614e4194c7f2b42ef9ea2b581cac1201a77d04/contextos/comandos.gd#L43)
    - [procesar](https://github.com/bulfonjf/poc_godot_crear_escena/blob/c3614e4194c7f2b42ef9ea2b581cac1201a77d04/procesador_acciones/procesador_acciones_base.gd#L3)

You will have to take into account that
- The system under test (SUT) is a singleton. Is the 'contextos/comandos.gd' file.
- and  I'm using a double for the SUT, because I want to force the '_obtener_procesadores_' function to return a specific array with two processors. I think this is a bad practice because you can't make a double for the SUT, maybe I have to move the '_obtener_procesadores_' function to another script.


I wanted to test something very simple:
- get a list of processors (using '_obtener procesadores_' function)
- then for each processor call the function '_procesar_'
- the first processor that returns true should break the for each loop
- there are two files or scripts, one with the method to test, and the other with the '_procesar_' function.

**Comment by bitwes** [comment]
Thanks for the detailed response.  This helps a lot.  

If I understand correctly, you are trying to test that when you call ` sut.ejecutar_primer_procesador_que_aplique` it  performs some action on `procesador_a` and not `procesador_b`.

If that is the case then I think you want  a `partial_double` of `sut` or you should `stub(sut, "ejecutar_primer_procesador_que_aplique").to_call_super()` depending on how much functionality in `sut` you need to retain.

`sut` will not execute any of the code in `"res://contextos/comandos.gd"` because it is a `double`.  Stubbing a method `to_call_super` will run the method in the super class (`"res://contextos/comandos.gd"`).  You have to `stub` each method when using `double`.  A  `partial_double` defaults all methods `to_call_super`.

Check out this page of the wiki on Partial Doubles https://github.com/bitwes/Gut/wiki/Partial-Doubles

Let me know if you have any questions or if I didn't understand the issue correctly.

**Comment by bitwes** [comment]
There are not any issues with the `singleton` in this case because you testing a local instance correctly.  You may have issues later if you are testing something that **uses** the `singleton`.  In these cases I recommend using a local variable for the singleton.
Example for your setup:
``` gdscript
# res://my_class.gd
# Comandos is an autoload singleton at "res://contextos/comandos.gd"
# In your class that uses Commandos use a local variable instead
var _commandos = Comandos
...
_commandos.foo()
var b = _commandos.bar()
```
When testing you can inject the double into  the script with
``` gdscript
# res://test/test_my_class.gd
func test_something():
  my_instance = load("res://my_class.gd").new()
  my_instance._commandos = double("res://contextos/comandos.gd").new()
  ...
```
This is cumbersome but right now it is the only way to stub a singleton used by another class.

**Comment by bulfonjf** [comment]
I change double for partial_double in one line and my test works great!
Thank you very much!!

**Comment by jamie-pate** [comment]
IDK if this will work in godot4 but in godot3 you _can_ mock autoloads by calling `set_script()` on autoload node... But it's not for the faint of heart..
https://github.com/jamie-pate/godot-code-coverage/blob/main/addons/coverage/Coverage.gd#L225
