### ISSUE TITLE
Testing Equality with Custom Classes

### ISSUE THREAD

**Issue by Kodota** [bitwes/Gut#262]
It would be really helpful to have some method to test the equality of custom classes that call for the implementation of their own equality method.

As an example, I'm currently making a boss enemy that has various actions such as a punch and a jump attack, where each action is its own subclass of a main action class. I'm currently attempting to test that the right actions are returned by a function when called without resorting to using assert_is, since checking the exact class of an object would mean creating a tight coupling between that test code and my specific implementation which may change in the future. (In particular, I can see myself replacing the polymorphism with class variables that simply indicate which animation to play and whatever other action-related information is necessary.)

I've gotten around this problem by using the following test code:
```
# The action returned by get_next_action is expected to be a punch action.
var action = enemy.get_next_action`
# EnemyAction.punch() and EnemyAction.jump() are static constructors for the correct action type.
assert_true(action.equals(EnemyAction.punch())
assert_false(action.equals(EnemyAction.jump()))
```

In this case, EnemyAction.equals is a custom implementation to check the equality of the two objects. This solution that I've found works fine, but the only thing I'm unhappy with is that I lose the convenient log message that gets attached to the test when using assert_eq.

I'm not really sure what the best way would be to implement this given that GDScript doesn't have a built-in standard for overloading the equals operator. My first thought is maybe an assert_custom_equals function that takes in two object, and the name of a function to be called on the first object with the second object as the parameter, though that might be too error prone a solution. Another possibility would be adding an optional parameter to assert_eq, but I fear that would add unnecessary complexity to the function signature.

**Comment by bitwes** [comment]
I think you've hit on all the points that would make implementing something difficult.  Adding the optional text at the end of your asserts would improve your output a little.
```
assert_true(action.equals(EnemyAction.punch(), "action is punch")
assert_false(action.equals(EnemyAction.jump()), "action is not jump")
```
Or you could roll your own assert.  You can put that in a script that all your tests extend instead of `test.gd`
```
# res://test/my_cool_test_superclass.gd
extends "res://addons/gut/test.gd"

func assert_character_action(action, expected_type, text=""):
    var msg = str("action type [", action.get_name_or_whatever(), "] expected to be [" expected_type.get_name_or_waterver(), "] ", text)
    if(action.equals(expedted_type)):
        pass_test(msg)
    else:
        fail_test(msg)
```
Then  your other test scripts extend `my_cool_test_superclass` and you can do:
```
assert_character_action(action, EnemyAction.jump())
```

**Comment by bitwes** [comment]
Seems to be resolved.  Reopen if anything else comes up.
