### ISSUE TITLE
"View readme for usage details." - Add readme?

### ISSUE THREAD

**Issue by CitrusWire** [bitwes/Gut#264]
Thanks for this, looks promising!

The gut.gd file says:
> View readme for usage details.

But there is no Readme included in the download that comes from the Godot Asset Library.

I guess one should be added, also probably link to the online docs given that seems to be where the usage stuff is.

**Comment by bitwes** [comment]
The comment should be changed to have links to the readme and wiki instead of saying to check the readme.

**Comment by astrale-sharp** [comment]
Im on this!
