### ISSUE TITLE
Assert_eq with mismatched types + signal params wrapped in an array

### ISSUE THREAD

**Issue by nightblade9** [bitwes/Gut#268]
Hopefully this screenshot says it all:

![image](https://user-images.githubusercontent.com/31222662/107260061-bb084d00-6a0b-11eb-8b21-7ac9a9a2c1d9.png)

If I have a class `player` with a signal `try_to_move` and I call it with `emit_signal("try_to_move", Vector2(1, 0))`, then in my test I would assert as:

`assert_signal_called_with_parameters(player, "try_to_move", Vector2(1, 0))`

I run into two problems:

1) Godot/Gut/something wraps the parameters into an array. The actual value I get back is the one-element array with a Vector2 inside, a la `[Vector2(1, 0)]`. This seems like an implementation detail that's a leaky abstraction in my tests (I didn't know about this)

2) When the types aren't equal, I don't get a clear error that this is the problem; instead, Godot ends up putting a breakpoint on some Gut code. It's the final line in this block:

```gdscript
func assert_signal_emitted_with_parameters(object, signal_name, parameters, index=-1):
	var disp = str('Expected object ', _str(object), ' to emit signal [', signal_name, '] with parameters ', parameters, ', got ')
	if(_can_make_signal_assertions(object, signal_name)):
		if(_signal_watcher.did_emit(object, signal_name)):
			var parms_got = _signal_watcher.get_signal_parameters(object, signal_name, index)
			var diff_result = _compare.deep(parameters, parms_got)
			if(diff_result.are_equal()):
```

`diff_result.summary` clearly indicates the problem: `Vector2(1, 0) != Array([Vector2(1, 0]).  Cannot compare Vector2 with Array.`

It would be great if - instead of seeing the Gut code - I get a clear error that there's a type mismatch.

**Comment by bitwes** [comment]
`assert_signal_called_with_parameters` requires the parameters to check to be passed as an array.  The following should work:
```
assert_signal_called_with_parameters(player, "try_to_move", [Vector2(1, 0)] )
```

GUT should detect when the parameters passed in are not an array, log an error and fail the test.
