### ISSUE TITLE
Some _utils method reimplement core functionalities

### ISSUE THREAD

**Issue by astrale-sharp** [bitwes/Gut#273]
Hi!
in _utils we can see 2 well implemented methods :
```gdscript

# ------------------------------------------------------------------------------
# Returns an array created by splitting the string by the delimiter
# ------------------------------------------------------------------------------
func split_string(to_split, delim):
	var to_return = []

	var loc = to_split.find(delim)
	while(loc != -1):
		to_return.append(to_split.substr(0, loc))
		to_split = to_split.substr(loc + 1, to_split.length() - loc)
		loc = to_split.find(delim)
	to_return.append(to_split)
	return to_return


# ------------------------------------------------------------------------------
# Returns a string containing all the elements in the array separated by delim
# ------------------------------------------------------------------------------
func join_array(a, delim):
	var to_return = ''
	for i in range(a.size()):
		to_return += str(a[i])
		if(i != a.size() -1):
			to_return += str(delim)
	return to_return
```

However it looks like overkill since I'm pretty sure these would suffice :

```gdscript
func split_string(to_split, delim):
	return Array(to_split.split(delim))

func join_array(a, delim):
	return PoolStringArray(a).join(delim)
```
Do we even need method for that?
What do you think?

**Comment by bitwes** [comment]
These were created a LONG time ago.  They probably aren't needed anymore but they are easier on the eyes than the Godot equivalent.  I'm fine with  just updating the  implementation to use Godot methods.
 
`split_string` could be should be fine.  You'd have to check if `join_array` would be ok with a `PoolStringArray` everywhere.  I think it should be fine though.

**Comment by astrale-sharp** [comment]
join_array returns a String so I think it would be okay!

**Comment by astrale-sharp** [comment]
split_string is used once in the codebase
join_array is used twice

maybe we don't need these functions, I think we should get rid of them, what do you think?

**Comment by bitwes** [comment]
If that's all they are  being  used then  yea, we should get rid of them.

**Comment by astrale-sharp** [comment]
on it!
