### ISSUE TITLE
Typing the classes

### ISSUE THREAD

**Issue by astrale-sharp** [bitwes/Gut#278]
The idea is the following : 
Using typing for helper classes would 
1) reduce accidental mistakes when improving gut 
2) permits autocompletion
3) permits clicking to access documentation directly

it would be implemented by replacing occurrences like 
```gdscript
var _utils = load('res://addons/gut/utils.gd').get_instance()
```
by something like
```gdscript
var _utils := preload('res://addons/gut/utils.gd').new()
```

It seems like a good idea what do you think?

**Comment by bitwes** [comment]
`_utils` is a special class.  It is a pseudo-singleton.  Everything has to use `get_instance` so that only one instance of `utils.gd` is created.  This was done so that users didn't have to setup and autoload and I wanted a singleton.
