### ISSUE TITLE
add an optional #should_fail tag to tests

### ISSUE THREAD

**Issue by astrale-sharp** [bitwes/Gut#279]
I'm working on the snapshot features and I want to assert that some test fails: for instance

```gdscript
func test_node_should_fail():
	var x = Position2D.new()
	x.position = Vector2.LEFT
	assert_matches_snapshot(x)
```
should fail because objects don't have a json representation.

but I don't want other people working on the project thinking the snapshot doesn't work

A workaround is putting all such test in an inner class like `TestShouldFail` .

Im not sure how we could implement this, maybe a property holded by the current test we could change by having a method like this
```gdscript
func test_node_should_fail():
	should_fail()
        var x = Position2D.new()
	x.position = Vector2.LEFT
	assert_matches_snapshot(x)
```

**Comment by bitwes** [comment]
Tests in `test.gd` have access to `assert_fail` and `assert_pass1` which are defined in `BaseTestClass`.  If you are making asserts on assert methods then you should create an inner test class in `test.gd` that extends `BaseTestClass`.  See other tests in file for examples on how to use them.

**Comment by bitwes** [comment]
Closing because I think this is stale.
