### ISSUE TITLE
Parameterized do not warn if no asserts were made.

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#281]
If one of the parameters of a parameterized test does not cause any assertions to be made then it should warn that the test did not assert the way non-parameterized tests do.

**Comment by Nahdus** [comment]
Is this issue fixed I am able to see  "Test did not assert" warning on parameterized test

**Comment by Nahdus** [comment]
@bitwes ?

**Comment by bitwes** [comment]
This is now fixed in the next release.

**Comment by bitwes** [comment]
Released in v7.3.0.
