### ISSUE TITLE
Should GUT errors cause a test to fail?

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#282]
I think it would be possible to fail any test that generates a GUT error.  Off the top of my head I can't think of any reason why an error wouldn't be fatal to a test (it should be a warning instead).  There are probably a lot of cases where an error might be missed and the test result could be invalid then.

**Comment by ccanandmallik** [comment]
I'd appreciate this -- using this library now and while GUT errors do trigger warnings, it's easy to miss given the output says "All tests passed" at the end.

Normally I see testing libraries include an option for something like "warnings trigger test failures" such that if desired people can skip over warnings or cause them to fail the test run as an option.

I have some time and am familiar with and indebted to this work -- I might take a stabby stab at it in the next few weeks and push some code if it's a simple enough fix.

Thanks for the great project, it's really nice to use a TDDish style approach with GameDev!

**Comment by bitwes** [comment]
Errors cause failures now and Warnings cause risky.
