### ISSUE TITLE
Typo in wiki Hook page in hook script path

### ISSUE THREAD

**Issue by Ajver** [bitwes/Gut#286]
In the wiki Hooks page, in [Overview](https://github.com/bitwes/Gut/wiki/Hooks#overview) section there is a typo in 3rd paragraph, in the script path that the Hooks must inherit from: `res://addons/gut/hook_scirpt.gd`. It should be: `res://addons/gut/hook_script.gd`. 

Note that the same typo is in both paths in that paragraph, but not in any other parts of the wiki. At least I couldn't find it anywhere else.

**Comment by bitwes** [comment]
The infamous "scirpt" strikes again!  Fixed.  Thanks.
