### ISSUE TITLE
Test animation callback

### ISSUE THREAD

**Issue by afonsolage** [bitwes/Gut#289]
What is the best way to test if an animation is calling a function?

I have a Scene, named `MainPlayer` which triggers a function named `_attacking_started` when the animation `1h_attack` is, started.

![image](https://user-images.githubusercontent.com/1176452/112704831-ce1b9300-8e7a-11eb-8012-dbcdc97558eb.png)

I'm trying to test this using a `partial_double` as follow:
```gdscript
class TestMainPlayerScene:
	extends "res://addons/gut/test.gd"

	var scene_double
	var main_player_scene
	
	func before_all() -> void:
		scene_double = partial_double("res://scenes/characters/main_player.tscn")
		main_player_scene = scene_double.instance()
		self.add_child_autoqfree(main_player_scene)

	func test_when_playing_attack_animation_call_attacking_started_func() -> void:
		main_player_scene._animation_tree.set("parameters/attack/active", true)
		yield(get_tree().create_timer(2), "timeout")
		assert_called(main_player_scene, '_attacking_started')
```

But the `assert_called` tells me that the `_attacking_started` is never called. The animation is working fine when normal playing, tested it with debug. 

Any ideas what i'm doing wrong?

**Comment by bitwes** [comment]
Is this the only test in `TestMainPlayerScene`?  If not then maybe another test is mucking up `main_player_scene`.  I'd change `before_all` to `before_each` just to be safe going forward.

If that's not the issue then I'm not sure what is wrong.  I've not used an  `AnimationTree` before but everything else looks fine.  Is `_attacking_started` actually being called during the test?

**Comment by afonsolage** [comment]
I found that If the bacllback on animation is set to frame 0, it isn't called. After changing to 0.1, it worked fine.

If someone needs to know how to do this, this is the best I was able to get:

```gdscript
class TestMainPlayerScene:
	extends "res://addons/gut/test.gd"

	var scene_double
	var main_player_scene
	
	func before_each() -> void:
		scene_double = partial_double("res://scenes/characters/main_player.tscn")
		main_player_scene = scene_double.instance()
		self.add_child_autoqfree(main_player_scene)


	func test_when_playing_attack_animation_call_attacking_started_func() -> void:
		main_player_scene.get_node("AnimationPlayer").playback_speed = 2.0
		main_player_scene._animation_tree.set("parameters/attack/active", true)
		
		yield(get_tree().create_timer(0.2), "timeout")
		
		assert_called(main_player_scene, '_attacking_started')
```

**Comment by bitwes** [comment]
Closing, reopen if there's any other issues around this.
