### ISSUE TITLE
make concurent execution optional

### ISSUE THREAD

**Issue by Scony** [bitwes/Gut#298]
Test cases within the same `.gd` file are being run concurrently if they use `yield`, and hence if test cases may interfere with each other, it's impossible to group them in one file. It should be controllable by some opt probably.

**Comment by bitwes** [comment]
I've not seen that happen before and I use yields heavily 8n my own game's
tests.  Can you give some sample code.

Gut detects when a yield occurs in a test and will wait for the test to
finish.  If you have yields in the code you are trying to test you have to
explicitly yield in the test itself.  Gut can't know of yields that do not
occur in the test.

**Comment by Scony** [comment]
Okay, then my test cases must have been corrupting the global state somehow. Let's close this then.
