### ISSUE TITLE
Compatible with Godot 3.3.x?

### ISSUE THREAD

**Issue by Losatu** [bitwes/Gut#303]
Start paga says:

> Gut 7.1.0
> Godot 3.2.x compatible, includes all releases from 3.2.0 through 3.2.2. 6.8.3 is 3.1 compatible

I guess it is also Godot 3.3.x comaptible, right?

**Comment by bitwes** [comment]
I don't know of any issues with 3.3, but I have not tested it with 3.3 yet.  GUT had been put on the back burner while I completed my game.  I just saw the notification for this issue at the same time that I saw a notification that my game had been approved in the iOS store....so I'll be getting back to Gut soon.

**Comment by bitwes** [comment]
Verified `3.3.0` and `3.3.3` by running GUT's test suite.

**Comment by Losatu** [comment]
Thank you for verification :)
