### ISSUE TITLE
Tests are freezing on Linux (Ubuntu)

### ISSUE THREAD

**Issue by nightblade9** [bitwes/Gut#311]
I'm trying to get GitHub Actions to work for my Godot project to work - to run the tests on the build node. It's working. I don't know if it's something wrong with my tests, or if it's Gut, so I would appreciate any help in debugging what's going on. Unfortunately, I can't share my code.

Here's my .gutconfig.json:

```json
{
  "dirs":["res://tests/"],
  "double_strategy":"partial",
  "ignore_pause":false,
  "include_subdirs":true,
  "inner_class":"",
  "log_level":3,
  "opacity":100,
  "prefix":"Test",
  "selected":"",
  "should_exit":true,
  "should_maximize":true,
  "suffix":".gd",
  "tests":[],
  "unit_test_name":""
}
```

Runtime command: `./Godot_v3.3.3-stable_linux_headless.64 -s addons/gut/gut_cmdln.gd --path . -ghide_orphans
`

What I tried:

- Running this on Windows with the Windows (non-headless) Godot works.  There are lots of errors, but all the tests succeed and the process terminates
- Running the tests on Linux with the headless Godot on Linux feezes
- Running on Linux with the non-headless Linux Godot also freezes
- Running via GitHub Actions also freezes. I can't see the console output, though.

I can guess which tests are freezing (the suites seem to run in the same order each time). 

How can I debug and resolve this issue?

**Comment by nightblade9** [comment]
I solved this by opening Godot on a Linux VM and running my test scenes manually. Turns out I had a case error (e.g. `Environment` instead of `environment` in a `preload`). Fixing that unfroze the build.

It would be great to have a way to figure this out through Gut - there are like 300+ errors and warnings when I run my tests (mostly due to my code) - but this isn't a critical/blocking issue for me any longer.

**Comment by bitwes** [comment]
I doubt this is your issue, but for CI things you should always have `"ignore_pause":true`.  This causes any calls to `pause_before_teardown` to be ignored.  Also, the run-order for scripts should be consistent (I think) but the tests themselves are not consistent.  Gut gets the test names from Godot and the order they are returned is not guaranteed. 

Can you share the output from either of the Linux runs?  It's hard to help without at least seeing the output from a run.

Two things I can think to try:
* Try running with Windows headless.  That'll help decide if it is a platform or headless issue.
* Try getting a single script or test to hang by using the options/gutconfig to restrict which tests are run.


....aaaaaaaand you fixed it as I was typing.  Cool.

**Comment by nightblade9** [comment]
Honestly, I don't know what you can do differently in Gut to make this more obvious when something fails. Maybe the only real takeaway is that the test-order should somehow be deterministic. (Maybe sort test-names alphabetically when you get them from Godot?)

Feel free to close this if there's nothing significant you can do on the Gut side to make cases like this easier to debug.

**Comment by bitwes** [comment]
Yea, I don't think I can do much.  If Godot is hung, Gut can't do much either.  I've thought about sorting tests.  I really want to sort them in the order they are declared though and implementing that would be gross.  Sorting alphabetically feels wrong.

The master branch currently has an xml export that makes comparing the results of two runs a lot easier but the run has to complete for this to be helpful.  Closing this out, reopen if something else comes up.
