### ISSUE TITLE
How to set onready var with a partial_double

### ISSUE THREAD

**Issue by bbenefield89** [bitwes/Gut#313]
If I have the following script:

```python
extends KinematicBody2D

var current_target = null setget set_current_target

onready var UpdatePathToEnemyTimer := $UpdatePathToEnemyTimer

func set_current_target(value: KinematicBody2D = null) -> void:
	if value != null and is_instance_valid(value):
		remove_existing_connection(value.Stats)
		value.Stats.connect("zero_health", self, "set_current_target")
		UpdatePathToEnemyTimer.start(update_path_to_enemy_cd)
	else:
		remove_existing_connection(current_target.Stats)
	current_target = value
```

How would I tests this? I've tried a few different strategies noted in the wiki but I can't find an example for my case. The case of "I need to mock a method, `remove_existing_connection()`, but I also need to set the value of an onready variable, ` UpdatePathToEnemyTimer`.

I've been able to bypass this by treating `UpdatePathToEnemyTimer` as a normal variable, `var UpdatePathToEnemyTimer;`, and setting it in `_ready()` but I'd rather not use this method when accessing it via a `$` works with less code all for the sake of testing.

A couple of things I've tried:

I've tried creating a `partial_double` of the scene and instancing it but then I cant access methods or props on the instance
```python
func test_update_path_to_enemy():
	var Creature = partial_double("res://Creatures/Creature/Creature.tscn").instance()
	replace_node(Creature, "UpdatePathToEnemyTimer", Timer.new())
	stub(Creature, "remove_existing_connection").to_do_nothing()
	
	var enemy = Enemy.new()
	Creature.set_current_target(enemy)  # Nonexistent function 'set_current_target'
	pass_test("")
```

I've also tried creating a `partial_double` of the script but then my onready vars are always Null
```python
func test_update_path_to_enemy():
	var Creature = partial_double("res://Creatures/Creature/Creature.gd").new()
	Creature.UpdatePathToEnemyTimer = UpdatePathToEnemyTimer.new()
	stub(Creature, "remove_existing_connection").to_do_nothing()
	
	var enemy = Enemy.new()
	Creature.current_target = enemy  # Calls set_current_target() but then UpdatePathToEnemyTimer is Null
	pass_test("")
```

**Comment by bitwes** [comment]
You can `add_child` inside tests since `test.gd` inherits from `Node`.  I think you are just missing `add_child(Creature)`.

When using `add_child` inside a test you have to free the object or it will make orphans.  If you continue using a `double` or `partial_double` then Gut frees the object for you.  If you do not, then you can call `autofree`, `autoqfree`, `add_child_autofree`, and `add_child_autoqfree`. 

More info here: https://github.com/bitwes/Gut/wiki/Memory-Management

**Comment by bbenefield89** [comment]
Thanks for getting back to me so quickly. Something very interesting is going on here and I'm wondering if you've encountered anything like this before.

I read your comment and was confused about which snippet of code you wanted me to use `add_child(Creature)` one but I recalled from the docs you used that on a `*.tscn` file so I tried to first snippet and I got the same exact error `Creature.set_current_target(enemy)  # Nonexistent function 'set_current_target'`.

Then I tried the second snippet of code, did not change anything, ran the test and everything worked fine. I then tried to play around and see if I could break anything and I eventually got it to break by using an already loaded script passed to `partial_double()`. The error was the same as the second snippet, where my `UpdatePathToEnemyTimer` is Null. Example:

```
var Creature = load("res://Creatures/Creature/Creature.gd")

func test_update_path_to_enemy():
	var creature = partial_double(Creature).new()
        .... more stuff but nothing changed ...
```

I then reverted back to passing a string: `var creature = partial_double("res://Creatures/Creature/Creature.gd").new()`, and it was still broken. Curious, as passing a string worked before.

Finally, I stashed all my changes, switched branches (develop), and then came back to my testing branch. Took the second snippet of code from above, ran it and now everything works. I can even pass in an already loaded script and its not breaking as of writing this.

Back to the question, have you or anyone else experienced this issue?

**Comment by bitwes** [comment]
`double` and `parital_double` accept both a string (path) or a loaded class.  There shouldn't be any issue in switching between those two approaches for creating the doubles.

I think the confusion has to do with the difference between `.gd`/`.tscn` and `new`/`instance`.  The `.tscn` file has (I assume) the `.gd` file set for its script property.  When you `add_child` to a scene that has a script, the `onready` vars are populated from the objects in the scene tree and then the `_ready` method is called.  When you only instantiate the `.gd` file with `new`, you are creating an instance of the script but it is missing all the objects in the `.tscn` file.  This is why all your `onready` variables are empty even though you've called `add_child`.

**Comment by bbenefield89** [comment]
Very interesting and thank you for clarifying. For now, I've resorted to placing any of my `onready` vars into the `_ready()` method as this seems to work flawlessly and to be honest, I would rather have tested code than "cleaner" code.  

As I get more comfortable with this library I'll play around with this idea some more but thanks again and thanks for maintaining this code base!
