### ISSUE TITLE
GUT Panel Improvements

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#324]
Here's a list of things that didn't get done in the first release of the GUT Panel.

- [x] Run at cursor (same as run at cursor in the VSCode plugin).  This should populate "run like" fields so that you don't have to keep switching back to the test script to run it.
- [ ] ~~Colors in the output (a bunch of logging has to change for this to work, might be too much)~~ Out of scope for this issue.
- [x] Add orphans, errors, and warnings to the totals above output.
- [x] Shortcuts dialog could look better.
- [x] Directories should open up the File dialog to pick instead of being typed in.
- [x ] Log level could get descriptive names for levels instead of a number (added to mouse over)
- [x] Font settings for GUT Panel output instead of reusing the GUT settings.

#### Add settings 
- [x] pre-run hook
- [x] post-run hook
- [ ] ~~test name prefix~~ not a setting
- [x] font color
- [x] background color 
- [ ] color output (t/f)
- [x] show orphans
- [ ] ~~inner test class name prefix~~
- [ ] ~~test export path~~ I think you still need a scene to run tests on a device, so this does not help.
- [ ] ~~double strategy~~ I don't think you want to set this for the test suit.  This has very limited use cases.

**Comment by smks** [comment]
Can we also support the file extension option? I use the suffix: `MyScript.test.gd` - it's so I can group my tests with their source files, easier to navigate them and not as easy to forget they exist.

<img width="247" alt="Screenshot 2022-04-03 at 10 29 39" src="https://user-images.githubusercontent.com/4087157/161421047-a58b10dc-c3bc-40c1-8dd6-5051b205c6e9.png">

**Comment by smks** [comment]
Alternatively can we support test_suffix, so I could do:
```
test_suffix: 'Test'
MyScriptTest.gd
```

**Comment by bitwes** [comment]
@smks Can you make another issue with this feature in it?  I'm closing this issue since the original scope of the issue has been implemented in v7.3.0 but I don't want to lose these.

**Comment by bitwes** [comment]
Released in v7.3.0.
