### ISSUE TITLE
watch_signals(obj) not working when using the signal keyword

### ISSUE THREAD

**Issue by ericdsw** [bitwes/Gut#33]
If i have an object with a signal declared like this:
```
signal some_signal_name
```
Then using `watch_signals(my_object)` and calling `assert_signal_emited(my_object, "some_signal_name")` fails with the message "Cannot make signal assertion because the object is not being watched...". However, if I register my signal in my object like this (note that I'm not using the `signal` keyword):
```
func _init():
    add_user_signal("some_signal_name")
```
The assertion works, which makes me think that the test class is using a method that does not account for the signals registered using the keyword, and they are not correctly registered by `watch_signals(object)`.

I think it is related to this issue, which addresses the fact that there are multiple (poorly documented) methods to check for signals, and they behave differently: https://github.com/godotengine/godot/issues/9800

**Comment by bitwes** [comment]
Verified it isn't seeing them.  I can't get it to see them if I try to watch that specific signal or with `watch_signals`.  Hope to have a fix by the end of the weekend.

**Comment by bitwes** [comment]
"end of the weekend" was evidently 43 minutes later...quick weekend I guess.

@ericdsw Any interest in double checking if this fixed things?  I tested all the cases I could think of.   I didn't get the "object isn't being watched" message but I may have fixed it too much before I tested it (I started with the signal_watcher class then worked out to the asserts).

https://github.com/bitwes/Gut/tree/script_signals

**Comment by ericdsw** [comment]
Nice.

Sure, as soon as I get the chance, I'm gonna test it in multiple scenarios to see if any other issues arise. Will keep you updated.

**Comment by bitwes** [comment]
Thanks.

**Comment by ericdsw** [comment]
Can confirm that both `assert_signal_emitted()` and `assert_signal_emitted_with_parameters()` are working as intended, tested it with the following cases (note: I omitted some code unrelated to the signal assertion itself):

A simple test that checks if a node called `PlayerData` correctly emits a signal called `on_damage_received`. Works as expected.
```
# Inside the node PlayerData

signal on_damage_received

func receive_damage():
    emit_signal("on_damage_received")

# Inside test_PlayerData
var player_data

func setup():
    player_data = load("path_to_player_data").instance()
    add_child(player_data)

func test_it_propagates_damage_received():
    watch_signals(player_data)
    player_data.receive_damage()

    assert_signal_emitted(player_data, "on_damage_received")
```

A test that checks if a node called `Inventory` correctly emits a signal called `consumable_stack_full` when it tries to add more consumables than it's defined limit (in this case, 16). This signal must accept a parameter indicating which consumable caused the overflow. Also works as expected.

```
# Inside the node Inventory
var consumables = []
signal consumable_stack_full(consumable)

func add_consumable(consumable):
    if consumables.size() > 16:
        emit_signal("consumable_stack_full", consumable)
    consumables.append(consumable)

# Inside test_Inventory
var inventory
func setup():
    var inventory = load("path_to_inventory").instance()
    add_child(inventory)

func test_it_detects_when_consumable_stack_is_full():
    # Generic logic to fill the inventory's consumable list to the maximum amount
    var overflow_consumable = Consumable.new() # Generic consumable
    
    watch_signals(inventory)
    inventory.add_consumable(overflow_consumable)

    assert_signal_emitted_with_parameters(inventory, "consumable_stack_full", [overflow_consumable])
```

And just to make sure the assertion was working as expected, I removed the call to `watch_signals` in both tests and got the message `Cannot make signal assertion because the object is not being watched...`, which is the expected behavior.

I don't have any test using the `assert_signal_not_emitted` method, nor any test that fires a signal with parameters multiple times (to test the `index` parameter in `assert_signal_emitted_with_parameters`), but as far as I can tell, the issue should be fixed.

**Comment by bitwes** [comment]
@ericdsw thanks for the super thorough check!
