### ISSUE TITLE
Feature Request: Log level

### ISSUE THREAD

**Issue by Lyaaaaaaaaaaaaaaa** [bitwes/Gut#336]
It could be very useful to set the level of logs in the workflow file like you can do in Godot.
![image](https://user-images.githubusercontent.com/44974422/148052431-36f77f2c-5d31-4943-8c93-f520ec277b9e.png)
When there is no error, log level at 1 is enough, but if something fails, having logs level to 2 or 3 can come handy.

**Comment by bitwes** [comment]
What exact file are you speaking of?  You can set the log level in many places.  
* Using the slider on the GUI.
* The  GUT Panel (v7.2.0).
* Settings Panel for Gut object (when running as a scene).
* `.gutconfig.json` file when running from the command line or through VSCode extension.

**Comment by Lyaaaaaaaaaaaaaaa** [comment]
Ah sorry I'm an idiot. I thought I was in the https://github.com/croconut/godot-tester repo...
xD
