### ISSUE TITLE
mixed indentation with tabs and spaces is considered an error in Godot 4

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#338]
mixed indentation with tabs and spaces is considered an error in Godot 4 - used in a few places to align continuation lines.

These should be changed to two-tab indent for continuations.

**Comment by PrinceMerluza** [comment]
Does the project officially support 4.0?

**Comment by bitwes** [comment]
It does not.  I'm waiting for the first Beta before I put any effort into
converting it.  There is a 4.0 branch, and at least one person got it to
run in 4.0 (and has a fork somewhere, it's in one of the issues), but I
haven't tried it out yet.

**Comment by bitwes** [comment]
These have all been addressed in godot_4 branch.
