### ISSUE TITLE
Setting variables of built-in types to null is impossible when adding type hints

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#339]
Setting variables of built-in types to null is impossible when adding type hints, and sometimes marked as an error otherwise.

So maybe it is worth to think of other ways of indicating "no value yet", or lobby for the nullable? types proposal that's on godot-proposals.

**Comment by strank** [comment]
Hi @bitwes I do have a 4.0 branch now that at least allows you to run the whole test suite on the command line. See https://github.com/strank/Gut/tree/4.0 It's 10 commits behind your master branch right now, and the current end result, running with godot built from this branch https://github.com/strank/godot/tree/gut-porting-to-godot4 (which has two fixes not yet in main Godot), is:

```
Totals
Scripts:          40
Passing tests     1001
Failing tests     87
Pending:          4
Asserts:          1364/115

Warnings/Errors:
* 17 Errors.
* 6 Warnings.


1001 passed 87 failed.  Tests finished in 104.6s
```

versus on Godot 3.4.2:

```
Totals
Scripts:          40
Passing tests     1079
Failing tests     9
Pending:          4
Asserts:          1528/16

Warnings/Errors:
* 17 Errors.
* 6 Warnings.


1079 passed 9 failed.  Tests finished in 97.4s
```

Hope that helps in some way :)

**Comment by bitwes** [comment]
I believe this is not an issue any longer.
