### ISSUE TITLE
Verify everything works on lastest stable 2.1.4

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#34]
I've been running everything on 2.1.1 for awhile now.  It's time to upgrade or get someone to verify it works with the latest version.

**Comment by MIfeanyi** [comment]
@bitwes I currently use 2.1.4 and just got setup and working. This was my output running the example test:
`/-----------------------------------------
Testing Script res://test/unit/test_example.gd
-----------------------------------------/
* test_assert_eq_number_not_equal
    FAILED:  [1] expected to equal [2]:  Should fail.  1 != 2
      at line 14
* test_assert_eq_number_equal
* test_assert_true_with_true
* test_assert_true_with_false
    FAILED:  Should fail
      at line 23
* test_something_else
    FAILED:  didn't work
      at line 26



*****************
Run Summary
*****************
  scripts:   1
  tests:     5
  asserts:   5
  passed:    2
  pending:   0
  failed:    3


+++ 2 passed 3 failed.  Tests finished in:  0.000 s +++
`
and can be verified in my [project](https://github.com/MIfeanyi/Endless) . I have verified I'm running 2.1.4 but please let me know if I did anything wrong.

**Comment by bitwes** [comment]
If you could try running test_gut.gd test_test.gd from the GutTests repo that would be a better test but this is a great indicator that everything is fine.

https://github.com/bitwes/GutTests/blob/master/test/unit/test_test.gd
https://github.com/bitwes/GutTests/blob/master/test/unit/test_gut.gd

Thanks for the help.
