### ISSUE TITLE
Add text filter for test selection

### ISSUE THREAD

**Issue by db0** [bitwes/Gut#349]
I'm using the GUI to perform individual tests, but I now have so many inner classes, that it takes me quite a while to find where what I want to test is, since the list is not always in the same order.

![image](https://user-images.githubusercontent.com/296513/161698336-42fa7240-f35c-41e5-8479-d33500e481e0.png)

It would be nice to be able to filter testing classes based on name, by typing it somewhere.

**Comment by bitwes** [comment]
7.3.0 added a lot of  features to the in-editor Gut Panel (introduced in 7.2.0).  If you are running your tests from Godot then this will probably make this issue obsolete.  If you are however running tests on other devices and such, then this would be useful.  Let me know what you think.

**Comment by db0** [comment]
Noice. I'll check it out asap

**Comment by db0** [comment]
Alright, just tested. This works for my purposes. I can individually run the tests I need by navigating to their script and using the GUT tab below. During CI I anyway run all tests so I don't need filters.

Thanks for the great work!
