### ISSUE TITLE
Breakpoints in vscode with godot-tools don't seem to be recognized

### ISSUE THREAD

**Issue by 3ter** [bitwes/Gut#351]
## Reproduce the issue
- Take any test and add a breakpoint in vscode
- Run using `run current script`
- Expected: halt on breakpoint
- Result: Test runs through without a break

## Additional info
In the Godot editor with the `gut` console breakpoints work as expected.
Breakpoints in vscode work as expected as well.

Tests run with the following commandline and with the default config:
`"/var/lib/flatpak/exports/bin/org.godotengine.Godot" -s res://addons/gut/gut_cmdln.gd  -d  -gselect=test_main_scene.gd`

```
{
    "dirs": [
        "res://test/"
    ],
    "include_subdirs": true,
    "ignore_pause": true,
    "log_level": 2,
    "should_exit": false,
    "should_maximize": true
}
```

Godot version:  3.4.4
GUT version:  7.3.0

**Comment by bitwes** [comment]
I didn't know break points worked in VSCode, or the debugger for that matter.  I've been slumming it up with print statements or running from Godot to use the debugger.

This will take some research.  Right now the extension is a down and dirty wrapper around the CLI for GUT.  I'm not sure what kind of magic is involved in launching Godot and connecting the debugger to VSCode.  This would be great to have though.

**Comment by 3ter** [comment]
Yeah, the vscode extension has been updated recently that's why I just made the switch back to using it again as the default editor 😉.

Thanks for considering the request!

**Comment by bitwes** [comment]
Closing this out since this is related to the extension and we have bitwes/gut-extension#17 to capture this.

**Comment by bitwes** [comment]
GUT will need to be altered to work with the debugger.  This will keep track of the changes that need to be made as I discover them:
* CLI needs an argument to indicate it is being run through the debugger
  * terminal output should be disabled
  * console output should be enabled
  * when running a single test GUT needs to yield for a frame or two or debugger hangs before exit.  Does not appear to happen when more than one test runs.  Could just yield a bit regardless just to be safe.

**Comment by bitwes** [comment]
This has been implemented.
