### ISSUE TITLE
GUT panel not showing in the editor

### ISSUE THREAD

**Issue by senshellshark** [bitwes/Gut#355]
Using Godot v3.4.4.stable.official and installed from the AssetLib Gut v7.3.0

Down where the Output and Debugger is there is no GUT panel. Is there perhaps a step I am missing in installation or is this a bug? The gut node also doesn't show when searching for it in the Create New Node popup.

**Comment by bitwes** [comment]
You probably need to activate the plugin.  Check that in the plugins tab of
0roject settings.

**Comment by senshellshark** [comment]
My first time using a plugin and I didn't know I had to also enable it after installing. It appears to be working now!

Thanks!
