### ISSUE TITLE
Question: how can I stop Gut from opening a window when running tests from command line?

### ISSUE THREAD

**Issue by yudi-azvd** [bitwes/Gut#357]
Sorry if this question has been made already. I went through several issues but couldn't find what i'm looking for.

The tests run fine in the terminal/command line, just like the guide says. But it quickly opens and closes a window with the same results printed in the terminal. Even though it happens fast, it's a little annoying when exercising TDD. 

Is this intended? How can I disable this behavior?

I'm using the command `gut -gselect=test_example.gd` and gut is the following alias

```
alias gut='godot --debug-collisions --path $PWD -d -s addons/gut/gut_cmdln.gd'
```

My config file (almost equal to the one from the wiki)

```json
{
  "dirs": [
    "res://test/"
  ],
  "double_strategy": "partial",
  "ignore_pause": false,
  "include_subdirs": true,
  "inner_class": "",
  "log_level": 3,
  "opacity": 100,
  "prefix": "test_",
  "selected": "",
  "should_exit": true,
  "should_maximize": true,
  "suffix": ".gd",
  "tests": [],
  "unit_test_name": ""
}
```

**Comment by bitwes** [comment]
I haven't tried it, but I think if you add Godot's "no window" command line
option, it will hide the window.  --no-window.

**Comment by yudi-azvd** [comment]
Thanks! it works :)
