### ISSUE TITLE
Mocking and spies

### ISSUE THREAD

**Issue by donkeybonks** [bitwes/Gut#37]
Are needed for most isolated tests.

It would be the cherry on the cake if there was a way to spin up mocks or spies and I.e. check the number of times each function is called and optionally call through (or not at all) to original implementation.

**Comment by bitwes** [comment]
I've thought about this a little bit and started to look into it but I wasn't able to come up with an obvious solution.  There's no way to dynamically change the implementation of a class (that I could find).  You can pass around function references but you can't assign it to an existing method on an instance.  The best idea I could come up with was to write a class that inherits from another class and auto-magically implements methods you want to mock.

I'd welcome any other ideas if anyone has them.  Does anyone know how this is accomplished in other languages that don't allow dynamically setting methods on objects?

**Comment by donkeybonks** [comment]
Good point, I’ll see how the Google mocking tools for c++ does it and report back.

Perhaps someone could write a GDNative extension that actually plays with the guts of the vm.

**Comment by donkeybonks** [comment]
gTest mocking is macro based and requires static interfaces. GDScript really should be able to do this native .. I’ll poke around in the VM and see what’s possible.

**Comment by bitwes** [comment]
I think I might have a lead on an approach.  For the case of mocking I was able to take a script and make another one of it where all the methods were stubbed.  

My idea as of now is that you would tell Gut that you wanted to make a TestObject (name pending).  It would create a new version of the script in some temp dir.  You could use what I've done to stub any method you want.  I'd also remove all calls to `load` and `preload` and make them return a mocked class that was dynamically generated.

Here's where I'm experimenting https://github.com/bitwes/DynamicProgram

**Comment by bitwes** [comment]
Mocks and stubs have been implemented.  Spies to come later.
