### ISSUE TITLE
Typo on parameterized test summary: 'paramters'

### ISSUE THREAD

**Issue by Xiphereal** [bitwes/Gut#371]
Hi! 

I really appreciate the effort on this addon. Thanks to all the contributors :)

I think there's a typo here, were it says 'paramters' instead of 'parameters': https://github.com/bitwes/Gut/blob/86dcc705a589e5d90ac703562940a25a8a2acb70/addons/gut/test.gd#L1516 

Hope it helps!

**Comment by bitwes** [comment]
Thanks for using GUT.  Good eye, that is a typo.  Wanna fix it?

**Comment by Xiphereal** [comment]
Sure, I won't hesitate if I find the time :)

**Comment by bitwes** [comment]
I already got it.  Thanks.

**Comment by bitwes** [comment]
Released in 7.4.0
