### ISSUE TITLE
partial_double does not work on functions with preset typed parameters

### ISSUE THREAD

**Issue by dekaravanhoc** [bitwes/Gut#372]
Hi,

awesome addon!

Unfortunatly I run in an error. I have two functions:

func a( variable1 : Array, variable2 : Array = []):
   do_stuff

func b(variable : Array):
   if a(variable):
      do_stuff
      
If I call function b([0]) in a test on a partial_double, then it creates an error on the call of function a:
Invalid type in function 'a'. Cannot convert argument 2 from Nil to Array.

As it seems. The function is called with two arguments one the [0] the other Nil, which does not match the set type.

Hopefully my explanation is clear.

Thanks again for the great addon!

**Comment by bitwes** [comment]
I am very glad you like GUT, thanks.

The issue you are having has to do with how GUT defines doubles and partial
doubles.  Godot doesn't provide info about defaults so all parameters in
all doubled methods get null as a default value (even if they didn't
originally have a default).

GUT does allow you to stub default values though, there is more info here
https://github.com/bitwes/Gut/wiki/Stubbing#stubbing-method-paramter-defaults

Let me know if you have any issues getting this to work.

**Comment by dekaravanhoc** [comment]
Hey,

thanks for the fast help. The explanation makes sense and setting the defaults worked.
I just have a question there. If I just set the defaults on the function in a partial, all the tests work, but I get a ton of warnings. The method was not stubbed for the used parameters and null was returned. The method obviously did not return null or the tests would fail. So I did not really get the meaning of this warning. Stubbing with the call to super removes the warnings, but should not be necessary, as it is only a partial double. At least this is my understanding.

Thanks again!

**Comment by bitwes** [comment]
What you describe sounds like a bug.  Can you post the code for the test
and all the output?

**Comment by bitwes** [comment]
I was able to duplicate the issue and fix it.  It will be in the next release.

**Comment by bitwes** [comment]
Released in 7.4.0
