### ISSUE TITLE
Specify a test script suffix from the in-editor Plugin Controller

### ISSUE THREAD

**Issue by brisberg** [bitwes/Gut#375]
First, thanks for this cool framework!

You suggest a test [directory structure](https://github.com/bitwes/Gut/wiki/Install#setup), which is reasonable. However, I'd like to use a deviation from that:  Specifically I'd like my tests to look like `<script_name>_test.gd` so they appear next to the script they are testing.

I believe this should be possible using File Prefix and File Suffix settings.

These settings are already present in your example [config file](https://github.com/bitwes/Gut/wiki/Command-Line#config-file).
An empty `prefix` of `''` and a `suffix` of `_test.gd` will work for my purposes.

However, this does not seem to be possible for two reasons:
- The collection algorithm does not respect `suffix` in the config file (it default to using `.gd`)
- In the in-editor Gut Plugin Controller: `File_Prefix` cannot be empty, and there is no control for `File_Suffix`

I've prepared a PR which fixed both of these issues and makes such a test schema possible. Please let me know what you think.

**Comment by bitwes** [comment]
Although I don't really like this way of organizing tests, it does appear to be a way it's done in some languages/frameworks/whatever.  Since GUT is for the people and not just for the bitwes I think this would be a fine addition to GUT.
