### ISSUE TITLE
Godot 4.0 Things

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#384]
Here's a list of stuff that will have to be addressed, I tired of creating a bunch of issues.

- [x] `OS.get_unix_time()` Does not exist
- [x] `GDScriptFunctionState` changed
- [x] `list_dir_begin` changed
- [x] `JSON.print` doesn't exist, changed to `stringify`
- [x] `parse_json` doesn't exist
- [x] `if(!newone is Reference):` `Reference` does not exist.
- [x] the return of `get_data` in `JSON` has changed to be an Variant or `null`.
- [x] `.pressed` became `.button_pressed` on all buttons.
- [x] `String.find_last` does not exist anymore.
- [x] Cannot use `await` with signals added via `add_user_signal`.  You must use the `signal` keyword.
- [x] Checking a thing to see if it is null by using `!` does not work anymore.  Probably never should have been used, but I evidently did in some places to see if a dictionary was null `if(!_summary):`.
- [x] 'Invalid set index 'exit_code' (on base: 'OS') with value of type 'int'.'
- [x] The auto converter changed `remove` on a `Directory` object to `remove_at` because it thought it was an array or something.
- [x]  `str` on freed objects changed:  [Failed]:  ["[Freed Object]"] expected to equal ["[Deleted Object]"]:  
- [x] The flags for methods have changed.  The double logic has to change to use the new flags or no methods are found.
- [x] Methods local to a script are now retrieved with `get_script_method_list`, they are not in `get_method_list`.  They each appear to have a flag of `1`.  There also appears to be more information about parameters and maybe defaults than 3.x has.
- [x] Calling super's method now requires `super.` instead of just the `.`.  
- [x] Currently cannot double objects that have methods that `await`.  Since the result of the call to super is returned, Godot errors saying that the method is a coroutine and must be called with `await`.  Could just await every call to super.
- [x] `comparator.gd` and `test.gd` have to be updated to know that they can compare `TYPE_STRING` to `TYPE_STRING_NAME`.
- [x] `GDScript.reload` generates `ERROR: Attempt to open script '' resulted in error 'File not found'.` for doubles.  Created issue https://github.com/godotengine/godot/issues/65263
- [x] `inst2dict` renamed to `inst_to_dict`

**Comment by russmatney** [comment]
Maybe you've moved on from this checklist, but if it's helpful, i was meandering and just ran into this last item yesterday: ` 'Invalid set index 'exit_code' (on base: 'OS') with value of type 'int'.'`  `exit_code` is no longer an `OS` property - instead `SceneTree.quit()` now takes an int exit_code directly, defaulting to `0`.

**Comment by bitwes** [comment]
exit code was changed to be passed to `quit`.
