### ISSUE TITLE
Do you have a plan for Godot 3.0 Support?

### ISSUE THREAD

**Issue by darkyuu** [bitwes/Gut#39]
I try integrate them in my Godot 3.0 game project. it failed and throw a lot of error to console.

Thank you for advance.

**Comment by menip** [comment]
I'd love to see this in 3.0 as well.

**Comment by ViteFalcon** [comment]
Created a PR for this: https://github.com/bitwes/Gut/pull/40

**Comment by bitwes** [comment]
@ViteFalcon Testing the PR now.   I have to try and figure out the best way to maintain two codebases.  I don't think I'm going to convert the game I almost have done to 3.0 so I will need a 2.x compatible version.  I would think there would be others in the same boat.

**Comment by bitwes** [comment]
Ok, here's the plan.  I hope to get this done tonight/tomorrow.  Well done to @ViteFalcon, it's great to see the changes needed.  It looks like the GutTest repo needs some changes as well.  I'm going to create a godot30 branch for now and (I've been wanting to try this for awhile) I'm going to combine Gut and GutTests into a single repo that is 3.0 compatible.

**Comment by bitwes** [comment]
The godot30 branch should be about done now.  I still have some README work to cover the combining of GutTests and Gut repos.  Everything else seems to be working.  I've got one failing test where it isn't comparing floats cast to strings correctly but this shouldn't cause a lot of issues.  Here is the test in question:
```
func test_cast_float_eq_pass():
	gr.test.assert_eq(float('0.92'), 0.92)
	assert_pass(gr.test)
```
I need to figure out if `master` will be 3.0 or 2.x compatible (probably 3.0).  I'll make an announcement on FB and in the forums when I'm satisfied it is complete but it should be working.  Open up issues if you find any bugs. 

Thanks everyone for your patience, I've been real busy with my 2.x project and real life.  Happy Testing.

**Comment by bitwes** [comment]
I've decided to make `master` 3.0 and have a branch for 2.x.  Gut 6.0.0 has been released!
