### ISSUE TITLE
Missing prefix variables from gut.gd

### ISSUE THREAD

**Issue by georgeyw** [bitwes/Gut#393]
I am on Godot 3.4.4.stable

I installed Gut and created a new scene with only a Gut node in it. Upon running that scene, I got an error:
`Invalid set index '_test_prefix' (on base: 'Control (gut.gd)') with value of type 'String'.`
![image](https://user-images.githubusercontent.com/23727589/184581509-cfbd540d-3cfb-401f-a5b3-e4967df2c50e.png)

I was able to successfully run the Gut node scene by adding the following lines to `gut.gd`:
`var _test_prefix = ''`
`var _file_prefix = ''`

**Comment by bitwes** [comment]
Fixed in new release 7.4.1.  Forgot to test running through a scene as I've been using the cli, vscode or the new gut panel.  Try out the new Gut Panel!  Too many ways to GUT.
