### ISSUE TITLE
back/forward buttons don't enable when picking new item from list

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#4]
1. Use the arrows to go to the end of the list so that the forward button is disabled.
2.  Select an earlier script from the drop down
3.  The forward button is not enabled like it should be.

**Comment by bitwes** [comment]
fixed in 3_1 branch.

**Comment by caryoscelus** [comment]
Btw, you can close issues from commit messages (https://github.com/blog/1386-closing-issues-via-commit-messages) instead of doing it manually.
