### ISSUE TITLE
Multiple problems prevent Gut's project from running in the Godot 4 branch

### ISSUE THREAD

**Issue by aaronfranke** [bitwes/Gut#423]
I opened Gut's `project.godot` in the Godot 4 branch and ran into a lot of problems that prevent it from running.

Running the main scene causes this line to error, because it extends `'res://addons/gut/gut_to_move.gd'` which extends `Node`. I'm not sure what the intention is here, should it be a Control node because it has "move" in its name?

<img width="730" alt="Screen Shot 2022-09-13 at 12 22 21 PM" src="https://user-images.githubusercontent.com/1646875/189968745-35bbe14a-bded-48f7-aede-d5b3382ee382.png">

If I comment about the above, it fails on this line. Again I don't know what the intention is, since this method does not exist:

<img width="780" alt="Screen Shot 2022-09-13 at 12 23 27 PM" src="https://user-images.githubusercontent.com/1646875/189968807-87cc2cdd-ee77-484a-9352-d8fcbbd58d62.png">

If I try running the tests from the bottom panel, it fails with multiple errors:

<img width="850" alt="Screen Shot 2022-09-13 at 12 22 59 PM" src="https://user-images.githubusercontent.com/1646875/189968783-ffdca661-07ec-472b-a1da-986fd0b84331.png">

**Comment by bitwes** [comment]
I haven't started looking into the GUI yet.  The GUT Panel should probably be disabled for now.  I've been using the command line and VSCode plugin for all the 4.0 development (though I haven't been able to "run at cursor" with Godot 4 in VSCode yet).

**Comment by bitwes** [comment]
The panel is kinda working in godot_4 branch now.  All Panel issues are being tracked in #459
