### ISSUE TITLE
Stubbing yielded functions

### ISSUE THREAD

**Issue by dekaravanhoc** [bitwes/Gut#425]
Hey,

at the moment I cannot stub a function that is called via a yield. Therefor it would be great to be able to stub a function, so it just yields for 1 or more frames.
Or is there a solution  I am not aware of? For know I just run the function unstubbed. But I would of course like to have a clean test.

Thanks again!

**Comment by bitwes** [comment]
Can you provide some sample code?  I'm not sure I understand the problem
you are having.

**Comment by dekaravanhoc** [comment]
Shure.

```
func a():
   # does some tween animation
   yield(tween, "tween_all_completed")
   
func b():
  yield(a(), "completed")
  # does some stuff and should be tested
```

Basically stubbing func a is not possible, as the stubbed version does not return a function state object for the yield.

**Comment by bitwes** [comment]
So you want to stub `a` so that you can test `b`?  In that case I believe you can create an instance of `GDScriptFunctionState` in code and stub `a` to return that.  Then you call `b` in the test, then make the instance emit the `completed` signal.  You probably need to `yield_frames` after emitting the signal.  Something like this:
``` gdscript
func test_b():
  var dbl = double(Foo).new()
  var f_state = GDScriptFunctionState.new()
  stub(dbl, 'a').to_return(f_state)
  stub(dbl, 'b').to_call_super()
  dbl.b()
  f_state.emit('completed')
  # must yield for the signal emission to be caught by the 
  # yield in b (pretty sure at least)
  yield(yield_frames(1), YIELD)
  # assert something
```
If you cannot make a `GDScriptFunctionState` instance then anything that has a `completed` signal will work (I've used this trick in tests before)
``` gdscript
class FakeFunctionState:
  signal completed

func test_b():
  var dbl = double(Foo).new()
  var f_state = FakeFunctionState.new()
  stub(dbl, 'a').to_return(f_state)
  stub(dbl, 'b').to_call_super()
  dbl.b()
  f_state.emit('completed')
  # must yield for the signal emission to be caught by the 
  # yield in b (pretty sure at least)
  yield(yield_frames(1), YIELD)
  # assert something
```

**Comment by bitwes** [comment]
You *may* need to `yield` for more than 1 frame.  I want to say that 1 frame isn't as reliable for tests as 3 or 5 is.

**Comment by dekaravanhoc** [comment]
Ah ok. Yeah. I tried already to get a GDScriptFunctionState Object, did not work as you said. I also thought about using a fake class only with the signal. Seems easy enough.
Thanks.
