### ISSUE TITLE
Trouble returning non-primitive values

### ISSUE THREAD

**Issue by engineer-pearl** [bitwes/Gut#434]
I want to stub a method to return the color black, but it seems to be returning a Nil instead. 

The stub line in question: `stub(doubledImage,'get_pixel').to_return(Color( 0, 0, 0, 1 ))`

Error message from test: `Invalid get index 'r8' (on base 'Nil')

Is there a way to allow stubs to return non-primitive values?

**Comment by feefladder** [comment]
could you provide a minimal working example? I did not have the same problem with:
```
#get_pixel.gd
extends Node
class_name GetPixel

func get_pixel() -> Color:
    return Color(0,0,0,1)
```
# test_get_pixel.gd
extends GutTest

var get_pixel: GetPixel

func test_get_pixel_normal():
    get_pixel = partial_double(GetPixel).new()
    assert_eq(get_pixel.get_pixel(), Color(0,0,0,1))

func test_get_pixel_stubbed():
    get_pixel = double(GetPixel).new()
    stub(get_pixel, "get_pixel").to_return(Color(1,1,1,1))
    assert_eq(get_pixel.get_pixel(), Color(1,1,1,1))
```

Is the problem in the stubbing or in something else?

**Comment by bitwes** [comment]
I also could not replicate the issue using the following.  What are you doubling?
``` gdscript
extends GutTest

func test_stub_image():
    var double_img = double(Image).new()
    stub(double_img, 'get_pixel').to_return(Color(1, 0, 0))
    assert_eq(double_img.get_pixel(1, 2), Color(1, 0, 0))
```
```
res://test/unit/test_bugs/test_i434.gd
* test_stub_image
    [Passed]:  [Color(1,0,0,1)] expected to equal [Color(1,0,0,1)]:  
1/1 passed.
```

**Comment by engineer-pearl** [comment]
I've modified my code to encounter the bug. 

I'm doubling an image, which is then passed into my object so that it can be referenced by the relevant function.

Looking at it now (I've been working on different parts of the code) it looks like the issue is on something other than what I thought it was when I opened the issue.

I have a break-point in gameworld.gd line 53, where I'm able to confirm that the image object IS a double, but the return value of the function is Nil, even for the first call.

![image](https://user-images.githubusercontent.com/17389425/195211280-d1d9298f-794c-403e-b589-b3c0d52b585c.png)

![image](https://user-images.githubusercontent.com/17389425/195211143-a8ca1d82-99da-4e2f-ae17-944f225934e5.png)

https://gitlab.com/ThisLifeDevelopment/thislifegodot/-/blob/create-bug-cant-return-color/test/unit/WorldTools/test_GameWorld.gd

**Comment by bitwes** [comment]
It's been....awhile...I think I see the issue:

You are stubbing the return in `before_all`, which will only work on the first test.  All stubs are cleared between tests to make sure that stubs do not leak from test to test.  You are also stubbing an instance which is getting overwritten in the `before_each`.

Here's some ways to stub things:
```gdscript
func before_each():
    # This will stub all doubles and partial doubles of Image.get_pixel to return black.  This is
    # a class level stub that must be done before double or partial_double is called.
    stub(Image, 'get_pixel').to_return(Color.BLACK)
```
In each test (or in `before_each` if you do it after the variable is assigned), you can stub return values for specific double instances if you want to change the value returned.
```gdscript
func test_something():
    var dbl_image = double(Image).new()
    # This overwrites the black stubbed in `before_each` but only
    # for dbl_image and nothing else
    stub(dbl_image, 'get_pixel').to_return(Color.BLUE)
    # This overwrites the blue stub above when the instance is passed `(5, 5)`
    stub(dbl_image, 'get_pixel').to_return(Color.RED).when_passed(5, 5)
```

Given how stale this is, if you haven't moved on with your life yet, and this is still an issue that was not resolved with this explanation then please reopen this issue.
