### ISSUE TITLE
[Bug/Feature request] Scene export values reset when doubling

### ISSUE THREAD

**Issue by feefladder** [bitwes/Gut#436]
Title says it. When doubling a scene, the resource values of the script are reset to default values.

# steps to reproduce:

* Make a scene with a single node, attach a script and give it an export variable  
  ```
  extends Node

  export(int) var a = 1
  ```
* Set the export variable to something different in the editor, for example two
* ```
    extends GutTest

    func test_same():
        var scene = load("res://test/unit/bugs/test.tscn").instance()
        assert_eq(scene.a, 2)
        scene.free()

    func test_test():
        var scene = partial_double("res://test/unit/bugs/test.tscn").instance()
        assert_eq(scene.a, 2)
  ```
* The second test will fail

**Comment by bitwes** [comment]
Hmmm, neat.
