### ISSUE TITLE
Auto removal of children added during tests.

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#44]
The thought occurred to me that I could override `add_child` in the Test class and keep track of all children added that way.  At the end of each test I could clear the children.  I'm not sure if this would break anything for anyone.  I imagine there are some testing being done where there are children added globally for the life of the script.  This might be bad practice so maybe I shouldn't care.  I could also implement a wrapper method that could be used to it was explicitly clear what was going on.  Maybe `add_test_child`.  I don't like that name...thoughts?

I might also be able to accomplish this with an `add_child` with a flag to do the removal or not.  Probably default it to off.

**Comment by Xrayez** [comment]
I always wondered where to add child to. So far I just run `add_child` from within the test method, that of course results in nodes placed on top of gut window :)

So I started to `get_tree().get_root().add_child()` because of that.

With GUT children are homeless now!

**Comment by bitwes** [comment]
Usually when I need to use `add_child` I'll do it in the `before_each` and then free it in the `after_each`.  I don't particularly like that they show up on the window, but if not on the window then they show up behind the window and you can't see them (hence the opacity setting).  

Maybe Gut should have an empty Node child that things could be added to and then auto-released.  
There would have to be a parameter to release it after the test or after the script.  I'm not sure how that pans out between 2d and 3d.  I think Node might be ok.

**Comment by Xrayez** [comment]
Yeah I think Node should be alright and it will not let children inherit parent's transform (which is good as for a simple node container).

**Comment by bitwes** [comment]
Version 7.0.0 has added `autofree`, `autoqfree`, add_child_autofree`, and `add_child_auotqfree` which addresses this.  I'll close this out when 7.0.0 goes live.

**Comment by bitwes** [comment]
Implemented in 7.0.0.  See the Memory Management wiki page for more information.
