### ISSUE TITLE
[Godot4] [ParseError] in res://addons/gut/gui/gut_config_gui.gd

### ISSUE THREAD

**Issue by theludovyc** [bitwes/Gut#443]
Parse Error: Cannot call non-static function "dir_exists()" on the class "DirAccess" directly. Make an instance instead.

https://github.com/bitwes/Gut/blob/5f18bb972677c0368993d9fcb54db7e25c367810/addons/gut/gui/gut_config_gui.gd#L276

Is path absolute ? If yes you can use DirAccess.dir_exists_absolute(path)

Can I make a PR ?

**Comment by bitwes** [comment]
I have not started trying to port the GUI yet, there are probably a ton of issues.  In this case, will be one of the configured directories for where your tests are.  So it should start with `res://`...so yes, it should be absolute.

**Comment by theludovyc** [comment]
Okay, I will make a PR this afternoon for it :)

**Comment by bitwes** [comment]
Fixed by PR
