### ISSUE TITLE
[Godot 4] [ParseError] in res://addons/gut/gui/GutBottomPanel.gd

### ISSUE THREAD

**Issue by theludovyc** [bitwes/Gut#444]
Invalid call. Nonexistent function 'new' in base 'GDScript'.

https://github.com/bitwes/Gut/blob/5f18bb972677c0368993d9fcb54db7e25c367810/addons/gut/gui/GutBottomPanel.gd#L57

I do not know how to resolve this. But if you explain me, I can make a PR :) !

**Comment by bitwes** [comment]
I have not started trying to port the GUI yet, there are probably a ton of issues.  I"m not sure what is going on here.  Probably due to something else being broken and `GutConfigGui` not being valid at this point in the code.

**Comment by theludovyc** [comment]
Okay, I see :)
