### ISSUE TITLE
[Godot 4] [ParseError] in res://addons/gut/gui/RunAtCursor.gd

### ISSUE THREAD

**Issue by theludovyc** [bitwes/Gut#445]
res://addons/gut/gui/RunAtCursor.gd:111 - Invalid set index 'hint_tooltip' (on base: 'Button') with value of type 'String'.

https://github.com/bitwes/Gut/blob/5f18bb972677c0368993d9fcb54db7e25c367810/addons/gut/gui/RunAtCursor.gd#L111

I do not know how to resolve this. But if you explain me, I can make a PR :) !

**Comment by bitwes** [comment]
I have not started trying to port the GUI yet, there are probably a ton of issues.  This particular issue probably has to do with them renaming `hint_tooltip` to something else.

**Comment by theludovyc** [comment]
Okay, I will investigate :)
