### ISSUE TITLE
Request: A function to only stub the nth occurence of a function.

### ISSUE THREAD

**Issue by lars-hoeck** [bitwes/Gut#457]
I have a while(!array.empty) loop and want it to run 1 time.
So i stubbed the function and returned false.
In the while loop I would call another function, which would remove elements the array.

So my problem is, that i want to test only this function, but i can't do that because i have an infinite running while loop.
I need a stub with a parameter which defines the call_amount at which this function should be stubbed.

```
func a(array):
    while(!array.empty):
        call_methode_to_decrease_amount_of_array_elements(array)

func call_methode_to_decrease_amount_of_array_elements(array):
    array.remove(0)
```

**Comment by teekennedy** [comment]
Perhaps you could move the `!array.empty` condition in your while loop to a function and then stub that?

(untested) ex:

```gdscript
func a(array):
    while(not_empty(array)):
        call_methode_to_decrease_amount_of_array_elements(array)

func call_methode_to_decrease_amount_of_array_elements(array):
    array.remove(0)

func not_empty(array):
    return !array.empty

# stubbed version
var not_empty_call_count = 0
func not_empty_stub(array):
    not_empty_call_count += 1
    return not_empty_call_count > 1
```

**Comment by bitwes** [comment]
I'm having a hard time getting my head around this example.  It looks like both methods are in the same class. Why are you doubling the class under test?

Also, if `call_methode_to_decrease_amount_of_array_elements` is a "private" method, then it should be stubbed to call super while testing `a`.  You don't want to test the implementation of private methods so it should be fine to have that method call super.

If `call_methode_to_decrease_amount_of_array_elements` is a "public" method, then I would test it thoroughly and still have it stubbed to call super when testing `a`.

**Comment by bitwes** [comment]
Reopen if you have more feedback about the feature.
