### ISSUE TITLE
Godot 4 GUT Panel Issues

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#459]
The panel is 80% working now.  There's still some bugs/polish needed but you can run the suite/script/inner-class/single-test and the Results Tree is now working as it should.

## General
- [x] Running based on cursor position is broke currently
- [x] Sync clicks toggle for Text box and script does not appear to work
- [x] Setting Runner Font not working.
- [x] None of the tooltips appear to be showing.

## Shortcuts
- [x] Keyboard Shortcuts cannot be set.
- [x] Shortcuts dialog is tiny at first, should not be resizable.

## Settings
- [x] Post-Run and Pre-Run Hook open file buttons don't work
- [x] Settings panel is tiny, should have a minimum size when shown.

## Output Panel
- [x] Cannot copy Output Text.
- [x] Text output search does not work.
- [x] Syntax highlighting toggle for the Text Output is reversed.
- [x] Setting font for Output text not working.
- [x] Setting font size for Output text not working.
- [ ] <s>Text colors needs some work.</s>

## Results Tree
- [x] Script entry should include counts of all Inner Classes.
- [x] Results should only include Inner Classes that were run.
- [x] Clicking on method names in the Test Result Tree takes you to the top of the file.
- [x] Green indicator for Test Result Tree is missing
- [x] Including passed tests toggle takes 3 clicks to enable.
- [x] Clicking on a test (and probably a inner class) for a file that is not open will take you to the top of the file in the editor.  If you click an assert with a line number then it will go to the line.  Once the file is open, clicking on nodes in the tree acts normally.  This is a strong indicator that an `await` is probably needed between opening the file and searching for text.  Especially since an assert with a line number always works.

**Comment by mbrealm** [comment]
This is very encouraging - thanks for your work on it!

After previously removing GUT from my v4 project experimental port, I will re-add it and see if I can get back to running tests!
