### ISSUE TITLE
[Godot 4 RC5] Parser errors in GUT code

### ISSUE THREAD

**Issue by mbrealm** [bitwes/Gut#461]
I encountered the following errors trying to run the `godot_4` branch @ 3a053bb4e1fb5e24b15ed3b8af13691b358f62cc with a project and Godot 4 RC5 (on Linux x86_64).

Initially I saw them after installing GUT into my project according to normal instructions (`addons/gut/` folder) and attempting to run as I have in the GUI on Godot 3.5 .

1. First error: 

   res://addons/gut/gut.gd:475: `'Parser Error: "_utils" is a variable but does not contain a type.' `

   I circumvented by removing the check for instance of Hook_Script just to see if this might be the only error.
   However, GUT encountered a subsequent error:

2. Second error:

   res://addons/gut/test.gd:739:  `'Parser Error: Could not find type "a_class" in the current scope.'`

   I did not know what caused this, so I stopped trying to monkey-patch GUT here.

I then set up the command line wrapper. It replicated the parse errors.
They also reproduced while running GUT's own tests via command line (in checkout of `godot_4` branch as above).

I have not tried running the new GUT with previous Godot 4 release candidates.

**Comment by bitwes** [comment]
They changed how the is keyword works in rc3.  I just found this
yesterday.  It seems odd they would change a keyword THIS much in a release
candidate...but they did.  I should have this fixed today or tomorrow
depending how much this broke.

FYI if u want to use is with a variable you now have to use
is_instance_of(inst, Your script).

**Comment by bitwes** [comment]
Here's the bug I opened:  https://github.com/godotengine/godot/issues/73906#event-8607563417.

If you click through all the related and "fixed by" links it appears the original issue was using `is` with `array[int]`.

There was only 4 lines of code that had to change, full suite runs now.  Changes have been pushed to godot_4 branch.
