### ISSUE TITLE
[Godot 4 RC5] Nonexistent function 'get_logger' when trying to run cmdline runner

### ISSUE THREAD

**Issue by mbrealm** [bitwes/Gut#462]
With [a recent fix](https://github.com/bitwes/Gut/commit/981a6aba323dc3ab8bd2dc634156133fcd0cab87) on `godot_4` branch, my tests run OK in GUI. Thanks!

But running on command line hits a problem in the runner script:

`home/user/my_godot_project $ godot4 -d -s --path $PWD addons/gut/gut_cmdln.gd`

...

```
Debugger Break, Reason: 'Invalid call. Nonexistent function 'get_logger' in base 'Node ()'.'
*Frame 0 - res://addons/gut/gut_cmdln.gd:287 in function '_on_tests_finished'
```

Note: This error was only encountered when running in my own project.

Subsequently, I tested a bit with running the unit tests of latest GUT `godot_4` from command line.
This worked, provided I had opened (imported) the GUT project using Godot 4, as mentioned in the documentation.
So on GUT itself, the "get_logger" call isn't a problem.

Running from command line within my own project isn't a priority for me, I consider this issue non-urgent.

**Comment by mbrealm** [comment]
I can confirm the error is still there with Godot 4 RC6.

**Comment by bitwes** [comment]
Fixed it.  I missed changing a `get_logger` line.  The one I missed was only called if you didn't have any directories configured in the `.gutconfig.json`.  The fix is in `godot_4`, but you can also fix it by adding a `.gutconfig.json` with directories configured.
