### ISSUE TITLE
Install for Godot 4 (no version in asset library)

### ISSUE THREAD

**Issue by hsandt** [bitwes/Gut#472]
More a discussion / tip than an issue

I noticed the Godot 4 version has not been released to the asset library. I suppose you are waiting to get a more stable version?

For now, for the godot_4 branch, we have to follow https://github.com/bitwes/Gut/wiki/Install > Download and install section, or alternatively:
a. clone the repo and copy the addons/godot folder into your project's own addons/ folder. When the repo is updated, you need to git pull and copy again.
b. clone the repo and add a symlink to the addons/godot folder into your project's own addons/ folder (thanks to https://www.reddit.com/r/godot/comments/ywdhqs/how_do_you_manage_assetlib_addons_with_git_is/ for the idea). When the repo is updated, you just need to git pull.

These alternative ways could be added to the wiki (but they are generic to all add-on repositories, really).

Too bad that the project structure doesn't allow us to directly add the add-on as a submodule repository... and I don't know an easy way to clone a subtree. This is a known issue and not specific to this add-on though (https://github.com/godotengine/godot-proposals/issues/62, https://github.com/godotengine/godot-proposals/issues/554, https://github.com/godotengine/godot-proposals/issues/1205)

**Comment by bitwes** [comment]
You can download the zip of the `godot_4` branch which is the same thing the Asset Library does.  It only contains the addons folder.  The submission for Godot 4 is getting final touches and should be submitted this weekend.

Here's the link https://github.com/bitwes/Gut/archive/refs/heads/godot_4.zip

**Comment by bitwes** [comment]
Godot 9.0.1 has been released and can be found in the Asset Library!
