### ISSUE TITLE
Font size of log view is too big，not consistent with the editor theme.

### ISSUE THREAD

**Issue by kaluluosi** [bitwes/Gut#478]
![image](https://user-images.githubusercontent.com/1620585/226153126-29b38d65-f89f-4cbe-9e80-0c72965c0e17.png)

**Comment by bitwes** [comment]
You can change the font size in the settings.  
<img width="613" alt="image" src="https://user-images.githubusercontent.com/1156520/226251344-7cb09d53-42d7-449b-bbda-6422543d84ec.png">

**Comment by kaluluosi** [comment]
I mean why not just read the editor theme font size as the default size?
