### ISSUE TITLE
Make the README into a wiki

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#48]
I think the README has gotten big enough and a Github wiki might make things more manageable.

**Comment by ivanskodje** [comment]
if the README hasn't gotten big enough, wouldn't that just mean that there is currently no need to turn it into a wiki? 👍

**Comment by bitwes** [comment]
Good catch, heh.  I changed it to "has".

**Comment by bitwes** [comment]
Readme is now a wiki.
