### ISSUE TITLE
Godot4 GUT No Main Loop Ready On Scene Tests

### ISSUE THREAD

**Issue by TheKingOfLettuce** [bitwes/Gut#497]
Whenever I attempt to run tests via scene, I hit the following error 
`ERROR: No Main Loop Yet`
This is with my test script as my main node and happens whenever I hit play. It seems when `utils.gd` gets instantiated in the `GutTest` script, the Main Loop isnt ready yet which sets the root node to null.

Also, the documentation says something about how you can configure GUT settings on that node in the inspector, yet when I add a GUT node, there is nothing to configure in the inspector.

Am I doing something wrong?

**Comment by TheKingOfLettuce** [comment]
Duh! Just read the Godot4 documentation that talks about how Gut control was removed. Looks like I was doing something wrong after all.

**Comment by bitwes** [comment]
FYI, the `godot_4` branch (unreleased) has a new feature to make running from scenes easier.  See:
https://github.com/bitwes/Gut/blob/godot_4/wiki/Running-On-Devices.md
