### ISSUE TITLE
Help: Assert Functions for Test Functions

### ISSUE THREAD

**Issue by cramsey86** [bitwes/Gut#500]
I am really enjoying GUT and for the most part its intuitiveness as I am very new to writing unit tests.

There is one thing I am not sure how to do though that is causing me issues and I feel will continue to cause larger issues down the road.

If I have a test called:

```Python
func test_classic_archer():
    var _champion_enum_id = Champion.Id.CLASSIC_ARCHER

    _scene_champion.init(
	_champion_enum_id,	# _enum_id : Champion.Id
    )

## HOW DO I MAKE A FUNCTION FOR THE FOLLOWING ##

    # Test Core Stats Values
    var _int_core_stat_armor_value = 0
    var _int_core_stat_attack_magic_value = 0
    var _int_core_stat_attack_melee_value = 0
    var _int_core_stat_attack_range_value = 2
    var _int_core_stat_health_value = 10

    ## ATTACK_MAGIC
    assert_eq(
		_scene_champion.int_core_stat_attack_magic_value,
		_int_core_stat_attack_magic_value,
		"Value for 'int_core_stat_attack_magic_value' should be '" + \
			str(_int_core_stat_attack_magic_value) + "'")
    ## ATTACK_MELEE
    assert_eq(
		_scene_champion.int_core_stat_attack_melee_value,
		_int_core_stat_attack_melee_value,
		"Value for 'int_core_stat_attack_melee_value' should be '" + \
			str(_int_core_stat_attack_melee_value) + "'")
    ## ATTACK_RANGE
    assert_eq(
		_scene_champion.int_core_stat_attack_range_value,
		_int_core_stat_attack_range_value,
		"Value for 'int_core_stat_attack_range_value' should be '" + \
			str(_int_core_stat_attack_range_value) + "'")
    ## HEALTH
    assert_eq(
		_scene_champion.int_core_stat_health_value,
		_int_core_stat_health_value,
		"Value for 'int_core_stat_health_value' should be '" + \
			str(_int_core_stat_health_value) + "'")
```

and I want to be able to have tests for my other champions, am I able to turn the parts that I am testing into their own function so I can repeat my tests logic without needing to have this same code exist in every one of my tests?

I will totally admit that I may be thinking about this incorrectly as well.

Would appreciate any help.

**Comment by cramsey86** [comment]
I think I figured out my flaw.

Rather than test each individual outcome in a separate function, I am creating a dictionary of those different outcomes and then looping against them to perform the same tests against each one.

**Comment by bitwes** [comment]
Hey @cramsey86, 

This is a good question so I'm going to answer this even though you closed it.  The purest TDD approach to this would be something like:
* have a test script for each champion type
* have a single test per property you want to test
* have a single assert in each test verifying the default value.

That is a bit tedious, but it's the TDD way.  Keep your tests small, simple, easy to understand, and as atomic as possible. 
 Only test "one" thing.  If that doesn't appeal to you then there's a couple different ways you could handle this in a more TDD fashion.  After all, it's better to have tests that aren't "perfect" than no tests at all.  The only rule you should NEVER break is that you should always write a failing test first.  If you don't do this, then you don't know if the code you wrote actually did what you thought it did.

## Create a reusable custom assert
You could create a function that performs asserts on something that is passed in.  This would allow you to create a "custom test" that performs specific checks on a thing.  You could put this in a script 
```gdscript
func assert_all_default_properties_of_a_champion(champ):
    assert_eq(champ. int_core_stat_attack_magic_value, 0, 'attack magic')
    ...

func test_archer_properties():
    var champ = _scene_champion.init(
	_champion_enum_id,	# _enum_id : Champion.Id
    )
    assert_all_default_properties_of_a_champion(champ)
```

## Parameterized tests (probably the best choice)
You could also create a parameterized test that GUT will run multiple times with different values (more info in the wiki)
```gdscript
# this would test all the properties of all the champions you pass in.
var some_list_you_made_of_champion_scenes = [champ1, champ2, champ3, champ4]
func assert_all_champions_have_default_values(champ = use_parameters(some_list_you_made_of_champion_scenes)):
    assert_eq(champ. int_core_stat_attack_magic_value, 0, 'attack magic')
    ....

# This would test the attack magic for all the champions, allowing you to specify different default values
# for each champion (this is a better approach than testing all properties in one method).
var attack_magic_champs = [ [archer.new(), 4], [wizard.new(), 10], [warrior.new(), 1]]
func assert_default_magic_attack_values(champ_value_pair = use_parameters(attack_magic_champs)):
    assert_eq(champ_value_pair[0].int_core_stat_attack_magic_value, champ_value_pair[1], champ_value_pair[0].get_champion_name_or_something_identifiable_for_output_reasons())
```

## TDD Stuff
I would discourage you from using the solution you mentioned.  When writing tests you should make the tests as simple and as small as possible, and should avoid any logic.  Some good programming practices such as "do not  repeat yourself" shouldn't be used with tests.  It's better to be verbose and easy to understand, even if you end up typing a lot of the same thing over again.

That doesn't mean you can't reuse things, just that you shouldn't by default.  Another part of unit tests is that you should test "one" thing.  This usually means one assert per test, but doesn't have to mean that.  Sometimes it gets a difficult to verify "one" thing with a single assert.  These properties are a good example of deciding what "one" thing is.  Technically you should have one test per property, but that does feel like busy work.


## Some style tips
Here's some style tips that you can take 'em or leave 'em.  

### Variable names
When making local variables in a function, don't use `_`.  Per the GDScript style guide, `_` should be used for private class level variables. It's what all the cool kids do, so this is one time it's ok to succumb to peer pressure.  Plus it makes your code a lot easier for others to understand (I was confused for a bit).

### Assert message text
I noticed you had a lot of text in the message for your asserts.  GUT will print out the "got" and "expected" values.  So you can save some text by just putting the thing the assert is testing.
```gdscript
# instead of 
    assert_eq(
		_scene_champion.int_core_stat_attack_magic_value,
		_int_core_stat_attack_magic_value,
		"Value for 'int_core_stat_attack_magic_value' should be '" + \
			str(_int_core_stat_attack_magic_value) + "'")
# you can get same info with:
    assert_eq(
		_scene_champion.int_core_stat_attack_magic_value,
		_int_core_stat_attack_magic_value,
                "int_core_stat_attack_magic_value")

# If you only have a single assert in a test then you don't have to add text.
# If this test fails, you know the default attack magic value is wrong based
# on the name of the test.
func test_archer_default_attack_magic():
    assert_eq(
		_scene_champion.int_core_stat_attack_magic_value,
		_int_core_stat_attack_magic_value,
                "int_core_stat_attack_magic_value")
```

That's about all I can think of now.  If you don't have any more questions feel free to re-close this.

**Comment by cramsey86** [comment]
Wow! @bitwes thank you so much for taking the time to respond with all this great information (going above and beyond my initial question)!

The examples above are exactly what I was looking for, and now that I see it, I feel dumb for not just creating a function like regular, not sure if I thought it "had" to be one of the GUT special functions, or what was going through my head.

I am going to work on creating the Parameterized Test second example that you gave.

Again so appreciative of this insight!
