### ISSUE TITLE
Can't test methods using get_node / $NodeName

### ISSUE THREAD

**Issue by ratala321** [bitwes/Gut#504]
If a method use get_node() / $NodeName, the return value will always be null when running a test.

It is also a problem when a class is using an export variable.

**Comment by bitwes** [comment]
You probably need to call add_child on the object inside the test.  Also
look at GUT's add_child_autofree and add_child_autoqfree methods.

Node paths only work once an object is in the tree.

**Comment by bitwes** [comment]
Reopen this if that wasn't the problem.

**Comment by ratala321** [comment]
Sorry for the delay, I didn't achieve the result expected using your advice, but it may be due to the lack of knowledge of godot on my part. 

Thank you for your help !

**Comment by bitwes** [comment]
Paste your code and I'll have a look.

**Comment by ratala321** [comment]
I recently learned about "mocking" and I wasn't doing it in a proper way. The code was also referring to external objects that weren't added using "add_child". Basically, I was trying to get_node("nodeName") on a node that wasn't added using add_child before. 

Sorry for the inconvenience it may have caused and thank you for your time and dedication.
