### ISSUE TITLE
Can not create / use Partial-Doubles

### ISSUE THREAD

**Issue by TomCoursow** [bitwes/Gut#513]
Hi,

I am currently evaluating GUT and don't know if I found a bug or if I use the api in a wrong way...
I realy looked a lot at the documentation but it seems not to work that way...

I tried to create a simple test which should use simulate a scene (so call _process() ) and then assert that a certain function is or is not called.
But I can not get this to work...

- The asserts want to work with a double
- But when I create a partial double from a packed scene and instantiate it (to add it to the tree for simulation)
  - The resulting node/s seem not to be a double at all
  - Therefore the assert will not work
- It also seems like there is no ``instance()`` method which is stated in the docs... So I used instantiate() instead...

Test Code:
```
extends GutTest

func test_player_with_disabled_input_can_not_move():
	var testSceneRes = load("res://test/integration/Integration_Tests.tscn")
	var testScene = partial_double(testSceneRes).instantiate()
	add_child_autofree(testScene)
	var player := testScene.get_node("Player") as Player
	player.inputEnabled = false
	gut.simulate(testScene, 5, 0.1)
	assert_not_called(player, "move_or_slide") # <<-- You must pass a doubled instance to assert_not_called. Check the wiki for info on using double.
	# Also even "testScene" seems not to be a double...

func test_player_with_enabled_input_calls_move():
	var testSceneRes = load("res://test/integration/Integration_Tests.tscn")
	var testScene = partial_double(testSceneRes).instance() # <<-- Invalid call. Nonexistent function 'instance' in base 'PackedScene (PackedSceneDouble)'.
	add_child_autofree(testScene)
	var player := testScene.get_node("Player") as Player
	player.inputEnabled = true
	gut.simulate(testScene, 5, 0.1)
	assert_not_called(testScene, "move_or_slide")
```

- OS: Linux
- Godot: 4.1.1
- GUT: 9.1.0

**Comment by bitwes** [comment]
Double and partial_double do not double everything in a scene, just that's
scene.  So player is not a double.  You could create a double of player and
stub get_node to return it.

**Comment by bitwes** [comment]
Also, in Godot 4 it is instantiate, in Godot 3 it is instance.

**Comment by bitwes** [comment]
If you are still having issues reopen.
