### ISSUE TITLE
Config File "res://.gut_editor_config.json" does not exist.

### ISSUE THREAD

**Issue by Darkmatter43** [bitwes/Gut#516]
I installed GUT using godot's AssetLib
After installing and enabling the plugin, I receive the following message:
"Config File "res://.gut_editor_config.json" does not exist."

I cannot see the proper GUT node to use for testing.
I only see GutUtils and GutTest nodes - neither of which have the properties in the inspector nor do I see anything in my scene.

![image](https://github.com/bitwes/Gut/assets/89175435/bd87e6de-4c53-4323-adbf-fc2b4b22b5e5)

I notice that I do not see that .gut_editor_config.json file in the root of the project here on GitHub. Have I missed something during installation?

**Comment by bitwes** [comment]
The gut node is the old old way.  The new way adds the gut tab to the
bottom panel that has controls for running tests without having to make a
node.  The config file should be created for you.  Maybe 8t errors on the
first install, but it should make it for you after that, I know it makes it
after setting any settings in the settings panel of the gut tab.

What version of Godot are you using?

**Comment by Darkmatter43** [comment]
Apologies - and thank you for the clear answer. I must have looked at old documentation or gotten confused somewhere. I found the editor and was able to run tests as expected. Thanks again!
