### ISSUE TITLE
How to run the tests to pass a gitlab pipeline? 

### ISSUE THREAD

**Issue by Dracks** [bitwes/Gut#520]
Hello, 

I'm trying to make a pipeline work in gitlab, to run the tests in godot, but I'm not getting it to work. 

Seems that I get it working adding the folder ".godot" but this folder contains a lot of files that every time I start godot get modifyied, which I don't wish to have in the git, when I remove the folder or part of it, simply crashes with lots of "Failed loading resource..."

Any Idea What I can do to have this fixed? Can you add some documentation in the wiki of gut about how to run it on pipelines? 

[edit]
Seems that only adding this file into git, works `godot/.godot/global_script_class_cache.cfg` and with a cache imported files
[/edit]

Thanks!

**Comment by Dracks** [comment]
yeah, thanks , I get it working, keeping some of the files internal of .godot, I tried to run the godot --exit (I think is called) to run it and exit, but was not enough to rebuild all the stuff... Currently I've got the gut working in the pipeline, but now it's been days since I touched that for the last time.

**Comment by m21-cerutti** [comment]
Seems related to this issue https://github.com/godotengine/godot/issues/77478
 On my own pipeline it prevents GUT from working on the CI, the only workaround is the .godot/global_script_class_cache.cfg indeed to remove from the gitignore.
 I have reproduce it locally too if it's the first launch of godot.
 
![image](https://github.com/bitwes/Gut/assets/23432929/793d6516-f7d9-4fd8-9de2-7eadec173946)

https://gitlab.com/neitherlands/engine/-/blame/feature/build-system-local/build/Build.cs?ref_type=heads#L153

**Comment by Dracks** [comment]
the best is to run the godot head-less, and ask to quit after more than 50 cicles, here https://github.com/Codename-Recon/Codename-Recon/blob/master/.github/workflows/client-exports.yaml#L38 we put 200, and is working fine (this will allow godot to regenerate the file)
