### ISSUE TITLE
Is a better "assert_almost_eq" function possible ?

### ISSUE THREAD

**Issue by navy-cap-echo** [bitwes/Gut#523]
For information, I tested the following code with version v4.1.3.stable.official [f06b6836a] 

```
extends GutTest

func test_Gut() :
  var cos60 : float = cos( deg_to_rad( 60.0 ) )
  
  assert_almost_eq( 0.5 , 0.501 , 0.001 , "Test 1" ) 
  assert_almost_eq( 0.5 , 0.500 , 0.001 , "Test 2" ) 
  assert_almost_eq( 0.5 , 0.499 , 0.001 , "Test 3" ) 

  # to prove that cos60 is almost equal to 0.5
  assert_almost_eq( cos60 , 0.5 , 0.001 , "Test 10" ) 
  assert_almost_eq( cos60 , 0.5 , 0.0000000001, "Test 11" ) 

  assert_almost_eq( cos60 , 0.501 , 0.001 , "Test 21" )  
  assert_almost_eq( cos60 , 0.500 , 0.001 , "Test 22" )  
  assert_almost_eq( cos60 , 0.499 , 0.001 , "Test 23" ) # Fail !!!
```
All tests should pass, but test 23 doesn't !

![gut_test_fail](https://github.com/bitwes/Gut/assets/55918951/01d73cff-1287-41f2-b47b-433fcd7fce32)

I tried to dig a little in test.gd, in the ```function func _is_almost_eq(got, expected, error_interval) -> bool``` :
- The problem is line 315 : ```elif(got >= (expected - error_interval) and got <= (expected + error_interval)):```
- The second part ```got <= (expected + error_interval)``` returns false (I noticed this by separating the logical results into 2 boolean variables)

By printing the value of the ```cos60``` variable, with an higher number of digits, we can see the problem : 
-    ```print( "%.20f" % cos60 )``` give us ```0.50000000000000011000```
-    Value which is obviously greater than ```0.499+0.001=0.5```
-   The floating-point approximation in all its glory...
 
I tried some ideas to get rid, in part, of the floating point approximation issue :
- Conversion to integer (Problems arise when values exceed the integer range...)
- Conversion to String :
```
# Deliberately not simplified and not optimal function !
func is_almost_eq(a : float , b : float, tol : float = 1e-09 ) -> bool :
  var digits : int = int( abs(log(tol)/log(10.0)) ) + 1
  var sa  : String = "%.0*f" % [digits,a]
  var sbm : String = "%.0*f" % [digits,b-tol]
  var sb  : String = "%.0*f" % [digits,b    ]
  var sbp : String = "%.0*f" % [digits,b+tol]
  var result : bool = ( sa >= sbm ) and ( sa <= sbp )
  prints( "%s ≅ %s [%s..%s] %s" % [sa,sb,sbm,sbp,result] )
  return result
```
This function worked in my case, giving me the expected results.
```
  print( "\n%.20f" % cos60 )
  
  var epsilon : float = 0.001 
  print( "\n%.20f" % epsilon )
  is_almost_eq(cos60, 0.5  + epsilon, epsilon )
  is_almost_eq(cos60, 0.5           , epsilon )
  is_almost_eq(cos60, 0.5  - epsilon, epsilon )

  epsilon = 0.003
  print( "\n%.20f" % epsilon )
  is_almost_eq(cos60, 0.5  + epsilon, epsilon )
  is_almost_eq(cos60, 0.5           , epsilon )
  is_almost_eq(cos60, 0.5  - epsilon, epsilon )

  epsilon = 1e-12 # 0.000000000001
  print( "\n%.20f" % epsilon )
  is_almost_eq(cos60, 0.5  + epsilon, epsilon )
  is_almost_eq(cos60, 0.5           , epsilon )
  is_almost_eq(cos60, 0.5  - epsilon, epsilon )

  epsilon = 1e-13 # 0.0000000000001
  print( "\n%.20f" % epsilon )
  is_almost_eq(cos60, 0.5  + epsilon, epsilon )
  is_almost_eq(cos60, 0.5           , epsilon )
  is_almost_eq(cos60, 0.5  - epsilon, epsilon )

  epsilon = 1e-14 # 0.00000000000001
  print( "\n%.20f" % epsilon )
  is_almost_eq(cos60, 0.5  + epsilon, epsilon )
  is_almost_eq(cos60, 0.5           , epsilon )
  is_almost_eq(cos60, 0.5  - epsilon, epsilon )

  epsilon = 1e-15 # 0.000000000000001
  print( "\n%.20f" % epsilon )
  is_almost_eq(cos60, 0.5  + epsilon, epsilon )
  is_almost_eq(cos60, 0.5           , epsilon )
  is_almost_eq(cos60, 0.5  - epsilon, epsilon )

  epsilon = 1e-16 # 0.0000000000000001
  print( "\n%.20f" % epsilon )
  is_almost_eq(cos60, 0.5  + epsilon, epsilon )
  is_almost_eq(cos60, 0.5           , epsilon )
  is_almost_eq(cos60, 0.5  - epsilon, epsilon )
```
Results :
```
0.50000000000000011000

0.00100000000000000000
0.500 ≅ 0.501 [0.500..0.502] true
0.500 ≅ 0.500 [0.499..0.501] true
0.500 ≅ 0.499 [0.498..0.500] true

0.00300000000000000010
0.500 ≅ 0.503 [0.500..0.506] true
0.500 ≅ 0.500 [0.497..0.503] true
0.500 ≅ 0.497 [0.494..0.500] true

0.00000000000100000000
0.500000000000 ≅ 0.500000000001 [0.500000000000..0.500000000002] true
0.500000000000 ≅ 0.500000000000 [0.499999999999..0.500000000001] true
0.500000000000 ≅ 0.499999999999 [0.499999999998..0.500000000000] true

0.00000000000010000000
0.5000000000000 ≅ 0.5000000000001 [0.5000000000000..0.5000000000002] true
0.5000000000000 ≅ 0.5000000000000 [0.4999999999999..0.5000000000001] true
0.5000000000000 ≅ 0.4999999999999 [0.4999999999998..0.5000000000000] true

0.00000000000001000000
0.500000000000000 ≅ 0.500000000000010 [0.500000000000000..0.500000000000020] true
0.500000000000000 ≅ 0.500000000000000 [0.499999999999990..0.500000000000010] true
0.500000000000000 ≅ 0.499999999999990 [0.499999999999980..0.500000000000000] true

0.00000000000000100000
0.500000000000000 ≅ 0.500000000000001 [0.500000000000000..0.500000000000002] true
0.500000000000000 ≅ 0.500000000000000 [0.499999999999999..0.500000000000001] true
0.500000000000000 ≅ 0.499999999999999 [0.499999999999998..0.500000000000000] true

0.00000000000000010000
0.50000000000000011 ≅ 0.50000000000000011 [0.50000000000000000..0.50000000000000022] true
0.50000000000000011 ≅ 0.50000000000000000 [0.49999999999999989..0.50000000000000011] true
0.50000000000000011 ≅ 0.49999999999999989 [0.49999999999999978..0.50000000000000000] false
```
N.B. Some problems arise when epsilon is extremely small (far from the normal values ​​normally used). Could it be solved by adding/subtracting the tolerance as a String ?

Conclusions : 
- The floating point equality test is and will remain a nigthmare...
- The partial solution I proposed addresses my specific problem, Is it "THE" solution ?
- I don't know if a better and simple function is possible. I wrote this hoping someone has already found the holy grail and is willing to share it with us !

Some links, for those interested in further research :
- [7 Dubious Solutions to Approximate Floating-Point Equality](https://www.reidatcheson.com/floating%20point/comparison/2019/03/20/floating-point-comparison.html)
- [Comparing Floating-Point Numbers Is Tricky](https://bitbashing.io/comparing-floats.html)

**Comment by rodrigo-borges** [comment]
> The partial solution I proposed addresses my specific problem, Is it "THE" solution ?

It isn't clear to me what is your problem. Isn't the purpose of assert_almost_eq precisely to account for floating points?

The premise of any approximation test should be "is this value almost the value it should be?". In the case of cos(60), the only logical test is `assert_almost_eq(cos60 , 0.500 , 0.001 , "Test 22")`. Testing for 0.501 or 0.499 makes no sense to me, and adapting an approximation adjustment in an already approximation-based test seems unnecessary.

**Comment by navy-cap-echo** [comment]
@rodrigo-borges 
> It isn't clear to me what is your problem. 

if test 3 works, test 23 should also work ! This is not the case !

> the only logical test is assert_almost_eq(cos60 , 0.500 , 0.001 , "Test 22"). Testing for 0.501 or 0.499 makes no sense to me

This is what an approximation function should do! if we want to test a value to within 0.001, we need to compare it with its lower limit (value - 0.001 = 0.499) and its upper limit (value + 0.001 = 0.501) and thus guarantee that the result is well within the desired range.

BTW, These values ​​are only there as an example, to emphasis the problem that I encountered during a comparison that should not have failed in a real project...

**Comment by rodrigo-borges** [comment]
@navy-cap-echo 

> if test 3 works, test 23 should also work

Not really, since 0.5 and cos(60) are coming from different operations and susceptible to floating. It's this exact behavior that justifies the existence of approximation tests.

> we need to compare it with its lower limit (value - 0.001 = 0.499) and its upper limit (value + 0.001 = 0.501)

Indeed, and you are doing so when testing for cos(60) ~= 0.5, and not cos(60) ~= 0.49. Testing for cos(60) ~= 0.49 is not a failure of the test function, but a failure of the choice of what to test for. When cos(60) ~= 0.5 fails, then there is a problem to be fixed.

If these values are examples for illustration, maybe you could provide some practical examples where tests being used appropriately fail.

**Comment by bitwes** [comment]
I think there is room for improvement here.  If nothing else, getting a failure message indicating that `0.5` is not included in the range of `.5` and `.498` is misleading.  It's not too bad though, considering it's the upper bound.  Failing at the bounds _should_ make you think "ahhhh, dang floating point probably".  Perhaps formatting the number to some amount of places greater than the `error_interval` precision would be a good approach...or just 20, like @navy-cap-echo you did.  20 is probably good for 80% of use cases.  The super right answer is to make it configurable.  

I'm not convinced there is anything in the comparison that needs to change though.  I agree with what @rodrigo-borges   says about "picking better values" and I'm having a hard time conjuring up an example that isn't covered by that.   @navy-cap-echo, if you have any other examples that would not be addressed by changing the message (to include more precision) please add them.

**Comment by bitwes** [comment]
#552 Adds additional precision to assert messages in various locations for various datatypes.  Reopen if this doesn't adequately address the issue.
