### ISSUE TITLE
Command line broken in 4.2.rc_1

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#526]
All my global magic I'm doing is finally breaking.  The command hard crashes on launch in 4.2.rc_1.  The panel seems to work fine still though.

**Comment by RevoluPowered** [comment]
Can confirm the command line is broken on our CI/CD too, we just upgraded to 4.2 internally.

I believe the tests run fine from the window as you said.

**Comment by RevoluPowered** [comment]
Update: your 4.2 branch works :D

**Comment by bitwes** [comment]
Fixed in 9.1.1
