### ISSUE TITLE
Cannot create a double of class in Godot 4.2rc1

### ISSUE THREAD

**Issue by wojtekpil** [bitwes/Gut#528]
This simple code:
```gdscript
extends GutTest

func test_sample():
	var doubled_node2d = double(Node2D).new()
```
Results in error:
<img width="321" alt="image" src="https://github.com/bitwes/Gut/assets/1286923/b9809595-f6f3-4635-866a-a235cc83f26f">

Looks like similar issue happens for any kind of custom gd script class.

**Comment by bitwes** [comment]
This is fixed in the `godot_4` branch but has not been put into a release yet.  Also, FYI, there is an issue with running GUT from command line in 4.2rc1 that has been fixed but hasn't been pushed up yet (still making sure everything works ok in 4.2)
