### ISSUE TITLE
Memory leaks after upgrade to v9.1.1

### ISSUE THREAD

**Issue by ngburke** [bitwes/Gut#542]
I believe GUT has started leaking textures / fonts in the latest release. I didn't see these before a big migration we did to Godot 4.2 / Gut 9.1. I see the following when running on the command line. Is anyone else experiencing this?

```
---- All tests passed! ----

ERROR: 3 RID allocations of type 'PN13RendererDummy14TextureStorage12DummyTextureE' were leaked at exit.
ERROR: 4 RID allocations of type 'PN18TextServerAdvanced12FontAdvancedE' were leaked at exit.
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2208)
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/io/resource.cpp:493)
```

**Comment by bitwes** [comment]
I've done a ton of experimenting trying to track down the leaks and I'm not having any luck.  I've created the [i542_leaks](https://github.com/bitwes/Gut/tree/i542_leaks) branch that has all of my debugging in it.

I've been able to reduce the number of things listed as leaked by removing some fonts in themes and references to themes.  There's still something it doesn't like, but I can't seem to find where it is coming from.

I've been able to replicate the warning with less code than `gut_cmdln.gd` in the command line runnable script `scratch/i542_experiments.gd`.  I've been concentrating mostly on the leaks listed as PackedScene since I figured those are the culprits.  There's a ton of things listed as leaked that I"m not sure actually are.

I was hoping to have this addressed for `9.2.0` but I don't want to hold that release up any longer.

Anyone who would like to dig into this...please do.

**Comment by ngburke** [comment]
> I've done a ton of experimenting trying to track down the leaks and I'm not having any luck. I've created the [i542_leaks](https://github.com/bitwes/Gut/tree/i542_leaks) branch that has all of my debugging in it.
> 
> I've been able to reduce the number of things listed as leaked by removing some fonts in themes and references to themes. There's still something it doesn't like, but I can't seem to find where it is coming from.
> 
> I've been able to replicate the warning with less code than `gut_cmdln.gd` in the command line runnable script `scratch/i542_experiments.gd`. I've been concentrating mostly on the leaks listed as PackedScene since I figured those are the culprits. There's a ton of things listed as leaked that I"m not sure actually are.
> 
> I was hoping to have this addressed for `9.2.0` but I don't want to hold that release up any longer.
> 
> Anyone who would like to dig into this...please do.

I'll take a look next week and see if I can help.

**Comment by ngburke** [comment]
I took a look at your branch and was able to find out some things, I hope it's enough for you to solve it in a more elegant way. The `GutUtils` class is a `RefCounted` class that has the `get_instance()` routine to instantiate it, storing a reference in the `_the_instance` variable.

This does limit the calls to `GutUtils.new()` to a single call, but many other classes are storing references to `_the_instance`   via `load('res://addons/gut/utils.gd').get_instance()` calls, and the one `GutUtils.get_instance()` call. Furthermore, there may possibly be a circular reference (not sure about this) being created somehow either by storing a reference of the class inside the `GutUtils` class itself (via `_the_instance`) or somewhere else - there is a warning about this situation in https://docs.godotengine.org/en/stable/classes/class_refcounted.html (cyclical reference preventing free).

When I put in a hack to have `GutUtils` extend Object (thus eliminating any referencing problems) like so:

```
@tool
class_name GutUtils
extends Object
# ------------------------------------------------------------------------------
# Description
# -----------
```
... and added `_utils.free()` at the bottom of `_on_tests_finished()` in `gut_cmdln.gd` like so:

```
	if(should_exit or (should_exit_on_success and _tester.get_fail_count() == 0)):
		# runner.queue_free()
		# runner.kill_scenes()
		# quit.call_deferred(exit_code)
		await end_it_all.call_deferred(exit_code)
	else:
		print("Tests finished, exit manually")

	_utils.free()
```

... then all the memory leaks went away when running with `--verbose`! May not be the way you'd like to solve it, but it should point in the right direction.

As an aside, I still saw leaks with one of my tests that used mocks and doubles, but that may have been my test problem - I just commented those out for now until I can dig further. Maybe you can test my hack/workaround with some known good (non-leaky) mocks/double/spy tests to make sure we're good there.

**Comment by bitwes** [comment]
@ngburke This seems to have done the trick.  I implemented it earlier this week, then dog fooded it in my own game.  DIdn't cause any errors and seems to work great.  Thanks for the idea, I never would have thought to do this.

**Comment by ngburke** [comment]
> @ngburke This seems to have done the trick. I implemented it earlier this week, then dog fooded it in my own game. DIdn't cause any errors and seems to work great. Thanks for the idea, I never would have thought to do this.

No worries, glad it worked out and thank you for the real fix!
