### ISSUE TITLE
The assert_typeof function is not working in Godot Engine 3.5.3 LTS

### ISSUE THREAD

**Issue by jcmljunior** [bitwes/Gut#543]
Hello, I found a problem when making dictionary comparisons using the “assert_typeof” function.
### The Problem:
[Failed]:  Expected [typeof(18) = 2(Int)] to equal [18(Dictionary)].

### Code:
```gdscript
func test_has_dict_in_increment_counter():
    for method in Mock.get_script().get_script_method_list():
      if method.get("name") != "increment_counter":
        continue
      
      # return: 18 18
      print(method.get("return").get("type"), TYPE_DICTIONARY)

      # test fail
      assert_typeof(method.get("return").get("type"), TYPE_DICTIONARY, "...")

      # test pass
      assert_true(method.get("return").get("type") == TYPE_DICTIONARY, "...")

      break

```

### Demo:

https://github.com/bitwes/Gut/assets/82642883/778866ff-5ed9-46db-95c8-d67d8ec4de6a

**Comment by bitwes** [comment]
In "test fail", don't call get_type.  assert_type_of calls type_of.  So
it's calling it on the result of get_type which is 18, which is an int
which results in 2 != 18.
