### ISSUE TITLE
GUT 9.2 not working with Godot 4.1.1 on WIndows

### ISSUE THREAD

**Issue by hadryel** [bitwes/Gut#566]
Hi! Sorry if this is stated somewhere, but I didn't find a way to make GUT work on my project. Tried 9.0 and 9.2 (latest) and getting errors when trying to use it.

```GDScript
--- GDScript language server started ---
  res://addons/gut/gui/editor_globals.gd:41 - Parse Error: Cannot call non-static function "get_editor_settings()" on the class "EditorInterface" directly. Make an instance instead.
  res://addons/gut/gut_plugin.gd:8 - Invalid call. Nonexistent function 'create_temp_directory' in base 'GDScript'.
  res://addons/gut/gui/OutputText.gd:88 - Invalid get index 'user_prefs' (on base: 'GDScript').
  res://addons/gut/gui/BottomPanelShortcuts.gd:5 - Invalid get index 'editor_shortcuts_path' (on base: 'GDScript').
  Can't open file from path 'res://addons/gut/fonts/CourierNew-Regular.ttf'.
  Can't open file from path 'res://addons/gut/fonts/CourierNew-Regular.ttf'.
  Can't open file from path 'res://addons/gut/fonts/CourierNew-Bold.ttf'.
  Can't open file from path 'res://addons/gut/fonts/CourierNew-Italic.ttf'.
  Can't open file from path 'res://addons/gut/fonts/CourierNew-BoldItalic.ttf'.
  res://addons/gut/gui/GutBottomPanel.gd:52 - Invalid call. Nonexistent function 'create_temp_directory' in base 'GDScript'.
  res://addons/gut/gui/BottomPanelShortcuts.gd:134 - Invalid type in function 'load' in base 'ConfigFile'. Cannot convert argument 1 from Nil to String.
```
and the panel is loaded like this:
![image](https://github.com/bitwes/Gut/assets/28874635/9580afac-a1f8-4c3c-a602-b68280e40e9b)

Trying to run the test from editor does nothing. I'm new to Godot, so I have no idea what can I edit to fix the error. Did I miss something? Should this be working or is it a WIP? Happens if I create a new project and add just Gut as well.

**Comment by bitwes** [comment]
You want GUT v9.1.1 for Godot 4.1:  https://github.com/bitwes/Gut/releases/tag/v9.1.1

9.2 just came out and requires Godot 4.2.  There are version checks in GUT, but I guess it's blowing up before it can output them.

**Comment by bitwes** [comment]
Make sure you completely delete the `res://addons/gut` folder before you copy over the new version just in case any files were moved or deleted.

**Comment by hadryel** [comment]
Hey, it worked! I manually added a `.gut_editor.config.json` for it to work (don't know if it should be created automatically), but my problem is solved. Thanks!

**Comment by bitwes** [comment]
Great.  GUT creates that file after settings get saved, but does print that message when it can't find it.
