### ISSUE TITLE
[Question] Is it possible to spy on a Signals connect method?

### ISSUE THREAD

**Issue by SavoVuksan** [bitwes/Gut#567]
Is it possible to spy on a Signals connect method?

I have a Double of a Resource and the resource has the changed signal. I would like to check if the connect function of that signal has been called. 

Would this be possible with gut?

**Comment by bitwes** [comment]
GUT has `assert_connected` and `assert_not_connected`.  These check if an object's signal is connected to another object (and optionally a specific method on the other object).  I think it would be possible to create a double of a signal and inject that into your other double, but that could get a little messy.

Let me know which approach you end up using, and if you need a hand implementing either.

https://gut.readthedocs.io/en/latest/Asserts-and-Methods.html#assert-connected

**Comment by SavoVuksan** [comment]
Hey there thanks for the fast reply. Just got back to it and I solved it by getting the connection list. I think my main issue was that I forgot that resources are kinda like singletons and I already had a connection on it. I will do some more unit tests and if I encounter a similar problem I will try one of your proposed solutions ^^.

**Comment by bitwes** [comment]
Reopen if you have any issues.
