### ISSUE TITLE
Having trouble installing GUT

### ISSUE THREAD

**Issue by wafflebottom** [bitwes/Gut#579]
Hello,

I am trying to use GUT, but I am running into issues with finding it on the Godot Asset Library. When I search 'gut' or 'Gut' or 'GUT', I cannot find your asset. So, I looked into the documentation and tried to follow the Download and Install instructions, but I get a bunch of Unicode parsing errors when I add the gut directory to my addons directory at the root of my project file. Then I try to activate the directory in the Setup section only to be met with this popup and no way to enable the plugin.

Unable to load addon script from path: 'res://addons/gut/gut_plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/gut/plugin.cfg' to prevent further errors.

Do you have any direction for me to get this one resolved?

**Comment by bitwes** [comment]
What version of godot are you on?  My last update changed the required 4.x
version to 4.2 so it won't show in the asset library for earlier versions
of godot.

The Unicode errors are fixed in the latest version, and is a known issue
for the earlier version.  It usually still loads though.

**Comment by wafflebottom** [comment]
Hmm. I'm using 4.1.2. I'll install the updated version and see if that does it. Thanks!
