### ISSUE TITLE
No errors but cant find the interface node!

### ISSUE THREAD

**Issue by moshujsg** [bitwes/Gut#583]
What it says, I think at some point it mentioned that cant find a cfg. I'm using godot 4.2.1 and neither me nor my teammate cant seem to find the scene to run teh tests

**Comment by moshujsg** [comment]
I see, the scene thing is because of a youtube video which is of the old version. However, the confusion comes because the documentation kinda says: download > set up the panel, however, at least form having looked at the video it was not very obvious to me how to get to that panel.

**Comment by bitwes** [comment]
Updating the tutorials I've put out is on my list.  So if you got the info from the ButchTeachesTyping channel then this should be resolved in the not so distant future.
