### ISSUE TITLE
Please voice your support for dependency injection in Godot

### ISSUE THREAD

**Issue by janosdebugs** [bitwes/Gut#590]
Hey folks,

my apologies for co-opting an issue for this purpose. Can I ask you to voice your support for [Godot proposal 8850](https://github.com/godotengine/godot-proposals/issues/8850) aiming to make it possible to use dependency injection in Godot?

Thank you for considering.

**Comment by bitwes** [comment]
I gave it the "thumbs up", and I'm watching the issue now.  I don't have much to add to the conversation, but I do think it would be very useful.  I'm not super excited about  someone making an issue to get my attention, but there aren't a lot of other ways to accomplish this.  I'm going to leave this open for another week or so and then close this out.
