### ISSUE TITLE
assert_string_contains does not check datatype prior to performing string operations

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#618]
# Versions
* Godot: 4.2
* GUT: 9.2.1 (main)
* OS: macOS Sonoma

# The Bug
```
func test_something():
    assert_string_contains(null, 'this breaks', false)
```
That test will cause the error:  
```
Debugger Break, Reason: 'Invalid call. Nonexistent function 'to_lower' in base 'Nil'.'
*Frame 0 - res://addons/gut/test.gd:849 in function 'assert_string_contains'
```

This should generate a failure that GUT cannot convert nil to String, but it breaks isntead.

**Comment by nycdotnet** [comment]
Maybe I can try this?

**Comment by bitwes** [comment]
@bitwes Sure.  Tests for asserts are in `res://test/unit/test_test.gd`
