### ISSUE TITLE
Timer never stops in integration tests

### ISSUE THREAD

**Issue by kamran-charles-nayebi** [bitwes/Gut#637]
# Versions
Godot: v4.2.2.stable.official.15073afe3
GUT: 9.2.1
OS: Linux Mint 21.2 Cinnamon

# The Bug
I'm trying to test if a cooldown system works in an integration test, but the timer never seems to stop after waiting for the specified time. Very sorry if this is user error, but I could not find out anything about this in the docs.

# Steps To Reproduce
``` gdscript
func test_timer() -> void:
	# Given
	var test_timer := Timer.new()
	add_child_autofree(test_timer)
	test_timer.wait_time = 0.1
	
	# When
	test_timer.start()
	await wait_seconds(0.2)
	
	# Then
	assert_true(test_timer.is_stopped())
```

**Comment by bitwes** [comment]
The problem is that Timer's `one_shot` property is false by default so the timer runs again after the timeout.  Add `test_timer.one_shot = true` and it will pass.

**Comment by kamran-charles-nayebi** [comment]
It does! Thank you very much
