### ISSUE TITLE
Add `assert_not_between`

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#66]
I haven't found a need for it but I'm sure there is a use case for asserting a number is not in an arbitrary range of values.  The upper and lower bounds should not be included in the range it is checking against:
* `expected < min and expected > max`

**Comment by nilold** [comment]
Should it be inclusive?
assert_not_between(1,1,5) -> fails
assert_not_between(5,1,5) -> fails

**Comment by bitwes** [comment]
I think exclusive.  I've updated the description to avoid confusion.  My random thought process below...

There appears to be some inconsistencies.  The descriptions said to be inclusive but the code sample did not.  `assert_between` includes the upper bounds but not the lower. I think there was a good reason for doing that but I can't remember it now. `assert_almost_eq` includes low and high.  When I think "pick a number between 1 and 10" then that should be inclusive...and when I think "not between 10 and 20"...I think below 10 and greater than 20...so exclusive. 

I wonder if these should be changed to `assert_within` and `assert_not_within`.  I think "within" implies inclusivity better than "between" does (`assert_within` would be inclusive and `assert_not_within` would not be).  Too late now I guess.  This shouldn't be this hard to figure out.

**Comment by nilold** [comment]
I agree with your semantics. `Within` sounds inclusive and `between`, exclusive, but I don't see this applied in practice. E.g. in SQL, between is inclusive by default. I think the most important is to be clear in the code or documentation.

Another option, which is more user-friendly in my opinion, is to have `assert_not_between_inclusive` and `assert_not_between_exclusive. Doing the same with `assert_between` we would have to have an alias for and maybe deprecate the non-explicit version in the future.
We could do this with between/within as well, but in my opinion, more explicit is better.

This naming would follow the Zen of ~Python~ GdScript. But I would understand if you prefer not to work with deprecation for now.

**Comment by bitwes** [comment]
I'll mull it over a little.  I like to be verbose but prefer shorter names
with tools so I'm on the fence to make two big name asserts   I think the
pass/fail message helps clear things up.  And if you are using this assert
you should be testing the bounds as well.  On the other hand, I've used
this kind of assert for random values so you aren't guaranteed to hit the
bounds of you don't roll enough values.

I've already added a deprecation system to GUT so it's trivial to mark a
method as deprecated.

**Comment by nilold** [comment]
Sure.
Can I take this and implement the `assert_not_between` while you digest those thoughts? Most of the code, considering the tests won't change if we decide for one or another, so we can at least have a PR opened in the meantime.

**Comment by bitwes** [comment]
I agree.  It's all yours.
