### ISSUE TITLE
Rename (alias) asserts/methods.  What names bug you?

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#69]
There are some asserts and methods that I don't like the names of anymore.  Here's a list of the ones I don't like.  I'm open to other suggestions.  I'd like to make aliases for these methods with the new better awesome names.  The documentation will change to use these new names but the old ones will stick around as to not cause undue headache.

# Setup/Teardown
In using other unit testing frameworks I've become quite fond of 
* `before_all` instead of `prerun_setup`
* `before_each` instead of `setup`
* `after_each` instead of `teardown` 
* `after_all` instead of `postrun_teardown`

I think these are easier to remember and read better.

# Asserts
* `assert_accessors` instead of `assert_get_set_methods`
  * Maybe add an `assert_has_get` and an `assert_has_set`.  These would only be able to verify that the method exists, not that it acts properly since it wouldn't have a method to call after setting, or vice versa.
* `assert_is` instead of `assert_extends` since the keyword changed from `extends` to `is`.

Any others?

**Comment by Xrayez** [comment]
I vote for `before_all/each` and `after_all/each` names because when I first stumbled upon names like `teardown` I had to look up docs to be sure what it does (and it would be easier for non-native speakers to understand).

**Comment by paulhocker** [comment]
+1 on before/after rename
+1 assert_accessors (less underscores)
+1 assert_is (makes more sense)

**Comment by bitwes** [comment]
Implemeted
