### ISSUE TITLE
Command line options ignored with respect to config file

### ISSUE THREAD

**Issue by Xrayez** [bitwes/Gut#72]
When `.gutconfig.json` is created and set, running gut from from command line would not allow to set command line options even if the configuration file doesn't define (override) such options.

For instance:
 `.gutconfig.json`:
```json
{
    "dirs":["res://tests/unit/"],
}
```
_Notice no ` "should_exit" ` defined in `.gutconfig.json`_ 

```bash
godot -s addons/gut/gut_cmdln.gd -gexit
```

The result is that the window is still open after tests ran despite explicitly telling gut to exit.

**Comment by bitwes** [comment]
Fixed in 6.5.0
