### ISSUE TITLE
Simplify GUT install & update

### ISSUE THREAD

**Issue by caryoscelus** [bitwes/Gut#8]
Manual file copying doesn't sound like a good way to manage dependencies.

Possible solutions include:
- separate test/gut into its own repository and use it as git submodule (or subtree) here and in any project using gut
- make assetlib package - seems like official Godot way, but there is no auto-update and it depends on another third-party servers
- use some external package manager

**Comment by bitwes** [comment]
Agreed.  I was going to at least maintain zips in the releases but that seems super tedious.

I think the assetlib package might be the best first choice.  A subtree is probably a good idea regardless of delivery mechanism.  

I thought about creating a script to install Gut into a project.  It could also update it as well.  There's a lot of caveats to that approach though.  Do you support multiple directory structures?  What language to write it in.  I would like to use a language most people already have installed, but have no idea what that would be.

This is definitely something to be implemented.  I haven't seen widespread use of the repo yet, so maybe it's something to cover as it becomes more of an issue.

**Comment by bitwes** [comment]
DONE!!
