### ISSUE TITLE
Closing Gut Window Produces Error

### ISSUE THREAD

**Issue by paulhocker** [bitwes/Gut#84]
Godot Version: 3.0.5.stable.official.6a88e22
Platform: Windows

The Error happens after closing the Test window, but does not appear to prevent the App from running or cause any problems with Tests. It only seems to occur when any type of Test is run. I did test it on an Empty Scene with no Tests specified on Gut, and closing the Window produces no errors.

Here is the Error I usually see - the tail end appears to get cutoff sometimes

```
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100
ERROR: ~
```

**Comment by paulhocker** [comment]
I think this might be related to a bug already open for Godot with respect to resources not being freed before the Game exits.

https://github.com/godotengine/godot/issues/8985

I will investigate some more, and if it truly is related, I will close this issue.

**Comment by paulhocker** [comment]
After doing some more research, I can confirm that this is a bug in Gut, but I would not consider it to be very high on the list. 

I think we can probably close this unless the moderator feels that it is something that needs to be addressed.

**Comment by bitwes** [comment]
#86 is basically this same bug but there's more discussion on #86 so I'm going to close this one.
