### ISSUE TITLE
Conflicting script names with Godot 3.1

### ISSUE THREAD

**Issue by Xrayez** [bitwes/Gut#85]
Version: 6.6.0

(Note: I base this info against Godot 3.1 alpha build)

1. Conflicting `class_name` is now a [reserved keyword](https://github.com/godotengine/godot/commit/a3f1ee5c57d7818eaa30c272dd97d1bbb06ca099) used for naming scripts to be accesible globally within a project (could be renamed as `script_name`)
2. Conflicting `class Script` inner class shadows native class (could be renamed as `ScriptInfo`).

While Godot 3.1 is not out yet, this must be fixed in the future releases of GUT eventually.

**Comment by bitwes** [comment]
I've started a Godot 3_1 branch.  I got things to run but there seems to be some issues with the `user://` and I don't know yet if it's Gut or Godot.  It appears that `user://` now defaults to the project's root directory which is bad b/c the tests I have for gut deletes things.


https://github.com/bitwes/Gut/tree/godot_3_1

**Comment by Xrayez** [comment]
There's still one thing that prevented me to run GUT 6.6.2 in 3.1:
https://github.com/bitwes/Gut/blob/3f4d31e6b75d6ecb4fed3bfd8dacd9f6f8f154c6/addons/gut/gut.gd#L549

Changed this `the_script.class_name` to `the_script.inner_class_name` and seems to work fine.

**Comment by bitwes** [comment]
fixed it, don't know how i missed it.

FYI, I'll be putting more attention to 3_1 when it goes to release candidate which I think is coming up soon.
