### ISSUE TITLE
Command line segmentation fault on closing test window

### ISSUE THREAD

**Issue by Xrayez** [bitwes/Gut#86]
GUT version: 6.6.0
Godot version: 3.1 alpha+
Platform: Windows 10

I use git pre-commit hook to run tests as some sort of CI, and git won't allow me to go past this point, even if all tests passed (after closing a window):
```
.git/hooks/pre-commit: line 9:  3604 Segmentation fault      godot -d -s addons/gut/gut_cmdln.gd
```
I think #84 might cause this error that I've stumbled upon several times, but can't seem to reproduce it (or actually can't isolate the problem).

My hook looks like this:
```bash
#!/bin/sh

# Run tests
godot -d -s addons/gut/gut_cmdln.gd
```

I'll report more info when I can pinpoint the problem.

**Comment by bitwes** [comment]
With this command (from inside the Gut project)
```
godot --path $PWD -s addons/gut/gut_cmdln.gd -gselect=test_gut.gd -gdirs=res://test -ginclude_subdirs -gexit
```
I see these errors
```
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:100.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1989.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:418.
```

These could be the culprit and are the same listed in #84 .  They've never gotten in the way before but I've always wanted to clean it up which is why I've left #84 open.  Looks like it is time to dig into them.

**Comment by Xrayez** [comment]
My  .gutconfig.json:
```json
{
    "dirs":["res://tests/unit/", "res://tests/integration/"],
    "should_exit":false,
    "ignore_pause":true,
    "log": 1,
    "should_maximize":true
}
```
> They've never gotten in the way before but I've always wanted to clean it up

I've been able to fix this issue before somehow, it seemed like it happened due to some script/scene parsing errors by Godot (not GUT scripts, but mine).

**Comment by bitwes** [comment]
I've narrowed it down a little.  

### Doesn't happen if it doesn't parse directories
If you remove your `.gutconfig` and run 
```
godot --path $PWD -s addons/gut/gut_cmdln.gd
```
and then close the window, the error doesn't seem to happen. 

### Doesn't happen when showing help
It also doesn't happen if you specify the help `-gh` option.  Which excludes the command line script.

### Happens if parsing occurs but doesn't run tests
I've also been able to make the errors appear if it parses the directories but doesn't run anything.  So if you run something like
```
godot30 --path $PWD -s addons/gut/gut_cmdln.gd -gdir=res://test -ginclude_subdirs -gselect=does_not_exist.gd
```
then you will still get the errors.

### Same behavior with Gut main.tscn scene
I've been able to verify the same behavior if I run the `main.tscn` inside the gut project from the command line.
```
godot --path $PWD scenes/main.tscn
```
If the scene has gut configured with directories then the errors occur, if not then they don't happen.

**Comment by bitwes** [comment]
You might be able to work around this by making a scene that has Gut in it.  With your own scene you could check the Gut object for failures with `get_fail_count()`.  You'll have to connect to the undocumented signal `tests_finished` on the Gut object.  You would then write some indicator to a file some indicator of success/failure.  You can then run your scene with a script, ignore the return value from running the scene and check the file.  It's a bit wonky but should work in the meantime.

Or, it looks like you're running a bash script, you could just have the script parse the output and return 1 or 0.  That's probably way easier than the Rube Goldberg machine from above.

**Comment by Xrayez** [comment]
> You would then write some indicator to a file some indicator of success/failure.

Yes, I considered that, I should probably try it out. I was thinking maybe it could be an option to write tests result to a file in `gut_temp_directory` as a feature.

I've also tried your suggestions removing .gutconfig file and such, but I compiled recent Godot version and the problem is gone either way, again!

**Comment by bitwes** [comment]
Are you still getting the errors at the end of the run but not the Segmentation fault?

**Comment by Xrayez** [comment]
Yes, test pass and the errors are there after closing the test window with no segfault now.

**Comment by paulhocker** [comment]
what branch are these changes on so I can test them out?

**Comment by bitwes** [comment]
I haven't pushed up any changes yet.  There's some changes in 3.1 but nothing for this.  I've been able to address some of the causes but not all of them yet.  I haven't seen the segmentation fault myself, just the errors.

**Comment by Xrayez** [comment]
This might be only reproducible using git pre-commit hook because the segmentation fault occurs right after exit, which git hook happens to catch and treat it as an error? Most likely this is indeed Godot's culprit and has little to do with GUT though.

**Comment by Xrayez** [comment]
Closing for now as the issue doesn't seem to be reproducible anymore whatever I tried, still not sure the cause. Currently using Godot 3.1 beta 10 or so.
