### ISSUE TITLE
Simulate behavior unclear

### ISSUE THREAD

**Issue by MrMinimal** [bitwes/Gut#90]
https://github.com/bitwes/Gut/wiki/Simulate

The wiki mentions that either `_process` or `_fixed_process` are called. It does not specify how to control which one is called. Are both called or are they exclusive?

**Comment by bitwes** [comment]
Objects shouldn't have both (I don't think), so it runs both.  Basically if it has the method it runs it.  

I'll update the readme.  

Also, I think there's a bug since in 3.0 the names changed and I'm not sure if gut was updated.

**Comment by bitwes** [comment]
Verified that simulate was updated to use the new Godot method `_physics_process` and then updated the documentation.  I also tried to explain things a little more.  Please read it over and close if it's clear enough now.

**Comment by MrMinimal** [comment]
So glad you are this involved. I would edit it myself, but "you object" would be "your object". Also I'd leave out the part that you are not supposed to have both `_process` and `_physics_process` because there are definatly instances where you want that (latency related mostly).

Other than that, the wiki is solid now!

**Comment by bitwes** [comment]
Fixed the "you" and removed the extra bit about both.
