### ISSUE TITLE
[Godot 3.1] `user://` is project root on mac

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#91]
Not sure if this is a bug with 3.1 or if I'm supposed to set the user directory, but `user://` appears to be set too the project's root and that causes issues with the tests in this project.

Using Gut might be a problem too since it makes directories for Doubles but the worst case for that *should* be extra files in your project.

**Comment by MrMinimal** [comment]
hm weird behaviour. But I also read it depends on the platform where `user://` acutally is.
Might not be the worst idea to just have a hidden folder in the projects root for the tests. Can easily be gitignored.

**Comment by bitwes** [comment]
I'm going to wait before I do anything.  It hasn't been like that in any previous release.  I'm just not sure yet if something has changed or is broke.

**Comment by bitwes** [comment]
This was a duplicate of #95 which has been fixed.
